Repository nextcloud/android, pull requests merged in 2018-03, with the labels that each got.

#2255 Fix #2140: waiting for Wifi
  src/main/res/values/strings.xml
Labels: 2. to review

#2254 Fix wrong status message on non existing files on upload
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#2200 Fix failing operations (create folder, download file) due to user agent change
  build.gradle
  src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review, backport

#2268 Backport e2e user agent fix
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 2. to review

#2283 Added confirmation before exit (Fixed #2276)
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/res/values/strings.xml
Labels: 2. to review

#2264 Remove Select all from the 3-dot-menu as that's already in the multis…
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#2322 Show long subtext of notification
  src/main/res/layout/activity_list_item.xml
Labels: 2. to review

#2317 Generating avatar as fallback
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review

#2332 Remove locking
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
Labels: 2. to review

#2186 E2E: do not modifiy userid
  src/main/java/com/owncloud/android/utils/CsrHelper.java
Labels: 2. to review, backport

#2217 Resizing of the activity icon
  src/main/res/layout/activity_list_item.xml
Labels: 2. to review

#2205 Fix crash on 4.x devices
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review, backport

#2207 Close cursor
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/jobs/ContactsImportJob.java
Labels: 2. to review

#2210 if searchView does not exist, search is not opened
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#2331 Send icons: icon size, app chooser
  src/main/java/com/owncloud/android/ui/adapter/SendButtonAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/layout/send_button.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2338 Update changelog
  CHANGELOG.md
Labels: 2. to review

#2347 Use contentResolver directly
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review

#2260 Try to prevent NPE on notification manager
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#2218 Show multiaccount intro only if multiaccount is enabled
  src/main/java/com/owncloud/android/features/FeatureList.java
  src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
Labels: 2. to review

#2233 Show files in FolderPicker
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2221 Copy/move starts within current folder
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2251 if nothing received to upload, app crashed
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 2. to review

#2038 Speed up sync
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 2. to review

#2160 Make multiple whitespaces on twitter working
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#2179 New drone version
  .drone.yml
Labels: 2. to review

#2228 TimSort: Add correct null check
  src/main/java/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java
Labels: 2. to review

#2262 Add natural sorting
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/third_parties/daveKoeller/AlphanumComparator.java
  src/test/java/com/owncloud/android/utils/TestSorting.java
Labels: 2. to review

#2253 Improve syncing code
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/services/observer/FileObserverService.java
  src/main/java/com/owncloud/android/services/observer/FolderObserver.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
Labels: 2. to review

#2090 List files can be null
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review

#2211 Instead of returning null on getServerVersion(), it returns now a version
  src/main/java/com/owncloud/android/authentication/AccountUtils.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  src/main/java/com/owncloud/android/ui/fragment/EditShareFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/utils/glide/HttpStreamFetcher.java
Labels: 2. to review

#2222 Move lib implementation to flavors
  build.gradle
Labels: 2. to review

#2373 Check if we’re on unmetered wifi
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
Labels: 2. to review

#2367 Use long instead of integer
  src/main/java/third_parties/daveKoeller/AlphanumComparator.java
  src/test/java/com/owncloud/android/utils/TestSorting.java
Labels: 2. to review

#2183 If no thumbnail exists, check if resized version exist and use this
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review

#2342 Use magical vectors
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#2376 Update android job
  build.gradle
Labels: 2. to review

#2360 Hiding the action bar in case of fullscreen video playback
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
Labels: 2. to review

#2352 check walled garden only on wifi
  src/main/java/com/owncloud/android/utils/ConnectivityUtils.java
Labels: 2. to review

#2380 minor version was on wrong location
  build.gradle
Labels: 2. to review

#2354 UX: improve auto upload list header
  src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.java
  src/main/res/drawable-hdpi/ic_image_18dp.png
  src/main/res/drawable-hdpi/ic_video_18dp.png
  src/main/res/drawable-mdpi/ic_image_18dp.png
  src/main/res/drawable-mdpi/ic_video_18dp.png
  src/main/res/drawable-xhdpi/ic_image_18dp.png
  src/main/res/drawable-xhdpi/ic_video_18dp.png
  src/main/res/drawable-xxhdpi/ic_image_18dp.png
  src/main/res/drawable-xxhdpi/ic_video_18dp.png
  src/main/res/drawable-xxxhdpi/ic_image_18dp.png
  src/main/res/drawable-xxxhdpi/ic_video_18dp.png
  src/main/res/drawable/folder_star_32dp.xml
  src/main/res/drawable/image_32dp.xml
  src/main/res/drawable/video_32dp.xml
  src/main/res/layout/synced_folders_item_header.xml
Labels: 2. to review

#2385 Drawer: check if account is null
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 3. to release

#2369 No blocking sync dialog
  build.gradle
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 3. to release

#2384 Init thumbnail cache: catch all exceptions
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 3. to release

#2383 context might be null, so fallback
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#2387 OnServiceConnnected: File not found
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#2370 If e2e app is disabled, show info
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/values/strings.xml
Labels: 3. to release

#2372 Fixes #2315 and other issues
  src/generic/java/com/owncloud/android/utils/PushUtils.java
  src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseInstanceIDService.java
  src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseMessagingService.java
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
  src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java
  src/main/java/com/owncloud/android/datamodel/SignatureVerification.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/versionDev/java/com/owncloud/android/utils/PushUtils.java
Labels: 2. to review

#2206 Add showing icon on external folders
  .pullapprove.yml
  drawable_resources/folder_external.svg
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/FileListListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploaderAdapter.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/res/drawable/folder_external.xml
Labels: 3. to release

#2398 Fix column name
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 2. to review, high

#2399 3.1.0RC1
  CHANGELOG.md
  build.gradle
Labels: 2. to review

#2405 android.database.CursorWindowAllocationException
  scripts/lint/lint-results.txt
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 2. to review

#2404 Resume activity crash due to grid view check
  src/main/java/com/owncloud/android/db/PreferenceManager.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review
