Repository nextcloud/android, pull requests merged in 2018-06, with the labels that each got.

#2665 fix transifex mappings: he->iw and id->in
  .tx/config
  scripts/lint/lint-results.txt
  src/main/res/values-in/strings.xml
  src/main/res/values-iw/strings.xml
Labels: 2. to review

#2683 util: Added @Override annotation where applicable.
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
Labels: 2. to review

#2661 Reword empty activity message
  src/main/res/values/strings.xml
Labels: 2. to review

#2651 Do not process result of async task if activity is stopped
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesContract.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesPresenter.java
Labels: 2. to review, backport-request

#2649 Explicitly finish preferences
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
Labels: 2. to review, backport-request

#2631 tint zip icon same as folder icon
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
Labels: 2. to review

#2626 Shorten code and improve readability via a menu helper
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
Labels: 2. to review

#2550 White theming
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FingerprintActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ParticipateActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/menu/upload_files_picker.xml
Labels: 2. to review

#2680 Use context instead of static getAppContext
  scripts/lint/getBranchName.sh
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  src/main/java/com/owncloud/android/authentication/AccountUtils.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/StorageMigration.java
Labels: 2. to review

#2648 File detail view: store file/account when suspending fragments
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 2. to review, backport-request

#2620 Minor cleanup of FileSortOrderByName and FileSortOrderBySize
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
Labels: 2. to review

#2689 Auth: Do not use context on static
  build.gradle
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#2669 Codacy fixes
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
Labels: 2. to review

#2686 Use correct exception
  src/main/java/com/owncloud/android/ui/TextDrawable.java
  src/main/java/com/owncloud/android/ui/adapter/ShareUserListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 2. to review

#2682 ui:fragment: Use isEmpty() to check if list of activities is empty.
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
Labels: 2. to review

#2698 fragment:util: Added private constructor to hide the inherit public one
  src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java
Labels: 2. to review

#2225 getWindow(): The current window, or null if the activity is not visual.
  src/main/java/com/owncloud/android/authentication/PassCodeManager.java
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
  src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/CredentialsDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#2389 Refactor : convert toast to snackbar
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/CopyToClipboardActivity.java
  src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/res/values-zh-rTW/strings.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2671 Iteration 3 for file detail & new sharing
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/operations/UpdateSharePermissionsOperation.java
  src/main/java/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java
  src/main/java/com/owncloud/android/ui/fragment/util/SharingMenuHelper.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/menu/file_detail_sharing_link_menu.xml
  src/main/res/menu/file_detail_sharing_menu.xml
Labels: 2. to review

#2703 Bump to 3.2.0
  CHANGELOG.md
  build.gradle
Labels: 2. to review

#2704 3.2.0 Changelog added
  CHANGELOG.md
  build.gradle
Labels: 2. to review

#2706 Crash on preferences: NPE check
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
Labels: 2. to review

#2700 Iteration 4 for File detail & new sharing - email share
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java
  src/main/java/com/owncloud/android/ui/fragment/util/SharingMenuHelper.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#2685 Add support for file versions
  build.gradle
  drawable_resources/ic_history.svg
  src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
  src/main/java/com/owncloud/android/operations/RestoreFileVersionOperation.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityAndVersionListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/FileDetailTabAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/RemoveFileDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/interfaces/VersionListInterface.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/res/drawable/ic_history.xml
  src/main/res/layout/version_list_item.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
  src/test/java/com/owncloud/android/utils/ErrorMessageAdapterUnitTest.java
Labels: 2. to review

#2716 fix wrong library from https://github.com/nextcloud/android/pull/2685
  build.gradle
Labels: 2. to review

#2730 Display copy icon and adding send action to the link menu
  drawable_resources/ic_content-copy.svg
  src/main/java/com/owncloud/android/ui/activity/CopyToClipboardActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/utils/ClipboardUtil.java
  src/main/res/drawable/ic_content_copy.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/menu/file_detail_sharing_link_menu.xml
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#2690 Iteration 5 for File detail & new sharing - Comments
  src/main/java/com/owncloud/android/operations/CommentFileOperation.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileFragment.java
  src/main/java/com/owncloud/android/ui/interfaces/VersionListInterface.java
  src/main/res/drawable/ic_send.xml
  src/main/res/layout/file_details_activities_fragment.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2733 Update release cycle description
  CONTRIBUTING.md
Labels: 2. to review

#2727 Wrong behaviour on privacy tab
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
Labels: 2. to review, backport-request

#2734 fix wrong access to mFilesAll
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
Labels: 2. to review, backport-request

#2732 Enhance outdated server warning
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/res/values/setup.xml
Labels: 2. to review

#2713 Feedback: test if any email app is available
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#2588 Support for trashbin
  drawable_resources/history.svg
  drawable_resources/ic_delete.svg
  src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/EmptyTrashbinFileOperation.java
  src/main/java/com/owncloud/android/operations/RestoreTrashbinFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/DiskLruImageCacheFileProvider.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploaderAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/interfaces/TrashbinActivityInterface.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinContract.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinPresenter.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinRepository.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/FileSortOrder.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/java/org/nextcloud/providers/cursors/FileCursor.java
  src/main/java/third_parties/daveKoeller/AlphanumComparator.java
  src/main/res/drawable/ic_delete.xml
  src/main/res/drawable/nav_trashbin.xml
  src/main/res/layout/trashbin_activity.xml
  src/main/res/layout/trashbin_item.xml
  src/main/res/menu/drawer_menu.xml
  src/main/res/menu/trashbin_actions_menu.xml
  src/main/res/menu/trashbin_options_menu.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2735 Revert local search
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#2724 Backport mail share creation
  build.gradle
  scripts/lint/lint-results.txt
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#2715 Backport mail sharing
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/operations/UpdateSharePermissionsOperation.java
  src/main/java/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java
  src/main/java/com/owncloud/android/ui/fragment/util/SharingMenuHelper.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/menu/file_detail_sharing_link_menu.xml
  src/main/res/menu/file_detail_sharing_menu.xml
Labels: 2. to review

#2739 Backport share link handling
  drawable_resources/ic_content-copy.svg
  src/main/java/com/owncloud/android/ui/activity/CopyToClipboardActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/utils/ClipboardUtil.java
  src/main/res/drawable/ic_content_copy.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/menu/file_detail_sharing_link_menu.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2743 Backport: Wrong behaviour on privacy tab
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
Labels: 2. to review

#2744 Backport: fix wrong access to mFilesAll
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
Labels: 2. to review

#2745 Backport: Revert local search
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2760 Added missing @Override annotations above applicable method signatures.
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
Labels: 2. to review

#2757 Fix Codacy issues
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 1. developing

#2750 Account may be null
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
Labels: 2. to review, backport-request

#2748 ContactListFragment: fix NPE
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review, backport-request

#2749 Intent may be null
  src/main/java/com/owncloud/android/services/OperationsService.java
Labels: 2. to review, backport-request

#2755 Release 3.2.1 - Preparation
  CHANGELOG.md
  build.gradle
Labels: 2. to review

#2741 Add findbugs to drone
  .drone.yml
  build.gradle
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
  scripts/analysis/lint-results.txt
  scripts/analysis/lint-up.rb
  scripts/lint/lint-results.txt
  scripts/lint/lint-up-wrapper.sh
  wait_for_emulator.sh
Labels: 2. to review

#2747 Share link creation via bottom sheet for files in OCFileList
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review

#2751 Activity stream / file detail design
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityAndVersionListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/res/layout/activity_list_item.xml
Labels: 2. to review

#2752 findbugs: several warnings
  findbugs-filter.xml
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/ui/adapter/GroupAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
Labels: 2. to review

#2726 Search enhancements
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2769 Backport of #2750: Account may be null
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
Labels: 2. to review

#2771 Backport of #2748: Use correct context
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review
