Repository nextcloud/android, pull requests merged in 2018-02, with the labels that each got.

#2146 Fix time display in activities list
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
Labels: 2. to review

#2138 Fix#2125:ShareDialogFix
  src/main/res/layout/share_file_layout.xml
Labels: 2. to review

#2109 Don't beautify empty inputs
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#2158 Delete public key if storage of private key did not worked
  build.gradle
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
Labels: 2. to review, backport

#2149 Fix SSL
  src/generic/java/com/owncloud/android/utils/SecurityUtils.java
  src/gplay/java/com/owncloud/android/utils/SecurityUtils.java
  src/main/java/com/owncloud/android/MainApp.java
  src/versionDev/java/com/owncloud/android/utils/SecurityUtils.java
Labels: 2. to review, backport

#2154 Encryption: Get IV directly from the cipher object when encrypting the private key
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review, E2E

#2166 Backport fix push
  src/generic/java/com/owncloud/android/utils/PushUtils.java
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
  src/main/java/com/owncloud/android/db/PreferenceManager.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/versionDev/java/com/owncloud/android/utils/PushUtils.java
Labels: 2. to review

#2169 Backport fix ssl
  src/generic/java/com/owncloud/android/utils/SecurityUtils.java
  src/gplay/java/com/owncloud/android/utils/SecurityUtils.java
  src/main/java/com/owncloud/android/MainApp.java
  src/versionDev/java/com/owncloud/android/utils/SecurityUtils.java
Labels: 2. to review

#2170 Backport delete public key
  build.gradle
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
Labels: 2. to review

#2171 Backport e2e iv
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review

#2163 Implement folder structure
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review

#2187 fix template link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 2. to review

#2201 use correct size for png
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review

#2180 Correctly load saved folder on resume
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2148 Add nicer variable based versioning calculation
  build.gradle
Labels: 2. to review

#2120 Screenshots: further languages
  fastlane/Screengrabfile
  scripts/screenshots/addMockDevice.sh
  scripts/screenshots/phone.svg
  scripts/screenshots/sevenInch.svg
Labels: 2. to review

#2037 Do not ignore ignoreEtags
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2144 codacy: remove unused code
  scripts/lint/lint-results.txt
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review

#2237 Transifex cherry picks since 3.0.1 for 3.0.2
  src/generic/fastlane/metadata/android/fr-FR/full_description.txt
  src/generic/fastlane/metadata/android/is-IS/full_description.txt
  src/generic/fastlane/metadata/android/is-IS/short_description.txt
  src/generic/fastlane/metadata/android/is-IS/title.txt
  src/generic/fastlane/metadata/android/nl-NL/full_description.txt
  src/main/res/values-ar/strings.xml
  src/main/res/values-ast/strings.xml
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-b+es+419/strings.xml
  src/main/res/values-bg-rBG/strings.xml
  src/main/res/values-ca/strings.xml
  src/main/res/values-cs-rCZ/strings.xml
  src/main/res/values-da/strings.xml
  src/main/res/values-de-rDE/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-el/strings.xml
  src/main/res/values-es-rAR/strings.xml
  src/main/res/values-es-rCL/strings.xml
  src/main/res/values-es-rCO/strings.xml
  src/main/res/values-es-rCR/strings.xml
  src/main/res/values-es-rDO/strings.xml
  src/main/res/values-es-rEC/strings.xml
  src/main/res/values-es-rGT/strings.xml
  src/main/res/values-es-rHN/strings.xml
  src/main/res/values-es-rMX/strings.xml
  src/main/res/values-es-rNI/strings.xml
  src/main/res/values-es-rPA/strings.xml
  src/main/res/values-es-rPE/strings.xml
  src/main/res/values-es-rPR/strings.xml
  src/main/res/values-es-rPY/strings.xml
  src/main/res/values-es-rSV/strings.xml
  src/main/res/values-es-rUY/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-et-rEE/strings.xml
  src/main/res/values-eu/strings.xml
  src/main/res/values-fi-rFI/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-hu-rHU/strings.xml
  src/main/res/values-id/strings.xml
  src/main/res/values-is/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-ka-rGE/strings.xml
  src/main/res/values-ko/strings.xml
  src/main/res/values-lt-rLT/strings.xml
  src/main/res/values-nb-rNO/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sk-rSK/strings.xml
  src/main/res/values-sl/strings.xml
  src/main/res/values-sq/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-sv/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values-zh-rCN/strings.xml
  src/main/res/values-zh-rTW/strings.xml
  src/versionDev/fastlane/metadata/android/fr-FR/full_description.txt
  src/versionDev/fastlane/metadata/android/nl-NL/full_description.txt
Labels: 2. to review

#2234 Backport e2e user agent
  build.gradle
  src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review

#2231 Backport fix action bar android4
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#2235 Backport e2e name with at
  src/main/java/com/owncloud/android/utils/CsrHelper.java
Labels: 2. to review

#2238 Bump to 3.0.2
  CHANGELOG.md
  build.gradle
Labels: 2. to review
