Repository nextcloud/android, pull requests merged in 2018-04, with the labels that each got.

#2427 FileDisplayActivity: Replaced duplicate subexpression in if statement with instantVideoUploadEnabled preference.
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#2410 Spelling: End-to-end encryption, notifications sent by server
  src/main/res/values/strings.xml
Labels: 3. to release

#2401 Fix typos
  CONTRIBUTING.md
  SETUP.md
Labels: 2. to review

#2433 Removal of change password menu entry
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/res/menu/user_info_menu.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2164 Grey-out auto upload options until enabled
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
Labels: 2. to review

#2403 Properly close Closable objects to avoid memleaks
  src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
  src/main/java/com/owncloud/android/jobs/ContactsImportJob.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/providers/DiskLruImageCacheFileProvider.java
  src/main/java/com/owncloud/android/ui/asynctasks/LoadingVersionNumberTask.java
  src/main/java/com/owncloud/android/ui/preview/ImageViewCustom.java
Labels: 2. to review

#2429 Update to Android Studio 3.1 tooling including build fixes
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  scripts/lint/lint-results.txt
  src/debug/AndroidManifest.xml
  src/main/java/com/owncloud/android/media/MediaService.java
  src/main/java/com/owncloud/android/widgets/ActionEditText.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
  src/main/res/layout/edit_box_dialog.xml
  src/main/res/layout/passcodelock.xml
  src/main/res/layout/password_dialog.xml
  src/main/res/layout/upload_file_dialog.xml
  src/main/res/values-v19/styles.xml
  src/main/res/values/oauth2_configuration.xml
  src/main/res/values/strings.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#2451 Backport "Fix #1260"
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
Labels: 2. to review

#2453 Backport #2450: Fix local file/folder browsingfix local file/folder browsing
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
Labels: 2. to review

#2452 Backport #2449: prevent NPE via null check
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 2. to review

#2456 update transifex
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-bg-rBG/strings.xml
  src/main/res/values-de-rDE/strings.xml
  src/main/res/values-el/strings.xml
  src/main/res/values-es-rMX/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fi-rFI/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-hu-rHU/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-nb-rNO/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sk-rSK/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-sv/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2450 Fix local file/folder browsing
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
Labels: 2. to review

#2448 Added a splash screen
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/res/drawable/launch_screen.xml
  src/main/res/values/styles.xml
Labels: 2. to review, design

#2432 Better understandable FAB actions via bottom sheet implementation
  build.gradle
  scripts/lint/lint-results.txt
  src/main/java/com/owncloud/android/db/PreferenceManager.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetActions.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/drawable/ic_plus.xml
  src/main/res/layout/account_action.xml
  src/main/res/layout/file_details_fragment.xml
  src/main/res/layout/file_details_share_user_item.xml
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
  src/main/res/layout/list_fragment.xml
  src/main/res/layout/preview_image_error_fragment.xml
  src/main/res/layout/send_button.xml
  src/main/res/layout/send_share_fragment.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 2. to review, design

#2482 Use unicode elipsis instead of html one -> desired behaviour on transifex
  src/main/res/values/strings.xml
Labels: 2. to review

#2353 Show correct error message if virus is detected
  .drone.yml
  src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  src/main/java/com/owncloud/android/db/UploadResult.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/res/values/strings.xml
Labels: 2. to review

#2489 Tint no upload icon grey
  drawable_resources/ic_list_empty_upload.svg
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/res/drawable-hdpi/ic_list_empty_upload.png
  src/main/res/drawable-mdpi/ic_list_empty_upload.png
  src/main/res/drawable-xhdpi/ic_list_empty_upload.png
  src/main/res/drawable-xxhdpi/ic_list_empty_upload.png
  src/main/res/drawable-xxxhdpi/ic_list_empty_upload.png
  src/main/res/drawable/ic_list_empty_upload.xml
Labels: 2. to review

#2493 Show themeable cloud name instead of hardcoded nextcloud
  scripts/lint/lint-results.txt
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/res/drawable/fab_label_background.xml
  src/main/res/values-ar/strings.xml
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-b+es+419/strings.xml
  src/main/res/values-bg-rBG/strings.xml
  src/main/res/values-ca/strings.xml
  src/main/res/values-cs-rCZ/strings.xml
  src/main/res/values-da/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-el/strings.xml
  src/main/res/values-es-rAR/strings.xml
  src/main/res/values-es-rCL/strings.xml
  src/main/res/values-es-rCO/strings.xml
  src/main/res/values-es-rCR/strings.xml
  src/main/res/values-es-rDO/strings.xml
  src/main/res/values-es-rEC/strings.xml
  src/main/res/values-es-rGT/strings.xml
  src/main/res/values-es-rHN/strings.xml
  src/main/res/values-es-rMX/strings.xml
  src/main/res/values-es-rNI/strings.xml
  src/main/res/values-es-rPA/strings.xml
  src/main/res/values-es-rPE/strings.xml
  src/main/res/values-es-rPR/strings.xml
  src/main/res/values-es-rPY/strings.xml
  src/main/res/values-es-rSV/strings.xml
  src/main/res/values-es-rUY/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-et-rEE/strings.xml
  src/main/res/values-eu/strings.xml
  src/main/res/values-fi-rFI/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-hu-rHU/strings.xml
  src/main/res/values-id/strings.xml
  src/main/res/values-is/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-ja-rJP/strings.xml
  src/main/res/values-ka-rGE/strings.xml
  src/main/res/values-ko/strings.xml
  src/main/res/values-lt-rLT/strings.xml
  src/main/res/values-nb-rNO/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-pt-rPT/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sk-rSK/strings.xml
  src/main/res/values-sl/strings.xml
  src/main/res/values-sq/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-sv/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values-zh-rCN/strings.xml
  src/main/res/values-zh-rTW/strings.xml
  src/main/res/values/attrs.xml
  src/main/res/values/colors.xml
  src/main/res/values/strings.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#2413 renames apk to include versionCode
  build.gradle
Labels: 2. to review

#2434 Disable TypographyEllipsis lint check
  lint.xml
Labels: 2. to review

#2479 fix failing notification on >= 8
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#2449 prevent NPE via null check
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 2. to review

#2488 ContactBackup: use always account of calling activity
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
Labels: 2. to review

#2487 Correct theming for contacts backup fragment: actionbar, buttons
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
Labels: 2. to review

#2426 Prevent IllegalArgumentException on generating preview
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Labels: 2. to review

#2394 Any theming call has now context, instead of app context
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/media/MediaControlView.java
  src/main/java/com/owncloud/android/media/MediaService.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  src/main/java/com/owncloud/android/ui/ThemeableSwitchPreference.java
  src/main/java/com/owncloud/android/ui/activity/ActivitiesListActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FingerprintActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/LogHistoryActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ParticipateActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploaderAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/IndeterminateProgressDialog.java
  src/main/java/com/owncloud/android/ui/dialog/LoadingDialog.java
  src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SortingOrderDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/EditShareFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/java/com/owncloud/android/ui/notifications/NotificationUtils.java
  src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  src/main/java/com/owncloud/android/ui/whatsnew/ProgressIndicator.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/values/strings.xml
Labels: 2. to review

#2503 adapter: Pass valid context to setImageDrawable()-call.
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
Labels: 2. to review

#2445 Enhance what's new screen
  src/main/res/layout/whats_new_activity.xml
  src/main/res/layout/whats_new_element.xml
Labels: 2. to review, design

#2511 added more information on initial connection error
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/res/values/strings.xml
Labels: 2. to review

#2512 Preferences: Don't start FileDisplayActivity when pressing the back button
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
Labels: 2. to review

#2509 fix more lint issues
  drawable_resources/account_circle_white.svg
  scripts/lint/lint-results.txt
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/res/drawable-hdpi/badge_favorite.png
  src/main/res/drawable-hdpi/ic_account_circle.png
  src/main/res/drawable-hdpi/ic_account_circle_white_18dp.png
  src/main/res/drawable-mdpi/badge_favorite.png
  src/main/res/drawable-mdpi/ic_account_circle_white_18dp.png
  src/main/res/drawable-xhdpi/badge_favorite.png
  src/main/res/drawable-xhdpi/ic_account_circle.png
  src/main/res/drawable-xhdpi/ic_account_circle_white_18dp.png
  src/main/res/drawable-xxhdpi/badge_favorite.png
  src/main/res/drawable-xxhdpi/ic_account_circle.png
  src/main/res/drawable-xxhdpi/ic_account_circle_white_18dp.png
  src/main/res/drawable-xxxhdpi/badge_favorite.png
  src/main/res/drawable-xxxhdpi/ic_account_circle_white_18dp.png
  src/main/res/drawable/account_circle_white.xml
  src/main/res/layout/account_item.xml
  src/main/res/layout/drawer_header.xml
  src/main/res/layout/file_details_empty.xml
  src/main/res/layout/files.xml
  src/main/res/layout/grid_image.xml
  src/main/res/layout/grid_item.xml
  src/main/res/layout/list_fragment_expandable.xml
  src/main/res/layout/list_item.xml
  src/main/res/layout/media_control.xml
  src/main/res/layout/synced_folders_item_header.xml
  src/main/res/layout/toolbar_user_information.xml
  src/main/res/layout/upload_list_item.xml
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-hu-rHU/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values/strings.xml
Labels: 2. to review
