Repository nextcloud/android, pull requests merged in 2018-05, with the labels that each got.

#2537 PassCodeManager cleanup
  src/main/java/com/owncloud/android/authentication/PassCodeManager.java
Labels: 2. to review

#2525 Remove buildToolsVersion
  build.gradle
Labels: 2. to review

#2541 authentication: Added @Override annotations to applicable methods.
  src/main/java/com/owncloud/android/authentication/AccountAuthenticatorActivity.java
Labels: 2. to review

#2540 activities: A couple of code quality fixes for the Activities component
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activities/data/Injection.java
Labels: 2. to review

#2546 ui: Corrected '&' to '&&' in boolean if statement.
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
Labels: 2. to review

#2547 Anonymous inner classes containing only one method should become lambdas
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  src/main/java/com/owncloud/android/authentication/SsoWebViewClient.java
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
Labels: 2. to review

#2545 ortiz.touch: End switch case with an unconditional break.
  src/main/java/com/ortiz/touch/TouchImageView.java
Labels: 2. to review

#2533 Iteration 1 for File detail & new sharing
  build.gradle
  drawable_resources/ic_star.svg
  drawable_resources/ic_star_outline.svg
  drawable_resources/ic_tag.svg
  scripts/lint/lint-results.txt
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/adapter/FileDetailTabAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ShareUserListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/drawable/ic_star.xml
  src/main/res/drawable/ic_star_outline.xml
  src/main/res/drawable/ic_tag.xml
  src/main/res/layout/file_details_activities_fragment.xml
  src/main/res/layout/file_details_fragment.xml
  src/main/res/layout/file_details_share_user_item.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/layout/log_send_file.xml
  src/main/res/layout/share_user_item.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 2. to review, design, enhancement

#2565 authentication: Fixed HTTPS prefixed URL normalization.
  src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.java
Labels: 2. to review

#2564 MainApp: Fixed auto upload state check.
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#2566 Fix local sorting
  src/main/java/com/owncloud/android/utils/FileSortOrder.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
Labels: 2. to review

#2578 fix again a null context
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review

#2580 Cleanup of the TouchViewImage class
  src/main/java/com/ortiz/touch/TouchImageView.java
Labels: 2. to review

#2581 Mainapp cleanup
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#2590 Lib refers always to master
  build.gradle
Labels: 2. to review

#2591 Ignore "unused quantity"
  lint.xml
Labels: 2. to review

#2593 Replaced legacy custom ImageView and ViewPager class with PhotoView and stock ViewPager
  build.gradle
  scripts/lint/lint-results.txt
  src/main/java/com/ortiz/touch/ExtendedViewPager.java
  src/main/java/com/ortiz/touch/TouchImageView.java
  src/main/java/com/owncloud/android/ui/preview/ImageViewCustom.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  src/main/java/third_parties/michaelOrtiz/TouchImageViewCustom.java
  src/main/res/layout/preview_image_activity.xml
  src/main/res/layout/preview_image_fragment.xml
Labels: 2. to review

#2519 Add ripple effect
  src/main/java/com/owncloud/android/ui/adapter/ShareUserListAdapter.java
  src/main/res/layout/grid_image.xml
  src/main/res/layout/list_item.xml
Labels: 2. to review

#2602 ui:preview Simplified generateCheckerboardLayeredDrawable()
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Labels: 2. to review

#2600 Minor cleanup of the PreviewImageFragment
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Labels: 2. to review

#2599 res:styles: Don't use a translucent navigation bar in the Preview activity
  src/main/res/values-v19/styles.xml
Labels: 2. to review, needs info/discussion

#2544 Brander with white primary color
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/res/layout/account_setup.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#2520 Do not sort on getFolderContent
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
Labels: 2. to review

#2501 Use userId for webdav search
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2490 Fix double search
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2312 Add support for integration tests
  .codecov.yml
  .drone.yml
  build.gradle
  scripts/lint/lint-results.txt
  scripts/uploadReport.sh
  src/androidTest/disabledTests/screenshots/ScreenshotsIT.java
  src/androidTest/disabledTests/uiautomator/InitialTest.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/FileIT.java
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/androidTest/java/com/owncloud/android/authentication/AuthenticatorActivityTest.java
  src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java
  src/test/java/com/owncloud/android/utils/ErrorMessageAdapterUnitTest.java
  wait_for_emulator.sh
Labels: 2. to review

#2616 Remove analytics
  CONTRIBUTING.md
  SETUP.md
  build.gradle
  scripts/lint/lint-results.txt
  src/generic/java/com/owncloud/android/utils/AnalyticsUtils.java
  src/gplay/AndroidManifest.xml
  src/gplay/java/com/owncloud/android/utils/AnalyticsUtils.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FingerprintActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/GenericExplanationActivity.java
  src/main/java/com/owncloud/android/ui/activity/LogHistoryActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ParticipateActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadPathActivity.java
  src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  src/main/java/com/owncloud/android/ui/fragment/EditShareFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/SearchShareesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  src/main/res/values/setup.xml
  src/versionDev/java/com/owncloud/android/utils/AnalyticsUtils.java
Labels: 2. to review

#2613 setting the menu item order according to the webUI
  src/main/java/com/owncloud/android/authentication/AccountUtils.java
  src/main/res/menu/file_actions_menu.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#2623 Cleanup unused code, housekeeping post #2616
  src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FingerprintActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/GenericExplanationActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ParticipateActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadPathActivity.java
  src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
Labels: 2. to review

#2619 ui:activity Removed unused override method in ManageAccountsActivity
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
Labels: 2. to review

#2621 ui:activity: Removed @NonNull annotation for method where null can be returned
  src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
Labels: 2. to review

#2622 ui:preview Verify that bitmap is not null before setting imageDrawable.
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Labels: 2. to review

#2573 Iteration 2 for file detail & new sharing
  drawable_resources/alert-octagon.svg
  scripts/lint/lint-results.txt
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/operations/UnshareOperation.java
  src/main/java/com/owncloud/android/operations/UpdateSharePermissionsOperation.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/TextDrawable.java
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/FileDetailTabAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ShareUserListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/decoration/SimpleListItemDividerDecoration.java
  src/main/java/com/owncloud/android/ui/dialog/ExpirationDatePickerDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java
  src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/drawable/divider.xml
  src/main/res/drawable/ic_alert_octagon.xml
  src/main/res/layout/file_details_empty.xml
  src/main/res/layout/file_details_fragment.xml
  src/main/res/layout/file_details_share_user_item.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/layout/share_file_layout.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/menu/file_detail_sharing_link_menu.xml
  src/main/res/menu/file_detail_sharing_menu.xml
  src/main/res/menu/file_details_actions_menu.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
  src/main/res/values/styles.xml
Labels: 2. to review, design, enhancement

#2633 restore prematurely deleted strings
  src/main/res/values/strings.xml
Labels: 2. to review, high

#2635 Create stable 3.2.x branch
  .codecov.yml
  .drone.yml
  scripts/lint/getBranchName.sh
Labels: 2. to review

#2634 3.2.0 RC1 + updated changelog
  .codecov.yml
  CHANGELOG.md
  build.gradle
  scripts/lint/lint-results.txt
Labels: 2. to review

#2636 Backport transifex to 3.2.x
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-cs-rCZ/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-es-rMX/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-is/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-sq/strings.xml
  src/main/res/values-tr/strings.xml
Labels: 2. to review

#2647 Fix search events
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#2650 Explicitly allow gcm on gplay
  src/gplay/AndroidManifest.xml
Labels: 2. to review, backport-request

#2652 Backport: As we use singleTop, we shall not start a new activity
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2653 Backport: do not process result of async task if activity is stopped
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesContract.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesPresenter.java
Labels: 2. to review

#2654 Backport: store file/account when suspending fragments
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 2. to review

#2655 Backport: explicitly finish preferences
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
Labels: 2. to review

#2656 Backport: explicitly allow gcm on gplay
  src/gplay/AndroidManifest.xml
Labels: 2. to review

#2659 Backport transifex
  src/main/res/values-es-rMX/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-nb-rNO/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sq/strings.xml
  src/main/res/values-sr/strings.xml
Labels: 2. to review

#2660 Bump to 3.2.0-rc2
  build.gradle
Labels: 2. to review

#2662 Backport: reword empty activity
  src/main/res/values/strings.xml
Labels: 2. to review
