Repository nextcloud/android, pull requests merged in 2018-09, with the labels that each got.

#2940 make restore icon grey600
  drawable_resources/ic_history.svg
  src/main/res/drawable/ic_history.xml
Labels: 2. to review

#2956 bump to 3.2.4
  CHANGELOG.md
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30020399.txt
  fastlane/metadata/android/en-US/changelogs/30020499.txt
Labels: 2. to review

#2958 Fix Timsort (again)
  src/main/java/third_parties/daveKoeller/AlphanumComparator.java
  src/test/java/com/owncloud/android/utils/TestSorting.java
Labels: 2. to review

#2944 remove dividers
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  src/main/res/layout/account_action.xml
  src/main/res/layout/account_item.xml
  src/main/res/layout/accounts_layout.xml
  src/main/res/layout/activity_list_item.xml
  src/main/res/layout/list_item.xml
  src/main/res/layout/notification_list_item.xml
  src/main/res/layout/toolbar_user_information.xml
  src/main/res/layout/trashbin_item.xml
  src/main/res/layout/user_info_details_table_item.xml
  src/main/res/values/dims.xml
Labels: 2. to review

#2935 Improve share link handling
  CHANGELOG.md
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/utils/ClipboardUtil.java
Labels: 2. to review, enhancement

#1116 Proof of concept for Single Sign On
  scripts/analysis/lint-results.txt
  src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  src/main/AndroidManifest.xml
  src/main/aidl/com/nextcloud/android/sso/aidl/IInputStreamService.aidl
  src/main/java/com/nextcloud/android/sso/Constants.java
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/nextcloud/android/sso/aidl/IThreadListener.java
  src/main/java/com/nextcloud/android/sso/aidl/NextcloudRequest.java
  src/main/java/com/nextcloud/android/sso/aidl/ParcelFileDescriptorUtil.java
  src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  src/main/java/com/owncloud/android/services/AccountManagerService.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review

#2960 Add links to summary
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#2936 3.3.0RC1
  .codecov.yml
  .drone.yml
  CHANGELOG.md
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30020499.txt
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#2962 3.4.0 alpha 1
  build.gradle
Labels: 2. to review

#2969 Do not block on check for dev version
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/Preferences.java
  src/main/java/com/owncloud/android/ui/asynctasks/LoadingVersionNumberTask.java
Labels: 2. to review

#2974 Nullable check on exit mode
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#2976 [3.3.0] Nullable check on exit mode
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#2967 Remove gcm as we use firebase messaging
  gplay.gradle
Labels: 2. to review

#2971 Library upgrades
  build.gradle
Labels: 2. to review

#2984 Backport #2982: add provider Exception
  src/main/java/com/owncloud/android/utils/DeviceCredentialUtils.java
Labels: 2. to review

#2986 Bump to 3.3.0 RC2
  build.gradle
Labels: 3. to release

#2985 Backport #2980: prevent NPE on media stream
  src/main/java/com/owncloud/android/media/MediaService.java
  src/main/java/com/owncloud/android/media/MediaServiceBinder.java
Labels: 2. to review

#2982 Add provider Exception
  src/main/java/com/owncloud/android/utils/DeviceCredentialUtils.java
Labels: 2. to review

#2980 Prevent NPE on media stream
  src/main/java/com/owncloud/android/media/MediaService.java
  src/main/java/com/owncloud/android/media/MediaServiceBinder.java
Labels: 2. to review

#3007 "dependencies" label do not need a pull approve
  .pullapprove.yml
Labels: 2. to review

#3006 Remove Firebase-core from the build
  build.gradle
Labels: 2. to review

#3009 Fix npe on version checking
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#3017 Backport npe server version check
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/res/values-el/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pl/strings.xml
  src/main/res/values-ru/strings.xml
Labels: 2. to review

#3018 Fix Avatar fetching for Nc14 server
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review, backport-request

#3008 Use grid_item view for gridview in upload filepicker
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
Labels: 2. to review

#3024 Backport #3018: Server sends a HTTP-201 (not 200) for a newly created avatar on Nc14
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review

#3013 Store mnemonic as typed in
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
Labels: 2. to review

#3025 Tint drawable according to login color
  src/main/java/com/owncloud/android/ui/fragment/FeatureFragment.java
Labels: 2. to review, backport-request

#3028 Delete proguard
  proguard.cfg
Labels: 2. to review

#3010 Codacy
  src/generic/java/com/owncloud/android/utils/PushUtils.java
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.java
  src/main/java/com/owncloud/android/authentication/PassCodeManager.java
  src/main/java/com/owncloud/android/datamodel/ArbitraryDataProvider.java
  src/main/java/com/owncloud/android/datamodel/DecryptedFolderMetadata.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  src/main/java/com/owncloud/android/datastorage/providers/AbstractCommandLineStoragePoint.java
  src/main/java/com/owncloud/android/datastorage/providers/AbstractStoragePointProvider.java
  src/main/java/com/owncloud/android/datastorage/providers/EnvironmentStoragePointProvider.java
  src/main/java/com/owncloud/android/datastorage/providers/IStoragePointProvider.java
  src/main/java/com/owncloud/android/datastorage/providers/MountCommandStoragePointProvider.java
  src/main/java/com/owncloud/android/datastorage/providers/VDCStoragePointProvider.java
  src/main/java/com/owncloud/android/db/PreferenceManager.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/operations/OAuth2GetAccessToken.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/UnshareOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApiImpl.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/StorageMigration.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityAndVersionListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/util/FileDetailSharingFragmentHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/utils/ClipboardUtil.java
  src/main/java/com/owncloud/android/utils/ConnectivityUtils.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/main/java/com/owncloud/android/utils/svg/SvgDecoder.java
  src/versionDev/java/com/owncloud/android/utils/PushUtils.java
Labels: 2. to review

#3033 Quickfix for unknown SharingTypes
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 2. to review, backport-request

#3030 backport: Tint drawable according to login color #3025
  src/main/java/com/owncloud/android/ui/fragment/FeatureFragment.java
Labels: 2. to review

#3037 Fix account switching: After adding an account, the app restart and uses the new account
  src/main/java/com/owncloud/android/ui/activity/FirstRunActivity.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#3039 backport: Fix account switching: After adding an account, the app restart and uses the new account #3037
  src/main/java/com/owncloud/android/ui/activity/FirstRunActivity.java
  src/main/res/values/strings.xml
Labels: 2. to review

#3027 add own sso token manager with custom dialog
  build.gradle
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/android/sso/Constants.java
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
  src/main/res/layout/activity_sso_grant_permission.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#3043 3.3.0 RC3
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30030052.txt
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-cs-rCZ/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-el/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fi-rFI/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-iw/strings.xml
  src/main/res/values-nb-rNO/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-ru/strings.xml
  src/main/res/values-sl/strings.xml
  src/main/res/values-sq/strings.xml
  src/main/res/values-sr/strings.xml
  src/main/res/values-tr/strings.xml
Labels: 2. to review

#3042 Backport 3027: add own sso token manager with custom dialog
  build.gradle
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/android/sso/Constants.java
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
  src/main/res/layout/activity_sso_grant_permission.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#3031 Fix upload filepicker footer view
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
Labels: 2. to review

#3044 Correct handle write protected folders
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#3050 Fix CanvasTooLargeException
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 2. to review

#3048 Bump drone version
  .drone.yml
Labels: 2. to review

#3055 change RC starting with 51
  build.gradle
Labels: 2. to review

#3056 Stable 3.3.0
  CHANGELOG.md
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30030099.txt
  src/generic/fastlane/metadata/android/bg-BG/short_description.txt
  src/generic/fastlane/metadata/android/bg-BG/title.txt
  src/generic/fastlane/metadata/android/vi-VI/short_description.txt
  src/generic/fastlane/metadata/android/vi-VI/title.txt
  src/main/res/values-b+en+001/strings.xml
  src/main/res/values-bg-rBG/strings.xml
  src/main/res/values-cs-rCZ/strings.xml
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values-ja-rJP/strings.xml
  src/main/res/values-nl/strings.xml
  src/main/res/values-pt-rBR/strings.xml
  src/main/res/values-tr/strings.xml
  src/main/res/values-vi/strings.xml
Labels: 2. to review

#3057 Changelog 3.3.0
  CHANGELOG.md
Labels: 2. to review

#3052 Codacy fixes
  src/gplay/java/com/owncloud/android/utils/GooglePlayUtils.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/datamodel/FileSystemDataSet.java
  src/main/java/com/owncloud/android/datamodel/MediaProvider.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/operations/GetServerInfoOperation.java
  src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  src/main/java/com/owncloud/android/ui/EmptyRecyclerView.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/components/CustomEditText.java
  src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review

#3066 Backport #3033: quickfix for unknown SharingTypes
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 2. to review

#3069 Show local size when switching to "on device" view
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review

#3081 Bump supportLibraryVersion from 27.1.1 to 28.0.0
  build.gradle
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/FileIT.java
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review

#3051 Add room share type
  build.gradle
  drawable_resources/chat_bubble.svg
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/ui/adapter/ShareUserListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/res/drawable/ic_chat_bubble.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#3070 Codacy fixes
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/MediaProvider.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/datastorage/providers/MountCommandStoragePointProvider.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/jobs/ContactsImportJob.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/StorageMigration.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/LoadingDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SslValidatorDialog.java
  src/main/java/com/owncloud/android/ui/fragment/EditShareFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/FileSortOrder.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review

#3086 Remember last path which was used on local file selection
  src/main/java/com/owncloud/android/db/PreferenceManager.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 2. to review, enhancement

#3090 charAt is throwing out of bounds, if empty string
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/datastorage/providers/MountCommandStoragePointProvider.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#3065 Fix broken navigation
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review
