Repository nextcloud/android, pull requests merged in 2019-09, with the labels that each got.

#4444 fix endless scroll on file detail activity stream
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
Labels: 2. to review, backport-request

#4449 baseURL might be null
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/test/java/com/owncloud/android/utils/DisplayUtilsTest.java
Labels: 2. to review, backport-request

#4447 Prevent npe
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#4446 Feedback link is removed from setting ang participate is changed to c…
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/res/layout/participate_layout.xml
  src/main/res/values/strings.xml
  src/main/res/xml/preferences.xml
Labels: 2. to review, design

#4434 Update MimeTypes
  drawable_resources/link.svg
  drawable_resources/location.svg
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/res/drawable/file_link.xml
  src/main/res/drawable/file_location.xml
Labels: 2. to review, backport-request

#4455 Remote wipe
  .idea/codeStyles/Project.xml
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/asynctasks/CheckRemoteWipeTask.java
Labels: 2. to review, backport-request

#4458 rename participate -> community
  drawable_resources/nav_community.svg
  drawable_resources/nav_participate.svg
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/res/drawable/nav_community.xml
  src/main/res/layout/community_layout.xml
  src/main/res/menu/drawer_menu.xml
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#4459 3.8.0 RC4
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080054.txt
Labels: 2. to review

#4461 do not use literals in conditional statements
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 2. to review

#4475 Enhance photo search task
  src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java
  src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java
Labels: 2. to review, backport-request

#4482 (temporary) fix for navigation issue
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java
Labels: 2. to review, backport-request

#4489 Bump to 3.8.0 RC5
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080055.txt
Labels: 2. to review

#4497 Bump to 3.8.0 final
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080090.txt
Labels: 2. to review

#4498 Changelog v3.8.0
  CHANGELOG.md
Labels: 2. to review

#4528 use Nextcloud UA
  src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
  src/main/java/com/nextcloud/client/network/PlainHttpClient.java
Labels: 2. to review, backport-request

#4539 Fix NPE crash in OCFileListFragment when action mode is destroyed
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#4545 Fix for NPE caused by Log.d in ThumbnailsCacheManager
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review, backport-request

#4538 Fix registration of second account on first run
  src/main/java/com/nextcloud/client/onboarding/OnboardingServiceImpl.kt
  src/test/java/com/nextcloud/client/onboarding/OnboardingServiceTest.kt
Labels: 2. to review, backport-request
