Repository nextcloud/android, pull requests merged in 2019-06, with the labels that each got.

#4111 Fix crash caused UserAccountManager dependency not being injected
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
Labels: 2. to review

#4106 Richdocuments: grab focus on resume
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsWebView.java
Labels: 2. to review

#4113 Second fragment might be null
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#4042 Move first run and whats new to onboarding package
  build.gradle
  detekt.yml
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/ui/activity/FileDisplayActivityTest.java
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/nextcloud/client/di/AppComponent.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  src/main/java/com/nextcloud/client/onboarding/OnboardingModule.kt
  src/main/java/com/nextcloud/client/onboarding/OnboardingService.kt
  src/main/java/com/nextcloud/client/onboarding/OnboardingServiceImpl.kt
  src/main/java/com/nextcloud/client/onboarding/WhatsNewActivity.java
  src/main/java/com/nextcloud/client/whatsnew/WhatsNewService.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
Labels: 2. to review

#4115 Simplify check
  build.gradle
Labels: 2. to review

#4085 Copy internal link
  drawable_resources/external.svg
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/res/drawable/ic_external.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/values/colors.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#4086 Migrate PowerUtils calls to PowerManagementService
  build.gradle
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/jobs/NContentObserverJob.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  src/main/java/com/owncloud/android/utils/PowerUtils.java
  src/main/java/com/owncloud/android/utils/ReceiversHelper.java
  src/test/java/com/owncloud/android/utils/PowerUtilsTest.java
Labels: 2. to review

#4116 Bump to 3.7.0 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30070051.txt
Labels: 2. to review

#4122 use own getAccounts() instead of AccountManager from AndroidSDK
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
Labels: 2. to review, backport-request

#4125 Do not show QR scan if Chromebook without camera
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review, backport-request

#4128 Bump to latest android docker
  .drone.yml
Labels: 2. to review

#4134 Prevent NPE if extras is null
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review, backport-request

#4138 show build number, if set
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#4139 Fix dismiss notification
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
Labels: 2. to review, backport-request

#4141 Fix crash on sharing file to NC with multiple accounts
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
Labels: 2. to review, backport-request

#4136 hide outdated version warning if extended support is enabled
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/operations/GetServerInfoOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review, backport-request

#4137 Use new convention "xyRemoteOperation"
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.java
  src/main/java/com/owncloud/android/operations/CreateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/operations/GetCapabilitiesOperation.java
  src/main/java/com/owncloud/android/operations/GetServerInfoOperation.java
  src/main/java/com/owncloud/android/operations/GetSharesForFileOperation.java
  src/main/java/com/owncloud/android/operations/GetUserProfileOperation.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/UnshareOperation.java
  src/main/java/com/owncloud/android/operations/UpdateNoteForShareOperation.java
  src/main/java/com/owncloud/android/operations/UpdateSharePermissionsOperation.java
  src/main/java/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#4145 Allow "save as" and "print" to be downloaded from Collabora
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsWebView.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#4156 Fix crash when displaying video files
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: backport-request

#4114 get rename message from RichDocuments
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsWebView.java
Labels: 2. to review, backport-request

#4174 Backport #4145
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsWebView.java
  src/main/res/values/strings.xml
Labels: 2. to review

#4178 fix parcelable with using kapt
  build.gradle
Labels: 2. to review, backport-request

#4175 Backport of #4114
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsWebView.java
  src/main/res/values/strings.xml
Labels: 2. to review

#4171 Remove DI from NContentObserverJob
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/jobs/NContentObserverJob.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review, backport-request

#4185 use index.php to create asset in Collabora
  src/main/java/com/owncloud/android/operations/RichDocumentsCreateAssetOperation.java
Labels: 2. to review, backport-request

#4188 Bump to 3.7.0 RC4
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30070054.txt
Labels: 2. to review

#4179 fix wrong tinted button on upload file within collabora
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/layout/files_picker.xml
Labels: 2. to review, backport-request
