Repository nextcloud/android, pull requests merged in 2019-07, with the labels that each got.

#4191 npe in file owner after upgrade
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review, backport-request

#4193 Better way to colorize text
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review, backport-request

#4186 Backport #4171
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/jobs/NContentObserverJob.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#4117 Remove legacy AccountUtils
  scripts/uploadReport.sh
  src/androidTest/java/com/nextcloud/client/account/UserAccountManagerImplTest.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/nextcloud/client/di/AppComponent.java
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/nextcloud/client/preferences/PreferencesModule.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AccountUtils.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/db/OCUpload.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApiImpl.java
  src/main/java/com/owncloud/android/ui/activities/data/files/FilesServiceApiImpl.java
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/test/java/com/nextcloud/client/preferences/TestPreferenceManager.java
Labels: 2. to review

#4198 use correct file for message while sharing via link
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
Labels: 2. to review

#4196 Codacy
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/di/InjectorNotFoundException.java
  src/main/java/com/owncloud/android/datastorage/UniqueStorageList.java
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/operations/RemoteOperationFailedException.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/StorageMigration.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
Labels: 2. to review

#4210 Bump to 3.7.0
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30070090.txt
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#4211 Use sameMajorVersion of OwnCloudVersion
  build.gradle
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#4217 fix GSS on android
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review, backport-request

#4225 Update changelog to 3.7.0
  CHANGELOG.md
Labels: 2. to review

#4226 Run drone only if source file changed
  .drone.yml
  scripts/checkIfRunDrone.sh
Labels: 2. to review

#4237 Remove last usage of SSO/Saml
  src/main/java/com/owncloud/android/services/OperationsService.java
Labels: 2. to review

#4238 Remove old and unmaintained bottom bar
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/main/res/layout/activity_list_layout.xml
  src/main/res/layout/contacts_preference.xml
  src/main/res/layout/list_fragment.xml
  src/main/res/layout/notifications_layout.xml
  src/main/res/layout/synced_folders_layout.xml
  src/main/res/layout/trashbin_activity.xml
  src/main/res/layout/upload_list_layout.xml
  src/main/res/values/setup.xml
Labels: 2. to review

#4242 new approach for tinted cursors
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#4250 fix check if source code was modified
  .drone.yml
  scripts/checkIfRunDrone.sh
Labels: 2. to review

#4249 show "shared" again
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 1. developing

#4253 Master: get lint/warnings down
  .idea/codeStyles/Project.xml
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java
  src/main/java/com/nextcloud/client/onboarding/OnboardingServiceImpl.kt
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/drawable/settings.xml
  src/main/res/menu/navigation_bar_menu.xml
  src/main/res/values/strings.xml
  src/test/java/com/nextcloud/client/device/TestPowerManagementService.kt
Labels: 2. to review

#4254 Reset host when using login via QR/link
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#4258 check if drone should run: also when build.gradle changed
  scripts/checkIfRunDrone.sh
Labels: 2. to review

#4261 merge commit should always run drone
  scripts/checkIfRunDrone.sh
Labels: 2. to review

#4263 remove document (with relation to parent)
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#4269 combined dagger bump
  build.gradle
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review, dependencies

#4270 mHostUrlInput can be null if used with direct login
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#4133 Engineering Test Mode
  build.gradle
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/AppComponent.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/di/ViewModelFactory.kt
  src/main/java/com/nextcloud/client/di/ViewModelKey.kt
  src/main/java/com/nextcloud/client/di/ViewModelModule.kt
  src/main/java/com/nextcloud/client/etm/EtmActivity.kt
  src/main/java/com/nextcloud/client/etm/EtmBaseFragment.kt
  src/main/java/com/nextcloud/client/etm/EtmMenuAdapter.kt
  src/main/java/com/nextcloud/client/etm/EtmMenuEntry.kt
  src/main/java/com/nextcloud/client/etm/EtmMenuFragment.kt
  src/main/java/com/nextcloud/client/etm/EtmViewModel.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmPreferencesFragment.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/res/layout/activity_etm.xml
  src/main/res/layout/fragment_etm_menu.xml
  src/main/res/layout/fragment_etm_preferences.xml
  src/main/res/layout/material_list_item_single_line.xml
  src/main/res/menu/etm_preferences.xml
  src/main/res/values/strings.xml
  src/main/res/values/styles.xml
  src/main/res/xml/preferences.xml
  src/test/java/com/nextcloud/client/etm/TestEtmViewModel.kt
Labels: 2. to review

#4276 Check status on transfer update
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#4283 Release 3.7.1
  CHANGELOG.md
Labels: 2. to review
