Repository nextcloud/android, pull requests merged in 2019-04, with the labels that each got.

#3818 datamodel: use equals for string comparison.
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 2. to review

#3820 Check result also for 202 (accepted)
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
Labels: 2. to review, backport-request

#3813 Add SpotBugs tasks
  build.gradle
Labels: 2. to review

#3821 NPE check on note
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 2. to review, backport-request

#3824 Use spotbugs for analytics
  build.gradle
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/findbugs-results.txt
  scripts/analysis/findbugs-up.rb
Labels: 1. developing

#3828 3.6.0 RC3
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30060053.txt
Labels: 2. to review

#3791 Inject AppPreferences into activities and fragments
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/di/Injectable.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FirstRunActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
Labels: 2. to review

#3829 bump master to 3.7.0-alpha1
  build.gradle
Labels: 2. to review

#3838 bump dagger to 2.22.1
  build.gradle
Labels: 2. to review, dependencies

#3850 removed unused imports.
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/ui/activity/FirstRunActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/activity/WhatsNewActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
Labels: 2. to review

#3853 fix drone.yml for drone 1.0
  .drone.yml
Labels: 2. to review

#3839 Minor refactor of StringUtils class. Added unit tests.
  src/main/java/com/owncloud/android/utils/StringUtils.java
  src/test/java/com/owncloud/android/utils/StringUtilsTest.java
Labels: 2. to review

#3847 revert to old auth login method: do not use weblogin suffix
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review, backport-request

#3845 Thumbnail with correct mimetype
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review, backport-request

#3862 backport drone
  .drone.yml
Labels: 2. to review

#3863 Backport #3845: As we can have now any preview (if there is a preview generator), we …
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review

#3861 3.6.0 release
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30060090.txt
Labels: 2. to review

#3859 tests: added unit tests for the ConnectivityUtils util class.
  src/test/java/com/owncloud/android/utils/ConnectivityUtilsTest.java
Labels: 2. to review

#3868 Changelog release 3.6.0
  CHANGELOG.md
Labels: 2. to review, backport-request

#3858 show changelog in dev
  scripts/buildDev
Labels: 2. to review

#3867 Codacy improvements
  src/main/java/com/nextcloud/android/sso/Constants.java
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/owncloud/android/authentication/OAuth2Constants.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/datastorage/DataStorageProvider.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/helpers/UriUploader.java
  src/main/java/com/owncloud/android/utils/MimeType.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#3866 test: added unit tests for the PowerUtils class.
  src/test/java/com/owncloud/android/utils/PowerUtilsTest.java
Labels: 2. to review

#3841 Unit tests for the OwnCloudSession class.
  src/main/java/com/owncloud/android/utils/OwnCloudSession.java
  src/test/java/com/owncloud/android/utils/OwnCloudSessionTest.java
Labels: 2. to review, needs info/discussion

#3864 test: added PowerMocked unit tests for the ConnectivityUtils class.
  build.gradle
  src/test/java/com/owncloud/android/utils/ConnectivityUtilsTest.java
Labels: 2. to review

#3873 Further code improvements
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/media/MediaService.java
  src/main/java/com/owncloud/android/media/MediaServiceBinder.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  src/main/java/com/owncloud/android/operations/common/SyncOperation.java
  src/main/java/com/owncloud/android/syncadapter/AbstractOwnCloudSyncAdapter.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncService.java
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/LogHistoryActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 2. to review

#3879 PMD ruleset
  build.gradle
  ruleset.xml
Labels: 2. to review

#3882 Fix #3881 by checking for result being null
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#3890 Delete old tests
  tests/.classpath
  tests/.project
  tests/.settings/org.eclipse.jdt.core.prefs
  tests/AndroidManifest.xml
  tests/ant.properties
  tests/proguard-project.txt
  tests/project.properties
  tests/res/drawable-hdpi/ic_launcher.png
  tests/res/drawable-ldpi/ic_launcher.png
  tests/res/drawable-mdpi/ic_launcher.png
  tests/res/drawable-xhdpi/ic_launcher.png
  tests/res/values/strings.xml
  tests/src/com/owncloud/android/test/AccountUtilsTest.java
  tests/src/com/owncloud/android/test/FileContentProviderTest.java
Labels: 2. to review

#3871 Show current codacy issue count
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#3886 Rename PreferenceManager to AppPreferencesImpl
  src/generic/java/com/owncloud/android/utils/PushUtils.java
  src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseInstanceIDService.java
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/PassCodeManager.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/MediaFoldersDetectionJob.java
  src/main/java/com/owncloud/android/jobs/NContentObserverJob.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  src/test/java/com/nextcloud/client/preferences/TestPreferenceManager.java
  src/versionDev/java/com/owncloud/android/utils/PushUtils.java
Labels: 2. to review

#3895 Create UserAccountManager and move getAccounts()
  findbugs-filter.xml
  scripts/analysis/findbugs-results.txt
  src/generic/java/com/nextcloud/client/di/VariantComponentsModule.java
  src/generic/java/com/owncloud/android/utils/PushUtils.java
  src/gplay/java/com/nextcloud/client/di/VariantComponentsModule.java
  src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseInstanceIDService.java
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AccountUtils.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/MediaFoldersDetectionJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/ui/TextDrawable.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FirstRunActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListAdapter.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  src/main/java/com/owncloud/android/utils/ReceiversHelper.java
  src/versionDev/java/com/nextcloud/client/di/VariantComponentsModule.java
  src/versionDev/java/com/owncloud/android/utils/PushUtils.java
Labels: 1. developing

#3900 Show codacy count only on master
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#3889 Cleanup authentication
  .idea/codeStyles/Project.xml
  scripts/analysis/findbugs-results.txt
  src/gplay/AndroidManifest.xml
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.java
  src/main/java/com/owncloud/android/authentication/OAuth2Constants.java
  src/main/java/com/owncloud/android/authentication/SsoWebViewClient.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/operations/CommentFileOperation.java
  src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/OAuth2GetAccessToken.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/dialog/SamlWebViewDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
  src/main/res/layout/sso_dialog.xml
  src/main/res/values/oauth2_configuration.xml
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#3908 Missing Injectable lead to half-stored account
  src/gplay/java/com/nextcloud/client/di/VariantComponentsModule.java
  src/gplay/java/com/owncloud/android/authentication/ModifiedAuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#3899 cleanup unused code
  src/main/java/com/owncloud/android/utils/UriUtils.java
Labels: 2. to review

#3912 Setup.md: direct usage of library project
  SETUP.md
Labels: 2. to review

#3924 Warn for wrong library branch on master (for upcoming stable)
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#3923 Allow edit on link share on a file
  src/main/java/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/res/layout/file_details_sharing_fragment.xml
Labels: 2. to review

#3903 Update wording for store text
  src/main/res/values/strings.xml
Labels: 2. to review, design, enhancement
