Repository nextcloud/android, pull requests merged in 2019-08, with the labels that each got.

#4180 Improve app store screenshot designs
  fastlane/Fastfile
  fastlane/Screengrabfile
  scripts/screenshots/addMockDevice.sh
  scripts/screenshots/phone.png
  scripts/screenshots/phone.svg
  scripts/screenshots/sevenInch.svg
  scripts/screenshots/tablet.png
  src/androidTest/java/com/owncloud/android/ScreenshotsIT.java
  src/main/res/values/strings.xml
Labels: 1. developing, design, enhancement

#4287 Fix upload and delete to actually delete
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#4262 Fix local state if fragment is initialized before services
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review

#3857 About resolving #2953
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListItem.java
  src/main/res/layout/accounts_layout.xml
  src/test/java/com/owncloud/android/ui/activities/data/activities/RemoteActivitiesRepositoryTest.java
  src/test/java/com/owncloud/android/ui/adapter/AccountListAdapterTest.java
Labels: 2. to review

#4295 Enhanced doc
  CONTRIBUTING.md
Labels: 2. to review

#4296 Use emulator-headless
  .drone.yml
Labels: 2. to review

#4286 FIDO U2F Support
  build.gradle
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#4313 Use ExceptionHandler not on debug builds
  src/main/java/com/nextcloud/client/appinfo/AppInfo.java
  src/main/java/com/nextcloud/client/appinfo/AppInfoImpl.java
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#4322 Add license sample
  CONTRIBUTING.md
Labels: 2. to review

#4324 Extract strings to be translatable
  src/main/res/values/strings.xml
  src/main/res/xml/preferences.xml
Labels: 2. to review

#4321 clarify transifex usage
  CONTRIBUTING.md
Labels: 2. to review

#4332 Bump to 3.7.2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30070290.txt
Labels: 2. to review

#4300 Show groupFolder correctly
  drawable_resources/folder-group.svg
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/res/drawable/ic_folder_group.xml
Labels: 2. to review

#4327 append phoneInfo on email
  src/main/java/com/nextcloud/client/logger/LegacyLoggerAdapter.kt
  src/main/java/com/nextcloud/client/logger/ui/LogsEmailSender.kt
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#4326 Centralize theming of search bar
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/logger/ui/LogsActivity.kt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#4336 Handle thread interruption when enqueueing log message
  src/main/java/com/nextcloud/client/logger/LoggerImpl.kt
  src/test/java/com/nextcloud/client/logger/LoggerTest.kt
Labels: 2. to review

#4346 use new Android docker image
  .drone.yml
Labels: 2. to review

#4348 hide user account from upload view items for single account setups
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
Labels: 2. to review

#4347 hardcode ignore ".thumbnail"
  src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
Labels: 2. to review

#4349 Delete temp file on receive external files
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 2. to review

#2250 Use reloading on photo view
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/ui/EmptyRecyclerView.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java
  src/main/java/com/owncloud/android/ui/interfaces/OCFileListFragmentInterface.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/main/res/layout/list_footer.xml
Labels: 2. to review

#4245 Fix upload list comparator to make it respect the comparator contract
  src/main/java/com/owncloud/android/db/OCUpload.java
  src/main/java/com/owncloud/android/db/OCUploadComparator.kt
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/test/java/com/owncloud/android/ui/db/OCUploadComparatorTest.kt
Labels: 2. to review

#4189 Provide a banal 'paste' postmessage implementation.
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsWebView.java
Labels: 2. to review

#4314 Use conscrypt
  build.gradle
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#3589 Check if app is excluded from battery optimization
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/device/DeviceModule.kt
  src/main/java/com/nextcloud/client/device/PowerManagementServiceImpl.kt
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/res/menu/synced_folders_menu.xml
  src/main/res/values/strings.xml
  src/test/java/com/nextcloud/client/device/TestPowerManagementService.kt
Labels: 2. to review

#4345 Push: no need to use ocClient
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
Labels: 2. to review

#4356 revert to old image
  .drone.yml
Labels: 2. to review

#4355 drawer: show only server address
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review

#4294 Activity data dividers
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activities/StickyHeaderItemDecoration.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/StickyHeaderAdapter.java
  src/main/res/layout/activity_list_item_header.xml
  src/main/res/values/dims.xml
  src/test/java/com/owncloud/android/ui/adapter/ActivityListAdapterTest.java
Labels: 2. to review

#4344 Connectivity check: no need to use owncloudClient
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/nextcloud/client/network/ClientFactory.java
  src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 2. to review

#4284 Sharees will be in NC17
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review, backport-request

#4361 prepare for 3.8.0 RC1
  .drone.yml
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080051.txt
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#4374 Do not use NContentObserverJob in DI for now
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
Labels: 2. to review, backport-request

#4373 fix shared view
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review, backport-request

#4370 Npe in get sharees
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 2. to review, backport-request

#4372 throttle avatar lookup
  src/main/java/com/owncloud/android/datamodel/ArbitraryDataProvider.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Labels: 2. to review, backport-request

#4360 Update due to Android Studio 3.5.0
  .idea/codeStyles/Project.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  scripts/analysis/findbugs-up.rb
  scripts/analysis/lint-results.txt
  src/main/java/com/nextcloud/client/device/DeviceInfo.kt
Labels: 2. to review

#4386 Bump to 3.8.0 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080052.txt
Labels: 2. to review

#4381 moved multiple account dialog to recyclerview
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/layout/choose_template.xml
  src/main/res/layout/multiple_accounts.xml
  src/test/java/com/owncloud/android/ui/adapter/AccountListAdapterTest.java
Labels: 2. to review, backport-request

#4387 fix possible NPE on stopping contact backup job
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
Labels: 2. to review, backport-request

#4384 Codacy
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 1. developing

#4388 attempt to get gridview test more reliable
  src/androidTest/java/com/owncloud/android/ScreenshotsIT.java
Labels: 2. to review

#4394 3.9.0 Alpha
  build.gradle
Labels: 2. to review

#4397 parent file can be null
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#4416 storage manager can be null
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review, backport-request

#4365 Add printing system to RichDocuments
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsWebView.java
  src/main/java/com/owncloud/android/ui/adapter/PrintAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/PrintAsyncTask.java
  src/main/res/values/strings.xml
Labels: 2. to review

#4419 activity: use lastGiven header
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesContract.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesPresenter.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesRepository.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApi.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApiImpl.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/RemoteActivitiesRepository.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/test/java/com/owncloud/android/ui/activities/ActivitiesPresenterTest.java
  src/test/java/com/owncloud/android/ui/activities/data/activities/RemoteActivitiesRepositoryTest.java
Labels: 2. to review, backport-request

#4421 Codacy
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/operations/UploadException.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivityRepositories.java
  src/main/java/com/owncloud/android/ui/activities/data/files/FileRepositories.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java
Labels: 2. to review

#4429 Backport of #4419
  build.gradle
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesContract.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesPresenter.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesRepository.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApi.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApiImpl.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/RemoteActivitiesRepository.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/test/java/com/owncloud/android/ui/activities/ActivitiesPresenterTest.java
  src/test/java/com/owncloud/android/ui/activities/data/activities/RemoteActivitiesRepositoryTest.java
Labels: 2. to review
