Repository nextcloud/android, pull requests merged in 2019-10, with the labels that each got.

#4208 New audio media player service
  build.gradle
  scripts/analysis/findbugs-results.txt
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/media/AudioFocus.kt
  src/main/java/com/nextcloud/client/media/AudioFocusManager.kt
  src/main/java/com/nextcloud/client/media/ErrorFormat.kt
  src/main/java/com/nextcloud/client/media/LoadUrlTask.kt
  src/main/java/com/nextcloud/client/media/Player.kt
  src/main/java/com/nextcloud/client/media/PlayerError.kt
  src/main/java/com/nextcloud/client/media/PlayerService.kt
  src/main/java/com/nextcloud/client/media/PlayerServiceConnection.kt
  src/main/java/com/nextcloud/client/media/PlayerStateMachine.kt
  src/main/java/com/nextcloud/client/media/PlaylistItem.kt
  src/main/java/com/owncloud/android/media/MediaControlView.java
  src/main/java/com/owncloud/android/media/MediaService.java
  src/main/java/com/owncloud/android/media/MediaServiceBinder.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  src/main/res/values/strings.xml
  src/test/java/com/nextcloud/client/media/AudioFocusManagerTest.kt
  src/test/java/com/nextcloud/client/media/AudioFocusTest.kt
  src/test/java/com/nextcloud/client/media/PlayerStateMachineTest.kt
Labels: 2. to review

#4470 Normalize local target path in auto upload
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/test/java/com/nextcloud/client/utils/FileStorageUtilsTest.kt
Labels: 2. to review, backport-request

#4425 Upload files into subfolder
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/test/java/com/nextcloud/client/utils/FileStorageUtilsTest.kt
Labels: 2. to review, backport-request

#4593 Backport of #4425: Upload files into subfolder
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/test/java/com/nextcloud/client/utils/FileStorageUtilsTest.kt
Labels: 2. to review

#4577 Fix NPE in PreviewMediaFragment
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review, backport-request

#4592 if parent is null, then do a regular check, no early exit
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review, backport-request

#4596 Bump to 3.8.1 RC1
  .idea/codeStyles/Project.xml
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080151.txt
Labels: 2. to review

#4597 make build run again
  build.gradle
Labels: 2. to review

#4357 change command order
  .drone.yml
Labels: 2. to review

#4598 bump to 3.8.1 rc1
  build.gradle
Labels: 2. to review

#4604 Fix NPE in Favorites when file has no local storage path
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review, backport-request

#4621 prevent crash when grid column is -1
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review, backport-request

#4623 Fix recurring synced folder notifications
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/jobs/MediaFoldersDetectionJob.java
Labels: 2. to review, backport-request

#4629 Remove sticky headers from activities list view
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
Labels: backport-request

#4632 hardening on possible NPE due to null account/activity
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#4640 fix disappearing account list on resume
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review, backport-request

#4642 bump to 3.8.1 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080152.txt
Labels: 2. to review

#4637 Enhance single account mode
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/DeepLinkLoginActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#4644 Allow broader check on CheckAuth
  src/main/java/com/owncloud/android/operations/DetectAuthenticationMethodOperation.java
Labels: 2. to review, backport-request

#4648 Auto upload: fix relative paths
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/test/java/com/nextcloud/client/utils/FileStorageUtilsTest.kt
Labels: 2. to review, backport-request

#4626 remove CustomEditTextField
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/components/CustomEditText.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
  src/main/res/values/setup.xml
Labels: 2. to review, backport-request

#4654 Bump to 3.8.1 RC3
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30080153.txt
Labels: 2. to review

#4630 Note about bug fix release schedule
  CONTRIBUTING.md
Labels: 2. to review

#4655 Revert disabling of exception handler
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#4658 3.8.1 release notes
  CHANGELOG.md
Labels: 2. to review

#4659 3.8.1 release notes
  CHANGELOG.md
Labels: 2. to review

#4681 Codacy
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/MediaProvider.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/asynctasks/PrintAsyncTask.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review

#4683 fix sorting of synced folder: NPE if both enabled, but one has null folder name
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java
Labels: 2. to review

#4537 Migrate NContentObserverJob to WorkManager
  build.gradle
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/AppComponent.java
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  src/main/java/com/nextcloud/client/jobs/ContentObserverWork.kt
  src/main/java/com/nextcloud/client/jobs/JobsModule.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/NContentObserverJob.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  src/test/java/com/nextcloud/client/jobs/BackgroundJobFactoryTest.kt
  src/test/java/com/nextcloud/client/jobs/ContentObserverWorkTest.kt
Labels: 2. to review

#4677 Deprecate setAccount logic and remove accounWasSet flag
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
Labels: 2. to review

#4684 more codacy fixes
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review

#4694 Remove onAccountSet from ConflictsResolveActivity
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
Labels: 2. to review

#4689 Remove onAccountSet from FolderPickerActivity
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
Labels: 2. to review

#4699 We do not use UploadPathActivity anymore(?)
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/ui/activity/UploadPathActivity.java
Labels: 2. to review

#4693 Remove onAccountSet from FileDisplayActivity
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#4688 Remove onAccountSet from ShareActivity
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
Labels: 2. to review

#4686 Remove onAccountSet from image and video preview activities
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
Labels: 2. to review

#4687 Remove onAccountSet from UploadFilesActivity
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 2. to review

#4692 Markdown rendering
  build.gradle
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
Labels: 2. to review

#4710 Eliminate account status flags from BaseActivity
  src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
Labels: 2. to review

#4712 Fix possible IndexOutOfBoundsException if returned array is empty
  src/main/java/com/owncloud/android/ui/asynctasks/FetchRemoteFileTask.java
  src/main/res/values/strings.xml
Labels: 2. to review

#4726 NPE in setting note
  src/main/java/com/owncloud/android/ui/dialog/NoteDialogFragment.java
Labels: 2. to review

#4716 DavX5: support login flow
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 2. to review

#4701 Markdown preview syntax highlighting
  build.gradle
  scripts/analysis/findbugs-results.txt
  spotbugs-filter.xml
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
Labels: 2. to review

#3905 enhance DocumentsProvider
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/org/nextcloud/providers/cursors/FileCursor.java
  src/main/java/org/nextcloud/providers/cursors/RootCursor.java
Labels: 2. to review

#4728 Theming for rendering markdown
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
Labels: 2. to review

#4730 fix notification task, if it failed first
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/NotificationExecuteActionTask.java
  src/main/java/com/owncloud/android/ui/notifications/NotificationsContract.java
Labels: 2. to review

#4733 Codacy
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
Labels: 2. to review

#4737 3.9.0 RC1
  .drone.yml
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30090051.txt
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
  src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#4725 SSO: return response headers
  scripts/analysis/findbugs-results.txt
  src/main/aidl/com/nextcloud/android/sso/aidl/IInputStreamService.aidl
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/nextcloud/android/sso/PlainHeader.java
  src/main/java/com/nextcloud/android/sso/Response.java
Labels: 2. to review, backport-request

#4740 Add changelog for 3.9.0 RC1
  CHANGELOG.md
Labels: 2. to review

#4744 bump to 3.10.0 Alpha1
  build.gradle
Labels: 2. to review

#4758 Fix dark theme #1
  src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  src/main/res/layout/first_run_activity.xml
  src/main/res/values/styles.xml
Labels: 2. to review, feature: theming

#4746 use default open chooser with "just once", "always"
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review

#4762 Dark theme: color enhancements
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
  src/main/res/values/setup.xml
Labels: 2. to review

#4768 consistently use snake_case for color resources
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/drawable/list_selector.xml
  src/main/res/layout/contacts_backup_fragment.xml
  src/main/res/layout/deep_link_login.xml
  src/main/res/layout/drawer_header.xml
  src/main/res/layout/file_details_activities_fragment.xml
  src/main/res/layout/file_details_fragment.xml
  src/main/res/layout/file_details_share_user_item.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
  src/main/res/layout/grid_item.xml
  src/main/res/layout/list_footer.xml
  src/main/res/layout/list_item.xml
  src/main/res/layout/media_control.xml
  src/main/res/layout/passcodelock.xml
  src/main/res/layout/richdocuments_webview.xml
  src/main/res/layout/send_button.xml
  src/main/res/layout/send_share_fragment.xml
  src/main/res/layout/share_file_layout.xml
  src/main/res/layout/share_user_item.xml
  src/main/res/layout/ssl_untrusted_cert_layout.xml
  src/main/res/layout/ssl_validator_layout.xml
  src/main/res/layout/storage_path_item.xml
  src/main/res/layout/template_button.xml
  src/main/res/layout/trashbin_item.xml
  src/main/res/layout/upload_files_layout.xml
  src/main/res/layout/upload_list_item.xml
  src/main/res/layout/uploader_list_item_layout.xml
  src/main/res/layout/whats_new_element.xml
  src/main/res/values-night/colors.xml
  src/main/res/values-v21/styles.xml
  src/main/res/values/colors.xml
  src/main/res/values/styles.xml
Labels: 2. to review
