Repository nextcloud/android, pull requests merged in 2020-03, with the labels that each got.

#5557 Show slideshow as new activity
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
Labels: 2. to review

#5530 Improve dev edition changelog generation
  scripts/buildDev
Labels: 2. to review

#5560 dev: change library before building
  scripts/buildDev
Labels: 2. to review

#5496 properly colorize text preview gradient based on theme (day/night)
  screenshots/richworkspaces_dark.png
  screenshots/richworkspaces_light.png
  scripts/updateScreenshots.sh
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/res/layout/list_header.xml
Labels: 2. to review

#5537 Split up share internal link
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#5345 Allows deep linking to open files
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/res/values/strings.xml
Labels: 1. developing

#5549 Fixed crash in Activities tab.
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
Labels: 2. to review

#5566 Disable old login method
  src/main/res/values/setup.xml
Labels: 2. to review

#5575 update dev changelog recognition for updating library
  scripts/buildDev
Labels: 2. to review

#5491 Enhance conflict dialog
  .idea/codeStyles/Project.xml
  screenshots/com.nextcloud.client.ConflictsResolveActivityIT_test.png
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth.png
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting.png
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew.png
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotImages.png
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles.png
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_test.png
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_test2.png
  scripts/updateScreenshots.sh
  src/androidTest/assets/image.jpg
  src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  src/main/res/layout/conflict_resolve_dialog.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#5531 Update to Android Studio 3.6
  .idea/codeStyles/Project.xml
  build.gradle
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  src/main/java/com/nextcloud/android/sso/PlainHeader.java
  src/main/java/com/nextcloud/android/sso/Response.java
  src/main/java/com/owncloud/android/datamodel/ArbitraryDataSet.kt
  src/main/java/com/owncloud/android/datamodel/DecryptedFolderMetadata.java
  src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java
  src/main/java/com/owncloud/android/datamodel/EncryptedFolderMetadata.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/FileSystemDataSet.java
  src/main/java/com/owncloud/android/datamodel/MediaFolderType.java
  src/main/java/com/owncloud/android/datamodel/MediaFoldersModel.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/datamodel/PushConfigurationState.java
  src/main/java/com/owncloud/android/datamodel/SignatureVerification.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderDisplayItem.java
  src/main/java/com/owncloud/android/datamodel/Template.java
  src/main/java/com/owncloud/android/datastorage/StoragePoint.java
  src/main/java/com/owncloud/android/db/OCUpload.java
  src/main/java/com/owncloud/android/features/FeatureItem.java
  src/main/java/com/owncloud/android/operations/CreateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  src/main/java/com/owncloud/android/operations/UpdateSharePermissionsOperation.java
  src/main/java/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/operations/common/SyncOperation.java
  src/main/java/com/owncloud/android/syncadapter/AbstractOwnCloudSyncAdapter.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/StoragePathAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/StoragePathItem.java
  src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
  src/main/java/com/owncloud/android/ui/events/SearchEvent.java
  src/main/java/com/owncloud/android/ui/events/SyncEventFinished.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/utils/OwnCloudSession.java
  src/main/java/com/owncloud/android/utils/svg/SvgDecoder.java
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
Labels: 2. to review, dependencies

#5587 Bump to 3.11 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30110051.txt
Labels: 2. to review

#5569 remove unused class
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/dialog/ChangelogDialog.java
  src/main/res/raw-de/changelog.html
  src/main/res/raw-es/changelog.html
  src/main/res/raw/changelog.html
Labels: 2. to review

#5594 change minimum supported Android version to 4.2
  build.gradle
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_action.xml
  src/main/res/layout/account_item.xml
  src/main/res/layout/account_setup.xml
  src/main/res/layout/activity_list_item.xml
  src/main/res/layout/activity_list_item_header.xml
  src/main/res/layout/activity_row.xml
  src/main/res/layout/activity_sso_grant_permission.xml
  src/main/res/layout/contactlist_list_item.xml
  src/main/res/layout/drawer_header.xml
  src/main/res/layout/file_details_activities_fragment.xml
  src/main/res/layout/file_details_fragment.xml
  src/main/res/layout/file_details_share_user_item.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/layout/file_download_fragment.xml
  src/main/res/layout/file_list_actions_bottom_sheet_creator.xml
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
  src/main/res/layout/files_folder_picker.xml
  src/main/res/layout/files_picker.xml
  src/main/res/layout/grid_image.xml
  src/main/res/layout/grid_item.xml
  src/main/res/layout/info_box.xml
  src/main/res/layout/list_fragment.xml
  src/main/res/layout/list_item.xml
  src/main/res/layout/loading_dialog.xml
  src/main/res/layout/notification_list_item.xml
  src/main/res/layout/search_users_groups_layout.xml
  src/main/res/layout/send_share_fragment.xml
  src/main/res/layout/share_file_layout.xml
  src/main/res/layout/share_user_item.xml
  src/main/res/layout/sorting_order_fragment.xml
  src/main/res/layout/ssl_untrusted_cert_layout.xml
  src/main/res/layout/ssl_validator_layout.xml
  src/main/res/layout/storage_path_item.xml
  src/main/res/layout/synced_folders_item_header.xml
  src/main/res/layout/synced_folders_settings_layout.xml
  src/main/res/layout/text_file_preview.xml
  src/main/res/layout/toolbar_user_information.xml
  src/main/res/layout/trashbin_item.xml
  src/main/res/layout/upload_files_layout.xml
  src/main/res/layout/upload_list_header.xml
  src/main/res/layout/upload_list_item.xml
  src/main/res/layout/uploader_layout.xml
  src/main/res/layout/uploader_list_item_layout.xml
  src/main/res/layout/user_info_details_table_item.xml
  src/main/res/layout/user_info_layout.xml
  src/main/res/layout/version_list_item.xml
  src/main/res/values/dims.xml
Labels: 2. to review

#5605 Fix NPE on restoring file detail sharing fragment
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 2. to review, backport-request

#5607 Use view bindings: https://developer.android.com/topic/libraries/view-binding
  build.gradle
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/res/layout/empty_list.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/layout/upload_list_layout.xml
Labels: 2. to review

#5611 Stale bot shall close only bugs with "need info" and no reply
  .github/stale.yml
  CONTRIBUTING.md
Labels: 2. to review

#5616 Improve readability on active drawer item
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
  src/main/res/values/styles.xml
Labels: 2. to review, backport-request

#5614 Use UTF8 PostMethod everywhere
  src/main/java/com/owncloud/android/files/CreateFileFromTemplateOperation.java
  src/main/java/com/owncloud/android/files/StreamMediaFileOperation.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/operations/RichDocumentsCreateAssetOperation.java
  src/main/java/com/owncloud/android/operations/RichDocumentsUrlOperation.java
  src/main/java/com/owncloud/android/ui/asynctasks/NotificationExecuteActionTask.java
Labels: 2. to review, backport-request

#5617 All files shows root again
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
Labels: 2. to review, backport-request

#5624 Gradle wrapper validation
  .github/workflows/gradle-wrapper-validation.yml
Labels: 2. to review, backport-request

#5608 Fix account switching
  src/androidTest/java/com/owncloud/android/ui/activity/DrawerActivityIT.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review, backport-request

#5631 Bump to 3.11 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30110052.txt
Labels: 2. to review

#5612 Fix exception on computing available space
  src/androidTest/java/com/owncloud/android/ui/helpers/FileOperationsHelperIT.kt
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review, backport-request

#5630 Backport of #5608
  .idea/codeStyles/Project.xml
  src/androidTest/java/com/owncloud/android/ui/activity/DrawerActivityIT.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review

#5625 Fix border of disabled FAB
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review, backport-request

#5632 fix crash when sorting in folder picker
  src/main/java/com/owncloud/android/ui/activity/FilePickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
Labels: 2. to review, backport-request

#5626 Correct font color in dark mode
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/values/colors.xml
Labels: 2. to review, backport-request

#5623 tint back button correctly
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
Labels: 2. to review, backport-request

#5634 Add gradient to preview images in toolbar
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/res/drawable/preview_image_gradient_shape.xml
  src/main/res/layout/toolbar_standard.xml
Labels: 2. to review, design

#5642 Add changelog for 3.11.0 RC2
  CHANGELOG.md
Labels: 2. to review

#5598 Fix the dev edition changelog excluding stuff
  scripts/buildDev
Labels: 2. to review

#5482 Migrate contacts backup job to new background job manager API
  src/androidTest/java/com/nextcloud/client/jobs/BackgroundJobManagerTest.kt
  src/androidTest/java/com/nextcloud/client/migrations/MigrationsDbTest.kt
  src/androidTest/java/com/nextcloud/client/migrations/MigrationsManagerTest.kt
  src/androidTest/java/com/nextcloud/client/migrations/MockSharedPreferences.kt
  src/androidTest/java/com/nextcloud/client/migrations/MockSharedPreferencesTest.kt
  src/main/java/com/nextcloud/client/account/AnonymousUser.kt
  src/main/java/com/nextcloud/client/account/RegisteredUser.kt
  src/main/java/com/nextcloud/client/account/User.kt
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/etm/EtmViewModel.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmBackgroundJobsFragment.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmMigrations.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  src/main/java/com/nextcloud/client/jobs/ContactsBackupWork.kt
  src/main/java/com/nextcloud/client/jobs/JobInfo.kt
  src/main/java/com/nextcloud/client/jobs/JobsModule.kt
  src/main/java/com/nextcloud/client/jobs/TestJob.kt
  src/main/java/com/nextcloud/client/migrations/MigrationInfo.kt
  src/main/java/com/nextcloud/client/migrations/Migrations.kt
  src/main/java/com/nextcloud/client/migrations/MigrationsDb.kt
  src/main/java/com/nextcloud/client/migrations/MigrationsManager.kt
  src/main/java/com/nextcloud/client/migrations/MigrationsManagerImpl.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/res/drawable/ic_arrow_up.xml
  src/main/res/drawable/ic_clock.xml
  src/main/res/layout/etm_background_job_list_item.xml
  src/main/res/layout/fragment_etm_background_jobs.xml
  src/main/res/layout/fragment_etm_migrations.xml
  src/main/res/menu/fragment_etm_background_jobs.xml
  src/main/res/menu/fragment_etm_migrations.xml
  src/main/res/values/strings.xml
  src/test/java/com/nextcloud/client/etm/TestEtmViewModel.kt
  src/test/java/com/nextcloud/client/jobs/BackgroundJobFactoryTest.kt
  src/test/java/com/nextcloud/client/jobs/ContentObserverWorkTest.kt
Labels: 2. to review

#5629 adjust share size
  src/main/java/com/owncloud/android/ui/adapter/SendButtonAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/res/layout/send_button.xml
  src/main/res/values/dims.xml
Labels: 2. to review, backport-request

#5675 Conflict behaviour fix
  screenshots/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotImages.png
  src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#5685 remove outdated background for dev
  src/versionDev/res/drawable-v24/ic_launcher_background.xml
  src/versionDev/res/drawable-v26/ic_launcher_background.xml
Labels: 2. to review

#5658 Dark Mode Improvements
  src/main/java/com/owncloud/android/ui/ThemeableSwitchPreference.java
  src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
  src/main/res/xml/preferences.xml
Labels: 2. to review, backport-request

#5690 Bump to RC3
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30110053.txt
Labels: 2. to review

#5688 Add circle support for searching / displaying
  .drone.yml
  drawable_resources/circles.svg
  screenshots/com.owncloud.android.ui.fragment.OCFileListFragmentIT_createAndShowShareToCircle.png
  screenshots/com.owncloud.android.ui.fragment.OCFileListFragmentIT_createAndShowShareToGroup.png
  screenshots/com.owncloud.android.ui.fragment.OCFileListFragmentIT_createAndShowShareToUser.png
  screenshots/com.owncloud.android.ui.fragment.OCFileListFragmentIT_createAndShowShareViaLink.png
  scripts/analysis/lint-results.txt
  scripts/updateScreenshots.sh
  scripts/wait_for_server.sh
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/ScreenshotsIT.java
  src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/ManageAccountsActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/androidTest/java/com/owncloud/android/ui/preview/PreviewTextFileFragmentTest.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  src/main/res/drawable/ic_circles.xml
Labels: 2. to review, backport-request

#5694 Add changelog for 3.11.0 RC3
  CHANGELOG.md
Labels: 2. to review

#5710 Fix for sso Allow/Deny dialog text color in dark mode.
  src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
Labels: 2. to review, backport-request

#5705 Wrong string
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#5695 fix activity image loading
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityAndVersionListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
Labels: 2. to review, backport-request

#5725 fix drone
  .drone.yml
Labels: backport-request

#5720 Bump to 3.11.0 RC4
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30110054.txt
Labels: 2. to review

#5719 Add question if problem is reproducible on try.nextcloud.com
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 2. to review

#5722 Bump to latest firebase messaging
  gplay.gradle
  scripts/analysis/lint-results.txt
  src/gplay/AndroidManifest.xml
  src/gplay/java/com/nextcloud/client/di/VariantComponentsModule.java
  src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseInstanceIDService.java
  src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseMessagingService.java
Labels: 2. to review, backport-request

#5728 Add changelog for 3.11.0 RC4
  CHANGELOG.md
Labels: 2. to review

#5684 Add rule to rety failing tests
  src/androidTest/java/com/nextcloud/client/RetryTestRule.kt
  src/androidTest/java/com/owncloud/android/AbstractIT.java
Labels: 1. developing

#5738 Fix #5736 Readd enableAccountHandling for show slider
  src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
Labels: 2. to review, backport-request

#5740 Bump to 3.11.0
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30110090.txt
Labels: 2. to review

#5773 edit downloaded md/text file is working now
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
Labels: 2. to review, backport-request

#5775 if no offline editor is available, use OO/Cool/Text
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review, backport-request

#5772 First use preferred mimetypes, then editor for optional mimetypes
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
Labels: 2. to review, backport-request
