Repository nextcloud/android, pull requests merged in 2020-08, with the labels that each got.

#6598 Add changelog for 3.13.0 RC2
  CHANGELOG.md
Labels: 2. to review

#6599 change order of fastlane lanes
  fastlane/Fastfile
Labels: 2. to review, backport-request

#6595 Hide cursor to make UI test more stable
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testNewFolderDialog.png
  src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
Labels: 2. to review

#6623 OCFileListFragment can be used witout FDA, and this crashed
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#6556 TrashbinActivity: viewbindings tests
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_empty.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_error.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_files.png
  src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinActivityIT.kt
  src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinLocalRepository.kt
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/res/layout/trashbin_activity.xml
Labels: 2. to review

#6619 Rename Download into Transfer
  src/androidTest/java/com/nextcloud/client/files/downloader/DownloaderConnectionTest.kt
  src/androidTest/java/com/nextcloud/client/files/downloader/DownloaderTest.kt
  src/androidTest/java/com/nextcloud/client/files/downloader/RegistryTest.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmDownloaderFragment.kt
  src/main/java/com/nextcloud/client/files/downloader/Direction.kt
  src/main/java/com/nextcloud/client/files/downloader/Downloader.kt
  src/main/java/com/nextcloud/client/files/downloader/DownloaderConnection.kt
  src/main/java/com/nextcloud/client/files/downloader/DownloaderImpl.kt
  src/main/java/com/nextcloud/client/files/downloader/DownloaderService.kt
  src/main/java/com/nextcloud/client/files/downloader/Registry.kt
  src/main/java/com/nextcloud/client/files/downloader/Request.kt
  src/main/java/com/nextcloud/client/files/downloader/Transfer.kt
  src/main/java/com/nextcloud/client/files/downloader/TransferState.kt
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review

#6627 Sync of encrypted folders, in sync with RefreshFolderOperation.synchronizeData
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
Labels: 2. to review, backport-request

#6640 bump to 3.13 RC3
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30130053.txt
Labels: 2. to review

#6641 Changelog rc 3.13.0 03
  CHANGELOG.md
Labels: 2. to review

#6646 object.getId() can also be a string if RichObjects refers to an user
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
Labels: 2. to review, backport-request

#6655 Rename Downloader to TransferManager
  src/androidTest/java/com/nextcloud/client/files/downloader/TransferManagerConnectionTest.kt
  src/androidTest/java/com/nextcloud/client/files/downloader/TransferManagerTest.kt
  src/main/java/com/nextcloud/client/etm/EtmViewModel.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmDownloaderFragment.kt
  src/main/java/com/nextcloud/client/files/downloader/DownloaderService.kt
  src/main/java/com/nextcloud/client/files/downloader/Registry.kt
  src/main/java/com/nextcloud/client/files/downloader/TransferManager.kt
  src/main/java/com/nextcloud/client/files/downloader/TransferManagerConnection.kt
  src/main/java/com/nextcloud/client/files/downloader/TransferManagerImpl.kt
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review

#6662 fix npe on setting expiration date on public share
  src/main/java/com/owncloud/android/ui/dialog/ExpirationDatePickerDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 2. to review, backport-request

#6651 make + icon grey600 for proper icon coloring dark/light
  src/main/res/drawable/ic_plus.xml
Labels: 2. to review, backport-request

#6669 removed FAB from text file preview and use FDA one
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/res/layout/text_file_preview.xml
Labels: 2. to review, backport-request

#6671 Bump to 3.13 RC4
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30130054.txt
Labels: 2. to review

#6667 add sort option to UploadFilesActivity and FolderPickerActivity
  screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_open.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.UploadFilesActivityIT_open.png
  src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 2. to review, backport-request

#6674 Add changelog for 3.13.0 RC4
  CHANGELOG.md
Labels: 2. to review

#6721 Prevent NPE: Ensure that mNotificationManager is not null
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review, backport-request

#6714 E2E: support old iv delimiter, read only
  src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review, backport-request

#6728 bump to 3.13.0
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30130090.txt
Labels: 2. to review

#6701 Correct call order when tinting the dialog button
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error.png
  src/androidTest/java/com/nextcloud/client/SettingsActivityIT.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 2. to review, backport-request

#6715 hide FAB on sharing view
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#6724 Do not show big spinner when initial loading a folder that is known to be not empty
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_open.png
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java
Labels: 2. to review, backport-request

#6743 Add changelog for 3.13.0
  CHANGELOG.md
Labels: 2. to review

#6747 Bump to 3.14.0 Alpha
  build.gradle
Labels: 2. to review

#6744 fix mnemonic test
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error.png
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.java
  src/androidTest/java/com/nextcloud/client/SettingsActivityIT.java
Labels: 2. to review, backport-request

#6760 Fix crash on setting password
  src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 2. to review, backport-request

#6771 Fix #5755
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
Labels: 2. to review, backport-request

#6775 do not preview html within our text view
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
Labels: 2. to review, backport-request

#6772 return onError in onPostExecute (which runs on UI thread)
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review, backport-request

#6751 Reset last sync date of files written via DocumentsProvider
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#6807 Fix insert image file picker only opens once
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
Labels: 2. to review

#6735 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 2. to review

#6725 Improve performance of DocumentsProvider#isChildDocument()
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#6805 Fix unresponsive preview player controls
  src/main/res/layout/file_preview.xml
Labels: 2. to review

#6774 arbitrary data set: store "" instead of null
  src/androidTest/java/com/owncloud/android/datamodel/ArbitraryDataProviderIT.kt
  src/main/java/com/owncloud/android/datamodel/ArbitraryDataProvider.java
Labels: 2. to review, backport-request

#6842 update trashbin screenshot
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_files.png
Labels: 3. to release

#6819 Use two chars for avatars
  src/main/java/com/owncloud/android/ui/TextDrawable.java
  src/test/java/com/owncloud/android/ui/TextDrawableTest.kt
Labels: 2. to review

#6859 Do not use scale larger than max scale
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Labels: 2. to review, backport-request
