Repository nextcloud/android, pull requests merged in 2020-02, with the labels that each got.

#5383 Auth activity with primary white color
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/values/colors.xml
  src/main/res/values/styles.xml
Labels: 2. to review, backport-request

#5387 Bump to 3.10.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30100151.txt
Labels: 2. to review

#5231 images: slightly rounded corners
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
  src/main/res/values/dims.xml
Labels: 2. to review

#5363 Changed appcompat 1.1.0 to 1.2.0-alpha02
  build.gradle
Labels: 2. to review

#5089 Add check to make sure cursor is initialized
  src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
Labels: 2. to review

#5246 Fix #2753 "Unresponsive App" error popup when syncing
  src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
Labels: 2. to review

#4878 Added TOC links and Engineering section to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 2. to review, enhancement, needs info/discussion

#5293 Status bar: white/black
  src/main/java/com/nextcloud/client/device/DeviceInfo.kt
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/values-v23/styles.xml
Labels: 2. to review, design

#5388 Add changelog for 3.10.1 RC1
  CHANGELOG.md
Labels: 2. to review

#5401 NAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
  src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApiImpl.java
  src/main/java/com/owncloud/android/ui/activities/data/files/FilesServiceApiImpl.java
  src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
  src/main/java/com/owncloud/android/ui/asynctasks/CheckRemoteWipeTask.java
  src/main/java/com/owncloud/android/ui/asynctasks/NotificationExecuteActionTask.java
  src/main/java/com/owncloud/android/ui/asynctasks/PrintAsyncTask.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.java
Labels: 2. to review

#5296 Fixed defective search
  gradle.properties
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review

#5405 bump to 3.10.1 final
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30100190.txt
Labels: 2. to review

#5406 bump lib to 2.0.1
  build.gradle
Labels: 2. to review

#5328 Added "not enough space dialog"
  screenshots/com.owncloud.android.ui.dialog.SyncFileNotEnoughSpaceDialogFragmentTest_showNotEnoughSpaceDialogForFile.png
  screenshots/com.owncloud.android.ui.dialog.SyncFileNotEnoughSpaceDialogFragmentTest_showNotEnoughSpaceDialogForFolder.png
  src/androidTest/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragmentTest.java
  src/main/java/com/owncloud/android/ui/dialog/ConfirmationDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/values-fr/strings.xml
  src/main/res/values/strings.xml
Labels: 2. to review, design

#5399 extract ArbitraryDataSet class
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/ArbitraryDataProvider.java
  src/main/java/com/owncloud/android/datamodel/ArbitraryDataSet.java
Labels: 2. to review

#5393 Remove UnsetType as we do not have bottom bar anymore…
  screenshots/com.nextcloud.client.ActivitiesActivityIT_openDrawer.png
  screenshots/com.nextcloud.client.FileDisplayActivityIT_drawer.png
  screenshots/com.nextcloud.client.FileDisplayActivityIT_open.png
  screenshots/com.nextcloud.client.FileDisplayActivityIT_showAccounts.png
  screenshots/com.nextcloud.client.NotificationsActivityIT_openDrawer.png
  screenshots/com.nextcloud.client.SyncedFoldersActivityIT_openDrawer.png
  screenshots/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  screenshots/com.owncloud.android.ui.preview.PreviewTextFileFragmentTest_displayJavaSnippetFile.png
  src/androidTest/java/com/nextcloud/client/ActivitiesActivityIT.java
  src/androidTest/java/com/nextcloud/client/NotificationsActivityIT.java
  src/androidTest/java/com/nextcloud/client/SyncedFoldersActivityIT.java
  src/androidTest/java/com/nextcloud/client/UploadListActivityActivityIT.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/events/SearchEvent.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/PhotoFragment.java
Labels: 2. to review

#5407 Add changelog for 3.10.1
  CHANGELOG.md
Labels: 2. to review

#5414 Fix crash: Caused by: java.lang.ClassCastException: java.lang.Object[…
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review

#5432 Migrate drawer menu utilities to new user model
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
Labels: 2. to review

#5422 switch to gplay connected tests, to not run both generic and gplay on drone
  build.gradle
Labels: 1. developing

#5436 Make user model parcelable
  src/androidTest/java/com/nextcloud/client/account/AnonymousUserTest.kt
  src/androidTest/java/com/nextcloud/client/account/RegisteredUserTest.kt
  src/main/java/com/nextcloud/client/account/AnonymousUser.kt
  src/main/java/com/nextcloud/client/account/RegisteredUser.kt
  src/main/java/com/nextcloud/client/account/Server.kt
  src/main/java/com/nextcloud/client/account/User.kt
  src/main/java/com/nextcloud/client/etm/EtmViewModel.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmAccountsFragment.kt
  src/main/res/layout/fragment_etm_accounts.xml
  src/main/res/menu/fragment_etm_accounts.xml
  src/main/res/values/strings.xml
  src/test/java/com/nextcloud/client/etm/TestEtmViewModel.kt
Labels: 2. to review

#5434 Migrate account list to new user model
  screenshots/com.owncloud.android.ui.activity.ManageAccountsActivityIT_open.png
  screenshots/com.owncloud.android.ui.activity.ManageAccountsActivityIT_userInfoDetail.png
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/ManageAccountsActivityIT.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/AccountListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListItem.java
  src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/test/java/com/owncloud/android/ui/adapter/UserListAdapterTest.java
Labels: 2. to review

#5450 Screenshot tests for ETM
  .drone.yml
  screenshots/com.nextcloud.client.etm.EtmActivityTest_accounts.png
  screenshots/com.nextcloud.client.etm.EtmActivityTest_overview.png
  screenshots/com.nextcloud.client.etm.EtmActivityTest_preferences.png
  src/androidTest/java/com/nextcloud/client/etm/EtmActivityTest.kt
Labels: 2. to review

#5466 Add square google icon
  src/main/ic_launcher-web-round.png
  src/main/ic_launcher-web.png
Labels: 2. to review

#5300 Re-enable shared search and add ui test for list shares
  .drone.yml
  screenshots/com.nextcloud.client.FileDisplayActivityIT_showShares.png
  scripts/analysis/findbugs-results.txt
  scripts/updateScreenshots.sh
  scripts/uploadReport.sh
  scripts/wait_for_server.sh
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#5442 Fix crash during text file creation
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java
Labels: 2. to review

#5447 Migrate jobs to new user model
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/MediaFoldersDetectionJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
Labels: 2. to review

#5465 Fixed crash during folder creation (autosync)
  src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityIT.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
Labels: 2. to review

#4788 Setting to also upload existing files
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderDisplayItem.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  src/main/java/com/owncloud/android/db/OCUpload.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
  src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
  src/main/java/com/owncloud/android/ui/helpers/UriUploader.java
  src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  src/main/res/layout/synced_folders_settings_layout.xml
  src/main/res/menu/upload_list_item_file_conflict.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
  src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java
Labels: 2. to review, design, feature:AutoUpload

#5471 Show "add folder info" only if text app is available
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
Labels: 2. to review

#5445 add HEAD Method support for SSO
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
Labels: 2. to review

#5536 Change to better english
  src/main/res/values/strings.xml
Labels: 2. to review
