Repository nextcloud/android, pull requests merged in 2020-06, with the labels that each got.

#6185 Change IDE Kotlin code formatter to follow official recommendations
  .idea/codeStyles/Project.xml
Labels: 2. to review

#6173 New design (UI) - Removed old options menu items from FileDisplayActivity
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/res/menu/activity_file_display.xml
  src/main/res/values/strings.xml
Labels: 2. to review, accessibility, design

#6172 fix search related items in drawer
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/main/res/menu/partial_drawer_entries.xml
Labels: 2. to review

#6190 Fix avatar tests after changes of UI
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/androidTest/java/com/owncloud/android/ScreenshotsIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/DrawerActivityIT.java
Labels: 2. to review

#6204 only scroll to position, if highlighted item exists
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#6198 Applied a new fallback color for DarkMode
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/dialog/SortingOrderDialogFragment.java
  src/main/res/values-night/colors.xml
Labels: 2. to review, design, feature:Theming

#6192 change trashbin view to new layout
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/res/layout/trashbin_activity.xml
  src/main/res/menu/activity_trashbin.xml
Labels: 2. to review

#6211 Add changelog for 3.12.0 RC3
  CHANGELOG.md
Labels: 2. to review

#6203 Upload list activity: new sort / switch button
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/res/menu/activity_upload_files.xml
Labels: 2. to review

#6207 Appbar - Pixel perfect and bug fix
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/res/layout/toolbar_standard.xml
Labels: 2. to review, design

#6213 Fixed a bug relative to actionmode + Enhanced actionmode behaviour
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, accessibility, bug

#6193 Sort/list change for ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/res/layout/receive_external_files.xml
  src/main/res/layout/uploader_layout.xml
  src/main/res/menu/activity_receive_external_files.xml
Labels: 3. to release

#6035 Add etag column to capabilities table
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/operations/GetCapabilitiesOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 3. to release

#6218 Fix move/copy to root folder
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
Labels: 2. to review

#6224 Activity stream on dark mode
  drawable_resources/shared_via_link.svg
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/utils/svg/SvgBitmapTranscoder.java
  src/main/res/drawable-night/shared_via_link.xml
  src/main/res/drawable/shared_via_link.xml
  src/main/res/layout/activity_list_item.xml
Labels: 2. to review

#6222 set gradient via imageview for markdown previews
  screenshots/gplay/debug/richworkspaces_dark.png
  screenshots/gplay/debug/richworkspaces_light.png
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/res/drawable-night/preview_markdown_gradient_shape.xml
  src/main/res/drawable/preview_markdown_gradient_shape.xml
  src/main/res/layout/list_header.xml
Labels: 2. to review

#6226 Added some tool hints for easier development
  src/main/res/layout/fragment_etm_menu.xml
  src/main/res/layout/log_entry_list_item.xml
  src/main/res/layout/multiple_accounts.xml
  src/main/res/layout/notifications_layout.xml
  src/main/res/layout/send_button.xml
  src/main/res/layout/send_share_fragment.xml
  src/main/res/layout/storage_path_dialog.xml
  src/main/res/layout/template_button.xml
  src/main/res/layout/text_file_preview.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/layout/trashbin_activity.xml
  src/main/res/layout/user_info_layout.xml
  src/main/res/layout/whats_new_activity.xml
  src/main/res/layout/whats_new_webview_element.xml
Labels: 2. to review

#6246 use check arrow for chosen account
  src/main/java/com/nextcloud/ui/ChooseAccountDialogFragment.kt
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  src/main/res/layout/account_item.xml
Labels: 2. to review

#6214 Fix crash when creating client
  src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
Labels: 3. to release, backport-request

#6221 remove action_sort
  drawable_resources/ic_sort_variant.svg
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/res/drawable/ic_sort_variant.xml
  src/main/res/menu/activity_folder_picker.xml
Labels: 2. to review

#6255 use ghactions also on stable-3.12
  .github/workflows/detekt.yml
  .github/workflows/gPlayFlavor.yml
  .github/workflows/genericFlavor.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/ktlint.yml
Labels: 2. to review

#6254 replace edge colors
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review, design

#6257 Fix unit tests
  .drone.yml
  scripts/uploadReport.sh
  src/test/java/com/owncloud/android/ui/adapter/UserListAdapterTest.java
Labels: 2. to review

#6260 bump to 3.12.0
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30120090.txt
Labels: 2. to review

#6261 Add changelog for 3.12.0
  CHANGELOG.md
Labels: 2. to review

#5336 Fds tests
  src/androidTest/assets/imageFile.png
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentProviderClientTest.java
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentResolverTest.java
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerTest.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 1. developing

#6300 remove non needed exceptions
  src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
Labels: 2. to review

#6296 tint first run
  src/main/res/values-v19/styles.xml
  src/main/res/values-v21/styles.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#6265 Properly align 3-dot menu of folder items
  src/main/res/layout/synced_folders_item_header.xml
  src/main/res/layout/trashbin_item.xml
  src/main/res/values/dims.xml
Labels: 2. to review, design

#6278 Drop Android 4.2 support
  build.gradle
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 3. to release

#6307 Use MaterialButton for addAccount action in accounts screen
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/res/layout/account_action.xml
Labels: 2. to review

#6309 remove unneeded linearLayout id
  scripts/analysis/lint-results.txt
  src/main/res/layout-land/account_setup.xml
Labels: 3. to release

#6231 Theme refresh bugfix
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 3. to release

#6284 Fix appbar photos view when enter in background
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to release

#6303 Add touch states to file_list_actions_bottom_sheet
  src/main/res/layout/file_list_actions_bottom_sheet_creator.xml
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
Labels: 2. to review

#6283 Show "photos" in title
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#6289 Migrate ContactsPreferenceActivity startup to type-safe API
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
Labels: 2. to review

#6288 [stable-3.12] Fix crash when starting ContactsPreferenceActivity with user extra
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
Labels: 2. to review

#6306 check if activity is running before showing dialog
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
Labels: 2. to review

#6256 fix #5281: click on conflict notification opens conflict dialog directly
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 3. to release

#6335 Fix improper deleting synced folder by OfflineSyncWork
  src/main/java/com/nextcloud/client/jobs/OfflineSyncWork.kt
Labels: 2. to review

#6243 color nav bar
  src/main/res/values-v19/styles.xml
  src/main/res/values-v21/styles.xml
  src/main/res/values-v27/styles.xml
  src/main/res/values/styles.xml
Labels: 3. to release

#6281 #6247 View Binding - FileDisplayActivity and partial Ssl views
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/CertificateCombinedExceptionViewAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/SslCertificateViewAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/SslErrorViewAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/X509CertificateViewAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java
Labels: 3. to release

#6328 Do not run auto upload job directly
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
Labels: 2. to review

#6343 fix LSC_LITERAL_STRING_COMPARISON
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/third_parties/ezvcard_android/ContactOperations.java
Labels: 2. to review

#6327 Combined ShareActivity with FileDetailSharingFragment as much as possible
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ShareUserListAdapter.java
  src/main/java/com/owncloud/android/ui/decoration/SimpleListItemDividerDecoration.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/SearchShareesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFragmentListener.java
  src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/utils/GetShareWithUsersAsyncTask.java
  src/main/res/layout/share_activity.xml
  src/main/res/layout/share_file_layout.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#6353 Use same search hint as on server
  src/main/AndroidManifest.xml
  src/main/res/values/strings.xml
  src/main/res/xml/users_and_groups_searchable.xml
Labels: 2. to review

#6351 rich workspace not in folder picker activity
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#6346 fix URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityAndVersionListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.java
Labels: 2. to review

#6355 on user share permission: unshare as destructive option on bottom
  src/main/res/menu/item_user_sharing_settings.xml
Labels: 2. to review

#6342 View binding
  src/main/java/com/owncloud/android/ui/adapter/SendButtonAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
Labels: 2. to review

#6347 Remove useless parents
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/res/layout/empty_list.xml
  src/main/res/layout/file_preview.xml
  src/main/res/layout/grid_image.xml
  src/main/res/layout/preview_image_fragment.xml
  src/main/res/layout/text_file_preview.xml
Labels: 2. to review

#6345 fix USBR_UNNECESSARY_STORE_BEFORE_RETURN
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/java/util/Optional.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review

#6359 use view instead of linear layout as common parent
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review

#6262 Hide on scrolling
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/res/layout/files.xml
  src/main/res/layout/list_fragment.xml
  src/main/res/layout/receive_external_files.xml
  src/main/res/layout/synced_folders_layout.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/layout/trashbin_activity.xml
Labels: 2. to review

#6361 Fix zoom, toggle background
  src/main/res/layout/preview_image_fragment.xml
Labels: 2. to review

#6344 fix OCP_OVERLY_CONCRETE_PARAMETER
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datastorage/providers/AbstractStoragePointProvider.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/adapter/X509CertificateViewAdapter.java
  src/main/java/third_parties/ezvcard_android/ContactOperations.java
Labels: 3. to release

#6338 Removed legacy login
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/dialog/CredentialsDialogFragment.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
  src/main/res/values/colors.xml
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 3. to release

#6263 Hide on scrolling for activities and notifications
  src/main/res/layout/activity_list_layout.xml
  src/main/res/layout/notifications_layout.xml
Labels: 2. to review

#6253 PreviewImageFragment: if we have no activity, do nothing
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/res/values/strings.xml
Labels: 3. to release, backport-request

#6354 Enhance FileDetailSharingFragment
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#6244 black nav bar on image preview
  src/main/res/values-v19/styles.xml
  src/main/res/values-v21/styles.xml
  src/main/res/values/styles.xml
Labels: 3. to release, design

#6332 Enh/dark theme optimizations
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityIT_showShares.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_open.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentIT_createAndShowShareViaLink.png
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SortingOrderDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
Labels: 2. to review

#6366 Delete outdated comments in case of success
  .drone.yml
  scripts/deleteOutdatedComments.sh
  scripts/uploadReport.sh
Labels: 2. to review

#6341 Replace fragment by FragmentContainerView
  build.gradle
  lint.xml
  scripts/analysis/lint-results.txt
  scripts/uploadReport.sh
  src/main/java/com/nextcloud/client/etm/EtmMenuFragment.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmBackgroundJobsFragment.kt
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/res/layout/upload_files_layout.xml
Labels: 2. to review

#6372 Migate file details and share details to User model
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  src/main/java/com/owncloud/android/ui/adapter/FileDetailTabAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 3. to release

#6364 Fix NPE in OCFileListFragment when OCFile is null
  src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to release, backport-request

#6373 Provide DeckApi via dependency injection framework
  src/androidTest/java/com/nextcloud/client/integrations/deck/DeckApiTest.kt
  src/main/java/com/nextcloud/client/di/AppComponent.java
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/integrations/IntegrationsModule.kt
  src/main/java/com/nextcloud/client/integrations/Package.md
  src/main/java/com/nextcloud/client/integrations/deck/DeckApi.java
  src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.java
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  src/test/java/com/nextcloud/client/jobs/BackgroundJobFactoryTest.kt
Labels: 3. to release

#6358 add multiple share links
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/operations/CreateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/operations/UnshareOperation.java
  src/main/java/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/adapter/PublicShareInterface.java
  src/main/java/com/owncloud/android/ui/adapter/PublicShareListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/PublicShareViewHolder.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/layout/file_details_share_public_link_add_new_item.xml
  src/main/res/layout/file_details_share_public_link_item.xml
  src/main/res/layout/file_details_sharing_fragment.xml
  src/main/res/menu/fragment_file_detail_sharing_link.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 3. to release

#5593 Synced folder dialog: fix summary click event intercepting parent
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/LocalStoragePathPickerDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/main/res/drawable/ic_folder_open.xml
  src/main/res/layout/synced_folders_settings_layout.xml
  src/main/res/layout/upload_list_item.xml
  src/main/res/values/strings.xml
Labels: 3. to release

#6121 enhance deep linking to allow pretty urls
  scripts/deleteOutdatedComments.sh
  src/androidTest/java/com/nextcloud/client/files/DeepLinkHandlerTest.kt
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/files/DeepLinkHandler.kt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to release

#6391 add default to switch
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/media/MediaControlView.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
Labels: 3. to release

#6392 remove EditShareFragment.java
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/fragment/EditShareFragment.java
  src/main/res/layout/edit_share_layout.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 2. to review
