Repository nextcloud/android, pull requests merged in 2020-04, with the labels that each got.

#5817 NC18+: add possibility to set expiration date on user/group shares
  src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  src/main/res/layout/file_details_sharing_fragment.xml
Labels: 2. to review

#5823 Search: only parse search if search event is there
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#5803 Rich workspaces: can be null (if disabled), or string (empty or with content)
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/res/layout/file_details_sharing_fragment.xml
Labels: 2. to review

#5822 Fix crash while showing ConflictDialog
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
Labels: 2. to review, backport-request

#5791 Ignore CHANGELOG.md while generating changelogs
  scripts/buildDev
Labels: 2. to review

#5788 Ninja-fix formatting of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 2. to review

#5754 Show loading instead of empty content
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#5830 Change pdf icon
  drawable_resources/application-pdf.svg
  src/main/res/drawable/file_pdf.xml
Labels: 2. to review

#5829 check if at least one account is set up, before receiving files
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 2. to review, backport-request

#5748 Remove deprecated contacts backup job
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
Labels: 2. to review

#5652 Codacy improvements
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/datamodel/MediaProvider.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/providers/DiskLruImageCacheFileProvider.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activities/StickyHeaderItemDecoration.java
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/java/com/owncloud/android/utils/glide/HttpStreamFetcher.java
Labels: 2. to review

#5756 Migrate contacts import job to new API
  build.gradle
  src/androidTest/java/com/nextcloud/client/jobs/BackgroundJobManagerTest.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  src/main/java/com/nextcloud/client/jobs/ContactsImportWork.kt
  src/main/java/com/owncloud/android/jobs/ContactsImportJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review

#5757 Migrate EditShareFragment to new User model
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  src/main/java/com/owncloud/android/ui/fragment/EditShareFragment.java
Labels: 2. to review

#5835 Log exception in ContactsImportWork catch block
  src/main/java/com/nextcloud/client/jobs/ContactsImportWork.kt
Labels: 2. to review

#5760 Migrate ChooseRichDocumentsTemplateDialogFragment to User
  src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
Labels: 2. to review

#5838 Do not tint dialog
  src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
Labels: 2. to review, backport-request

#5836 E2e token
  build.gradle
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 1. developing

#5798 Limit online editing/streaming when e2e
  build.gradle
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#5761 Migrate FileDownloader server to User model
  src/main/java/com/nextcloud/client/account/CurrentAccountProvider.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
Labels: 2. to review

#5857 Don't put User model into ConflictsResolveActivity account extra
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review, backport-request

#5839 show all files when clicking on show files
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review, backport-request

#5841 Fix OOM during image browsing
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 2. to review

#5873 Notification handle action type "web"
  src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
Labels: 2. to review, backport-request

#5810 Make the name collision policy for auto uploads selectable
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderDisplayItem.java
  src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
  src/main/res/layout/synced_folders_settings_layout.xml
  src/main/res/values/attrs.xml
  src/main/res/values/strings.xml
  src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java
Labels: 2. to review, backport-request, design

#5848 [FIX: #5752] Upload files: too much whitespace
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
Labels: 2. to review, backport-request

#5741 Readd enableAccountHandling for show slider
  src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
Labels: 2. to review

#5876 Release connections after usage
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/ui/asynctasks/NotificationExecuteActionTask.java
  src/main/java/com/owncloud/android/ui/asynctasks/PrintAsyncTask.java
  src/main/java/com/owncloud/android/utils/glide/HttpStreamFetcher.java
Labels: 2. to review

#5886 Bump to 3.11.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30111051.txt
Labels: 2. to review

#5885 Do not run insertAllDBEntriesForSyncedFolder directly
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/jobs/ContentObserverWork.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
Labels: 2. to review

#5912 Make sure only 1 content observer job is scheduled
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
Labels: 2. to review

#5509 Resolved the crash when account is not new (Auth)
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
Labels: 2. to review

#5887 close SSO streams
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/nextcloud/android/sso/Response.java
  src/main/java/com/nextcloud/android/sso/aidl/ParcelFileDescriptorUtil.java
Labels: 2. to review

#5874 Switch to bouncycastle
  build.gradle
  lint.xml
  src/main/java/com/owncloud/android/utils/CsrHelper.java
Labels: 2. to review

#5921 Bump to 3.11.1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30110190.txt
Labels: 2. to review

#5922 Add changelog for 3.11.1
  CHANGELOG.md
Labels: 2. to review

#5941 add missing back button in ManageAccountsActivity & UserInfoActivity
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
Labels: 2. to review

#5951 Bugfix for #5929
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: backport-request

#5948 Bump for 3.12
  .drone.yml
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#5739 Dark Mode Improvements II
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/drawable-night/favorite.xml
  src/main/res/drawable/uploader_list_separator.xml
  src/main/res/layout/conflict_resolve_dialog.xml
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
  src/main/res/values/dims.xml
Labels: 2. to review, backport-request

#5879 Migrate files sync related jobs to WorkManager API
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/nextcloud/client/jobs/BackgroundJobManagerTest.kt
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/etm/EtmViewModel.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmBackgroundJobsFragment.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  src/main/java/com/nextcloud/client/jobs/ContactsBackupWork.kt
  src/main/java/com/nextcloud/client/jobs/ContactsImportWork.kt
  src/main/java/com/nextcloud/client/jobs/ContentObserverWork.kt
  src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  src/main/java/com/nextcloud/client/jobs/OfflineSyncWork.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  src/main/java/com/owncloud/android/jobs/FilesSyncJob.java
  src/main/java/com/owncloud/android/jobs/MediaFoldersDetectionJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  src/main/res/layout/fragment_etm_background_jobs.xml
  src/main/res/menu/fragment_etm_background_jobs.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#5949 Bump to 3.13 alpha
  build.gradle
Labels: 2. to review

#5955 Allow local remote servers
  .drone.yml
  scripts/updateScreenshots.sh
Labels: 2. to review

#5938 New design (UI) - Changed some text styles
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
  src/main/res/values/dims.xml
  src/main/res/values/strings.xml
Labels: 2. to review, design

#5962 Fix background tests
  src/test/java/com/nextcloud/client/etm/TestEtmViewModel.kt
  src/test/java/com/nextcloud/client/jobs/BackgroundJobFactoryTest.kt
Labels: 2. to review

#5933 New design (UI) - appbar color
  src/main/java/com/nextcloud/client/logger/ui/LogsActivity.kt
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_1.png
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_2.png
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_3.png
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_4.png
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_5.png
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_6.png
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_7.png
  src/main/res/drawable-night-xxhdpi/owncloud_progressbar_indeterminate_8.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_1.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_2.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_3.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_4.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_5.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_6.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_7.png
  src/main/res/drawable-xxhdpi/owncloud_progressbar_indeterminate_8.png
  src/main/res/drawable/actionbar_progress_horizontal.xml
  src/main/res/drawable/actionbar_progress_indeterminate_horizontal.xml
  src/main/res/layout/drawer.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/values-night/colors.xml
  src/main/res/values-v21/styles.xml
  src/main/res/values/colors.xml
  src/main/res/values/styles.xml
Labels: 2. to review, design, enhancement

#5892 Migrate notifcation job to work manager api
  src/gplay/java/com/owncloud/android/services/firebase/NCFirebaseMessagingService.java
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
Labels: 2. to review

#5968 Bump to 3.12.0 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30120051.txt
Labels: 2. to review

#5973 Fixed invisible back-button
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
Labels: 2. to review

#5974 Add changelog for 3.12.0 RC1
  CHANGELOG.md
Labels: 2. to review

#5895 Migrate remaining jobs to work manager api
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/jobs/AccountRemovalJob.java
  src/main/java/com/owncloud/android/jobs/NCJobCreator.java
  src/main/java/com/owncloud/android/jobs/NotificationJob.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/asynctasks/CheckRemoteWipeTask.java
Labels: 2. to review

#5979 fix #4540
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 2. to review, backport-request

#5978 fix multiselect
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request
