Repository nextcloud/android, pull requests merged in 2020-11, with the labels that each got.

#7211 Only access data if operation succeeded
  src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  src/main/java/com/nextcloud/ui/ChooseAccountDialogFragment.kt
  src/main/java/com/owncloud/android/ui/asynctasks/RetrieveStatusAsyncTask.java
Labels: 2. to review, backport-request

#7209 Drop NC13-NC15
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/util/SharingMenuHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 2. to review

#7210 Only do UI manipulation if visible
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
Labels: 2. to review, backport-request

#7221 Reduce apk size by ~20 MB
  build.gradle
  src/main/java/com/nextcloud/ui/SetStatusDialogFragment.kt
  src/main/res/layout/dialog_set_status.xml
Labels: 2. to review

#7173 QA to gh actions
  .drone.yml
  .github/workflows/qa.yml
  .idea/codeStyles/Project.xml
Labels: 2. to review

#7164 Test also for connected networks
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
Labels: 1. developing, backport-request

#7229 Fix crash on opening details within PreviewText
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#7230 If relative subfolder cannot be found, do not use it
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review, backport-request

#6820 Photos -> Media/Gallery
  src/androidTest/assets/videoFile.mp4
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerTest.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/datamodel/VirtualFolderType.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/GallerySearchTask.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/main/res/drawable/ic_list_empty_image.xml
  src/main/res/drawable/ic_list_empty_video.xml
  src/main/res/menu/partial_drawer_entries.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#7175 Add changelog for 3.14.0 RC1
  CHANGELOG.md
Labels: 2. to review

#7242 do not tint nc logo
  src/main/res/drawable/nextcloud_logo.xml
  src/main/res/layout/drawer_header.xml
  src/main/res/values/colors.xml
Labels: 2. to review, backport-request

#7105 Replace butterknife with native view binding (File Details Fragments)
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/res/layout/file_details_activities_fragment.xml
  src/main/res/layout/file_details_fragment.xml
Labels: 2. to review, backport-request

#7246 Reset eTag so that capability get parsed again, so status is set
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 2. to review, backport-request

#7264 simplify test min sdk
  .drone.yml
  build.gradle
Labels: 2. to review, backport-request

#7263 Bump to 3.14.0 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30140052.txt
Labels: 2. to review

#7268 Fix AppPreferences Comment Typing Error
  src/main/java/com/nextcloud/client/preferences/AppPreferences.java
Labels: 2. to review

#7186 Update Screenshots
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_open_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_userInfoDetail_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.NotificationsActivityIT_loading.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.NotificationsActivityIT_loading_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialogWithStatusDisabled.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showFiles.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showFiles_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showRichWorkspace.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showRichWorkspace_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.preview.PreviewImageFragmentIT_corruptImage_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.preview.PreviewImageFragmentIT_validImage_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_empty.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_empty_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_error.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_error_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_files.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_files_dark_blue.png
  src/androidTest/java/com/nextcloud/client/etm/EtmActivityTest.kt
  src/androidTest/java/com/owncloud/android/ui/activity/NotificationsActivityIT.kt
  src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinActivityIT.kt
  src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinLocalRepository.kt
Labels: 2. to review, backport-request

#7278 use higher sdk only for lint
  build.gradle
Labels: 2. to review, backport-request

#7181 Theme edit text status message
  src/main/java/com/nextcloud/ui/SetStatusDialogFragment.kt
Labels: 2. to review, backport-request

#7279 use result from combinations
  scripts/runAllScreenshotCombinations
Labels: 1. developing, backport-request

#7271 Show generated avatars is file detail sharing list
  src/main/java/com/owncloud/android/ui/adapter/ShareViewHolder.java
  src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/test/java/com/owncloud/android/ui/adapter/ShareeListAdapterTest.kt
Labels: 2. to review, backport-request

#7287 Add changelog for 3.14.0 RC2
  CHANGELOG.md
  fastlane/metadata/android/en-US/changelogs/30140051.txt
  fastlane/metadata/android/en-US/changelogs/30140052.txt
Labels: 2. to review

#7308 Get last modified time from SAF files put it on the uploaded file
  src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
Labels: 3. to release

#7098 Updated avatar handling
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsSharing_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailSharingFragment_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileNone_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileResharingNotAllowed_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showSharedFiles_dark_blue.png
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  src/main/java/com/owncloud/android/ui/adapter/InternalShareViewHolder.java
  src/main/java/com/owncloud/android/ui/adapter/LinkShareViewHolder.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/ShareViewHolder.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/drawable/ic_chat_bubble.xml
  src/main/res/layout/file_details_share_group.xml
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
Labels: 2. to review

#7009 Run screenshot tests on github actions
  .drone.yml
  .github/workflows/blueDark.yml
  .github/workflows/blueLight.yml
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialog.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialog_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendShareDialogTest_showDialog.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendShareDialogTest_showDialog_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsSharing.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailSharingFragment.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes_dark.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileNone.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileResharingNotAllowed.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showSharedFiles.png
  scripts/deleteOldComments.sh
  scripts/runAllScreenshotCombinations
  scripts/uploadReport.sh
  src/androidTest/java/com/owncloud/android/ui/preview/PreviewImageFragmentIT.kt
Labels: 2. to review

#7351 Bump to 3.14.0
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30140090.txt
Labels: 2. to review

#7359 Black background on video playback in fullscreen mode
  src/main/res/layout/video_layout.xml
Labels: 2. to review

#7339 Fix overlapping seek bar and softkeys
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#7344 Fix black text on dark mode for synced folder preferences
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#7337 NPE on download
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
Labels: 2. to review, backport-request

#7338 show snackbar when entering wrong passcode
  src/main/res/layout/passcodelock.xml
Labels: 2. to review, backport-request

#7353 Fix/disable flaky tests
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentProviderClientIT.java
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentResolverIT.java
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
  src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  src/androidTest/java/com/owncloud/android/providers/DocumentsStorageProviderIT.kt
Labels: 2. to review

#7352 Use sans font on MaterialButtons to have same font overall in app
  screenshots/gplay/debug/com.nextcloud.client.CommunityActivityIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.CommunityActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_open_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FirstRunActivityIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.FirstRunActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_testSyncedFolderDialog.png
  screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_testSyncedFolderDialog_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ContactsPreferenceActivityIT_openContactsPreference.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ContactsPreferenceActivityIT_openContactsPreference_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_open.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_open.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialogWithStatusDisabled.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialogWithStatusDisabled_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_away.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_away_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_dnd.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_dnd_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_fun.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_fun_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_offline.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_offline_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_online.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog_online_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_empty.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_empty_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_error.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_error_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_files.png
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_files_dark_blue.png
  src/androidTest/java/com/nextcloud/client/CommunityActivityIT.java
  src/main/res/layout/account_action.xml
  src/main/res/layout/dialog_choose_account.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#7369 SVG: do not override view box
  src/main/java/com/owncloud/android/utils/svg/SvgBitmapTranscoder.java
Labels: 2. to review, backport-request

#7393 Disable debugging obsolete apis
  gradle.properties
Labels: 2. to review

#7390 Add password screenshot tests
  .idea/codeStyles/Project.xml
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_dark_blue.png
  src/androidTest/java/com/owncloud/android/ui/activity/PassCodeActivityIT.kt
Labels: 2. to review

#7371 Open PreviewMediaFragment only in left fragment
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#7370 Modify passcode setting layout alignment
  src/main/res/layout/passcodelock.xml
Labels: 2. to review

#7340 Directly start foreground service
  src/main/java/com/nextcloud/client/media/PlayerService.kt
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#7411 Use upload_and_delete for direct camera upload
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review, backport-request

#7453 fix pin screenshots
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_dark_blue.png
Labels: 2. to review

#7454 Bump to 3.14.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30140151.txt
Labels: 2. to review

#7375 FileDetailFragment also uses left fragment
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#7461 Stop file only if removed file is an audio file
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#7312 SDK30: Add queries to get info about deck app
  src/main/AndroidManifest.xml
Labels: 2. to review

#7372 Closed the app when press back button from App passcode screen
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
Labels: 2. to review

#7482 When conflicting upload and user decides to keep existing file, do not fail on downloading it
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
Labels: 2. to review, backport-request

#7348 Show file and folder name in resolve conflict dialog
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles_dark_blue.png
  src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  src/main/res/layout/conflict_resolve_dialog.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#7486 Bump to 3.14.1 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30140152.txt
Labels: 2. to review

#7491 Add changelog for 3.14.1 RC2
  CHANGELOG.md
Labels: 2. to review

#7488 More detailed check if >= Android M for metered connections
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
Labels: 2. to review

#7565 getActiveNetwork might be null
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
Labels: 2. to review

#7513 Drop Android 4.4 Support
  build.gradle
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  src/main/java/com/nextcloud/client/jobs/OfflineSyncWork.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/datastorage/DataStorageProvider.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/adapter/PrintAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/PrintAsyncTask.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/helpers/UriUploader.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/java/org/nextcloud/providers/cursors/FileCursor.java
  src/main/java/org/nextcloud/providers/cursors/RootCursor.java
  src/main/res/values-night-v21/styles.xml
  src/main/res/values-v21/styles.xml
  src/main/res/values-v27/styles.xml
  src/main/res/values/strings.xml
  src/main/res/values/styles.xml
Labels: 2. to review
