Repository nextcloud/android, pull requests merged in 2020-09, with the labels that each got.

#6798 Start audio player using foreground service API on Android 26+
  src/main/java/com/nextcloud/client/media/PlayerServiceConnection.kt
Labels: 2. to review

#6748 no sticky broadcast
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/services/SyncFolderHandler.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
Labels: 2. to review

#6875 fix Trashbin IT
  screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_files.png
  src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinActivityIT.kt
Labels: 2. to review

#6806 Improve DocumentsProvider and add tests
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/providers/DocumentsProviderUtils.kt
  src/androidTest/java/com/owncloud/android/providers/DocumentsStorageProviderIT.kt
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 3. to release

#6858 Fix crashing app when adding same account for second time when using qrCode
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review, backport-request

#6870 Fix not waiting for non-metered wifi
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#6822 Reduce extend of FileActivity, use DrawerActivity instead
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
Labels: 2. to review

#6817 Avatar: use display name & adapted algorithm to server one
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_open.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_open.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testAccountChooserDialog.png
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/utils/BitmapUtilsIT.kt
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/TextDrawable.java
  src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 2. to review

#6871 fix inplace scrollview in sharing fragment
  src/main/res/layout/file_details_sharing_fragment.xml
Labels: 2. to review

#6533 add TestActivity to launch fragments in it
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetails_Activities.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetails_Sharing.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailActivitiesFragment.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailSharingFragment.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showFiles.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showOneFile.png
  scripts/androidScreenshotTest
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  src/debug/AndroidManifest.xml
  src/debug/java/com/nextcloud/client/di/BuildTypeComponentsModule.java
  src/debug/kotlin/com/nextcloud/TestActivity.kt
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/adapter/FileDetailTabAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/layout/file_details_fragment.xml
  src/main/res/layout/test_layout.xml
  src/release/java/com/nextcloud/client/di/BuildTypeComponentsModule.java
Labels: 2. to review

#6886 DocumentsStorageProvider: open thumbnail directly
  src/main/java/com/owncloud/android/providers/DiskLruImageCacheFileProvider.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#6900 Fix npe on computing enough space with non-downloaded folder content
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#6910 Bump to 3.13.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30130151.txt
Labels: 2. to review

#6914 Add changelog for 3.13.1 RC1
  CHANGELOG.md
Labels: 2. to review

#6892 add tests for rich workspaces
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showRichWorkspace.png
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  src/debug/java/com/nextcloud/client/TestActivity.kt
Labels: 2. to review

#6927 do not use internal FieldSetter
  src/test/java/com/owncloud/android/ui/adapter/ActivityListAdapterTest.java
Labels: 2. to review

#6880 Don't disable upload retries for uploads from DocumentsProvider
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#6918 unify context access
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#6934 added by new Android Studio
  .idea/codeStyles/Project.xml
Labels: 2. to review

#6924 detect tablet mode again
  scripts/uploadReport.sh
  src/main/res/values-land/bools.xml
Labels: 2. to review

#6954 bump to 3.13.1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30130190.txt
Labels: 2. to review

#6866 UI test: sharees in file list
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.AvatarIT_showAvatars.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showSharedFiles.png
  src/androidTest/java/com/owncloud/android/ui/fragment/AvatarIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/AvatarTestFragment.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  src/debug/res/layout/avatar_fragment.xml
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review

#6955 Add changelog for 3.13.1
  CHANGELOG.md
Labels: 2. to review

#6947 Remove dual pane for rich workspaces
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#6961 Fix not showing comments in file detail view
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesError.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesNone.png
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
Labels: 2. to review

#6928 Do not show sortList group upon resume
  src/debug/java/com/nextcloud/client/TestActivity.kt
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Labels: 2. to review, backport-request

#6981 Add debug webview when using versionDev built
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
Labels: 2. to review

#6984 New media scanner: only use with valid path
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 2. to review

#6983 directly go back to app if SSO is used
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#6999 Do not show shimmer on folders
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review

#6997 Re-use the existing foreground notification for FileUploader progress notifications
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#7001 enhance mnemonic on dark mode
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_error.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic.png
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragmentIT.kt
  src/androidTest/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragmentTest.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  src/main/res/drawable/e2e_border.xml
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
Labels: 2. to review

#7006 Stacktrace is selectable in error activity
  src/main/res/layout/activity_show_error.xml
Labels: 2. to review

#7010 re-add grey200
  src/main/res/values/colors.xml
Labels: 2. to review

#6917 DocumentsStorageProvider: prevent opening stale file contents
  src/androidTest/java/com/owncloud/android/providers/DocumentsStorageProviderIT.kt
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review
