Repository nextcloud/android, pull requests merged in 2020-01, with the labels that each got.

#5035 Make hyperlinks clickable in markdown previews
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
Labels: 2. to review

#5066 Fix "Shared by null" glitch in file details view
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
Labels: 2. to review

#5031 Fix NPE crash on startup when storage manager is not set
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#5102 remove support for NC12
  src/main/java/com/nextcloud/client/account/UserAccountManager.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review

#5054 Fix account switch buttons in drawer header
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review

#5108 Fix text in option menu within image preview
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Labels: 2. to review

#5111 Bump to 3.10 RC1
  .drone.yml
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30100051.txt
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#5114 - fix not clickable rich workspace area
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
Labels: 2. to review, backport-request

#5115 bump to 3.11 alpha
  build.gradle
Labels: 2. to review

#5117 Add changelog for 3.10.0 RC1
  CHANGELOG.md
Labels: 2. to review

#5120 spinner: if primary color is white, use grey
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review, backport-request

#5017 Retrieve parent folder before removing document
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review, backport-request

#5128 editor: click on snackbar closes webview for real
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
Labels: 2. to review, backport-request

#5121 new background icon
  drawable_resources/icon-android-with-dev-as-layer.svg
  drawable_resources/icon-background.png
  drawable_resources/icon-background.svg
  drawable_resources/logo_dev.svg
  drawable_resources/logo_qa.svg
  src/main/ic_launcher-web.png
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/res/drawable-v24/ic_launcher_background.xml
  src/main/res/drawable-v26/ic_launcher_background.xml
  src/main/res/drawable-xxxhdpi/background.jpg
  src/main/res/drawable-xxxhdpi/background.png
  src/main/res/drawable-xxxhdpi/background_nc18.png
  src/main/res/drawable/ic_launcher_foreground.xml
  src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  src/main/res/mipmap-hdpi/ic_launcher.png
  src/main/res/mipmap-mdpi/ic_launcher.png
  src/main/res/mipmap-xhdpi/ic_launcher.png
  src/main/res/mipmap-xxhdpi/ic_launcher.png
  src/main/res/mipmap-xxxhdpi/ic_launcher.png
  src/qa/ic_launcher-web.png
  src/qa/res/drawable-v24/ic_launcher_background.xml
  src/qa/res/drawable-v24/ic_launcher_foreground.xml
  src/qa/res/drawable-v26/ic_launcher_background.xml
  src/qa/res/drawable/ic_launcher_foreground.xml
  src/qa/res/mipmap-hdpi/ic_launcher.png
  src/qa/res/mipmap-mdpi/ic_launcher.png
  src/qa/res/mipmap-xhdpi/ic_launcher.png
  src/qa/res/mipmap-xxhdpi/ic_launcher.png
  src/qa/res/mipmap-xxxhdpi/ic_launcher.png
  src/versionDev/ic_launcher-web.png
  src/versionDev/res/drawable-v24/ic_launcher_background.xml
  src/versionDev/res/drawable/ic_launcher_foreground.xml
  src/versionDev/res/mipmap-anydpi-v26/ic_launcher.xml
  src/versionDev/res/mipmap-hdpi/ic_launcher.png
  src/versionDev/res/mipmap-mdpi/ic_launcher.png
  src/versionDev/res/mipmap-xhdpi/ic_launcher.png
  src/versionDev/res/mipmap-xxhdpi/ic_launcher.png
  src/versionDev/res/mipmap-xxxhdpi/ic_launcher.png
Labels: 2. to review, backport-request

#5133 task needs to be a new object for every button
  src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
Labels: 2. to review, backport-request

#5143 launcher: correct folder position according to AS
  src/main/res/drawable-v26/ic_launcher_foreground.xml
  src/main/res/drawable/ic_launcher_foreground.xml
Labels: 2. to review, backport-request

#5122 show first run again
  src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
Labels: 2. to review, backport-request

#5130 rich workspaces
  drawable_resources/post_add.svg
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/drawable/ic_post_add.xml
  src/main/res/layout/text_file_preview.xml
  src/main/res/menu/activity_file_display.xml
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#5136 make "follow system" default for dark theme
  screenshots/com.nextcloud.client.SettingsActivityIT_open.png
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 2. to review

#5148 bump to 3.10 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30100052.txt
Labels: 2. to review

#5175 UI enhancements to rich workspaces
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  src/main/res/layout/list_header.xml
  src/main/res/layout/text_file_preview.xml
Labels: 2. to review, backport-request

#5172 prevent NPE
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#5181 Export vCard to version 3.0
  src/main/java/com/owncloud/android/jobs/ContactsBackupJob.java
Labels: 2. to review, backport-request

#5187 FAB: show disabled correctly again
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review, backport-request

#5157 Fix NPE in UserAccountManagerImpl.getUser(CharSequence)
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
Labels: 2. to review, backport-request

#5189 Dark theme enhancements
  src/main/res/drawable/uploader_list_separator.xml
  src/main/res/layout/uploader_layout.xml
  src/main/res/layout/uploader_list_item_layout.xml
  src/main/res/values-night/colors.xml
  src/main/res/values/colors.xml
Labels: 2. to review, backport-request

#5193 Upload button: disable/grey when folder is read-only
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 2. to review, backport-request

#5192 Bump to 3.10 RC3
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30100053.txt
Labels: 2. to review

#5201 Add changelog for 3.10.0 RC3
  CHANGELOG.md
Labels: 2. to review

#5211 Bump to 3.10 final
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30100090.txt
Labels: 2. to review

#5220 Add changelog for 3.10.0
  CHANGELOG.md
Labels: 2. to review

#5229 Launcher: color statusbar / navigation bar in primary color
  build.gradle
  src/main/res/values-v21/styles.xml
Labels: 2. to review

#5234 move create rich workspace into bottom sheet
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetActions.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
  src/main/res/menu/activity_file_display.xml
Labels: 2. to review

#5252 Added locking and unlocking of Drawer in Videos Activities/Fragments
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review

#5268 re-enable: coverage only on CI
  build.gradle
Labels: 2. to review

#5267 Fix duplicated rich_workspace in dev version
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 2. to review

#5269 use newest gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 2. to review

#5270 OC bottom list improvement
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/res/layout/file_list_actions_bottom_sheet_creator.xml
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#5249 fix formatting of changelog
  CHANGELOG.md
Labels: 2. to review

#5248 bump material to 1.1.0RC2
  build.gradle
Labels: 2. to review, backport-request, dependencies

#5203 prevent direct editing on < Lollipop
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
Labels: 2. to review, backport-request

#5218 Fix #5213 app is excluded from recent/current apps
  src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
Labels: 2. to review, backport-request

#5294 reproducable dev version: use commit instead of master snapshot for dev version
  scripts/buildDev
Labels: 2. to review

#5209 OnlyOffice: make download possible
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
Labels: 2. to review

#5358 No need of CDATA
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#5360 Test documentation
  .github/ISSUE_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
  build.gradle
  scripts/updateScreenshots.sh
Labels: 2. to review
