Repository nextcloud/android, pull requests merged in 2020-05, with the labels that each got.

#5750 Migrate UserListAdapter to new User model
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
Labels: 2. to review

#6007 show "no new version available" only when clicking on it, not in background check
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 2. to review

#5966 New design (UI) - Replaced some icons
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  src/main/res/drawable/account_circle_white.xml
  src/main/res/drawable/all_files.xml
  src/main/res/drawable/arrow_right.xml
  src/main/res/drawable/favorite.xml
  src/main/res/drawable/file_application.xml
  src/main/res/drawable/file_calendar.xml
  src/main/res/drawable/file_code.xml
  src/main/res/drawable/file_doc.xml
  src/main/res/drawable/file_image.xml
  src/main/res/drawable/file_movie.xml
  src/main/res/drawable/folder.xml
  src/main/res/drawable/ic_account_plus.xml
  src/main/res/drawable/ic_activity.xml
  src/main/res/drawable/ic_activity_light_grey.xml
  src/main/res/drawable/ic_delete.xml
  src/main/res/drawable/ic_dots_vertical.xml
  src/main/res/drawable/ic_folder_black_24dp.xml
  src/main/res/drawable/ic_list_empty_folder.xml
  src/main/res/drawable/ic_list_empty_image.xml
  src/main/res/drawable/ic_list_empty_recent.xml
  src/main/res/drawable/ic_list_empty_shared.xml
  src/main/res/drawable/ic_list_empty_video.xml
  src/main/res/drawable/ic_notification.xml
  src/main/res/drawable/ic_notification_light_grey.xml
  src/main/res/drawable/ic_ok.xml
  src/main/res/drawable/ic_people.xml
  src/main/res/drawable/ic_send.xml
  src/main/res/drawable/ic_settings.xml
  src/main/res/drawable/ic_share.xml
  src/main/res/drawable/ic_show.xml
  src/main/res/drawable/ic_unshared.xml
  src/main/res/drawable/ic_user.xml
  src/main/res/drawable/ic_view.xml
  src/main/res/drawable/ic_warning.xml
  src/main/res/drawable/image_32dp.xml
  src/main/res/drawable/nav_contacts.xml
  src/main/res/drawable/nav_favorites.xml
  src/main/res/drawable/nav_logout.xml
  src/main/res/drawable/nav_notifications.xml
  src/main/res/drawable/nav_photos.xml
  src/main/res/drawable/nav_recently.xml
  src/main/res/drawable/nav_settings.xml
  src/main/res/drawable/nav_shared.xml
  src/main/res/drawable/nav_synced_folders.xml
  src/main/res/drawable/nav_trashbin.xml
  src/main/res/drawable/nav_videos.xml
  src/main/res/drawable/no_network.xml
Labels: 2. to review, design

#6014 Fix account removal
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/dialog/AccountRemovalConfirmationDialog.java
Labels: 2. to review, backport-request

#6015 remove unused file
  src/main/res/drawable/ic_folder_black_24dp.xml
Labels: 2. to review

#6023 Fixed account extra argument passed to OperationsService when starting sync
  src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
Labels: 2. to review, backport-request

#6030 Fix NPE in AccountRemovalConfirmationDialog
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
Labels: 2. to review

#5515 Update strings.xml file
  src/main/res/values/strings.xml
Labels: 2. to review, design

#6040 Fix parameters passed to downloader during contacts list download
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
Labels: 2. to review, backport-request

#6042 New design (UI) - Favorite and "downloaded" icons alignment
  src/main/res/layout/list_item.xml
  src/main/res/values/dims.xml
Labels: 3. to release, design

#6022 New design (UI) - Accounts manage
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  src/main/res/layout/account_item.xml
  src/main/res/menu/item_account.xml
  src/main/res/values/strings.xml
Labels: 3. to release, design

#6051 remove EXTRA_FILE_PATH
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/services/SyncFolderHandler.java
Labels: 2. to review

#6044 New design (UI) - Round thumbnails
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
  src/main/res/layout/grid_image.xml
  src/main/res/layout/grid_item.xml
  src/main/res/layout/list_item.xml
  src/main/res/values/dims.xml
Labels: 3. to release, design

#6056 Fix fab behavior hide and ripple color
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#6073 Fix account IT
  src/androidTest/java/com/owncloud/android/ui/activity/ManageAccountsActivityIT.java
Labels: 2. to review

#5825 send push to deck app, if installed
  src/androidTest/java/com/nextcloud/client/integration/deck/DeckApiTest.kt
  src/main/java/com/nextcloud/client/integration/deck/DeckApi.java
  src/main/java/com/nextcloud/client/integration/deck/DeckApiImpl.java
  src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
Labels: 3. to release

#6063 fix crash when populating info on vanished activity
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
Labels: 2. to review, backport-request

#6075 Fix wrong extra_account, which used user instead of account
  src/main/java/com/nextcloud/client/jobs/ContactsBackupWork.kt
Labels: 2. to review, backport-request

#6068 New design (UI) - Replaced Toolbar Loader by SwipeRefreshLayout
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/PhotoSearchTask.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/layout/toolbar_standard.xml
Labels: 2. to review, design

#5918 Add some tests for upload storage manager
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/datamodel/UploadStorageManagerTest.java
  src/main/java/com/owncloud/android/db/OCUpload.java
Labels: 2. to review

#6067 New design (UI) - Home Appbar
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/animator/appbar_elevation_off.xml
  src/main/res/animator/appbar_elevation_on.xml
  src/main/res/drawable/ic_menu.xml
  src/main/res/layout/accounts_layout.xml
  src/main/res/layout/activity_list_layout.xml
  src/main/res/layout/community_layout.xml
  src/main/res/layout/contacts_preference.xml
  src/main/res/layout/externalsite_webview.xml
  src/main/res/layout/files_folder_picker.xml
  src/main/res/layout/files_picker.xml
  src/main/res/layout/notifications_layout.xml
  src/main/res/layout/synced_folders_layout.xml
  src/main/res/layout/toolbar_standard.xml
  src/main/res/layout/toolbar_user_information.xml
  src/main/res/layout/trashbin_activity.xml
  src/main/res/layout/upload_files_layout.xml
  src/main/res/layout/upload_list_layout.xml
  src/main/res/layout/uploader_layout.xml
  src/main/res/layout/user_info_layout.xml
  src/main/res/values/strings.xml
Labels: 2. to review, design

#6081 Bump to 3.12.0 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30120052.txt
Labels: 2. to review

#6037 Add SQL query pagination in UploadStorageManager
  src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
Labels: 2. to review, backport-request

#6090 Add changelog for 3.12.0 RC2
  CHANGELOG.md
Labels: 2. to review

#6065 Fix selected item background color
  src/main/res/drawable/list_selector.xml
  src/main/res/layout/grid_image.xml
  src/main/res/layout/grid_item.xml
  src/main/res/layout/grid_sync_item.xml
  src/main/res/layout/list_item.xml
  src/main/res/layout/trashbin_item.xml
  src/main/res/layout/uploader_list_item_layout.xml
  src/main/res/values/colors.xml
Labels: 2. to review, design

#6102 Move CI tasks to github actions
  .drone.yml
  .github/workflows/detekt.yml
  .github/workflows/gPlayFlavor.yml
  .github/workflows/genericFlavor.yml
  .github/workflows/gradle-wrapper-validation.yml
  .github/workflows/ktlint.yml
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#6010 Fix wrongly sized png thumbnail after download #6006
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review

#6005 E2E overhaul
  .drone.yml
  build.gradle
  scripts/analysis/findbugs-results.txt
  spotbugs-filter.xml
  src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/FileIT.java
  src/androidTest/java/com/owncloud/android/ScreenshotsIT.java
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  src/androidTest/java/com/owncloud/android/util/ErrorMessageAdapterIT.java
  src/main/java/com/nextcloud/client/account/CurrentAccountProvider.java
  src/main/java/com/nextcloud/client/jobs/OfflineSyncWork.kt
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/jobs/OfflineSyncJob.java
  src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
  src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.java
  src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadException.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/services/SyncFolderHandler.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/SearchShareesFragment.java
  src/main/java/com/owncloud/android/ui/fragment/ShareFileFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  src/main/java/com/owncloud/android/utils/GetShareWithUsersAsyncTask.java
  src/main/java/com/owncloud/android/utils/MimeType.java
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
Labels: 1. developing

#6107 Fix upload and wrote tests
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/FolderPickerActivityIT.java
  src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 2. to review

#6104 Properly show default/generated avatar if there is no one yet
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#6105 New design (UI) - User info activity
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/res/layout/toolbar_user_information.xml
  src/main/res/layout/user_info_details_table_item.xml
  src/main/res/layout/user_info_layout.xml
  src/main/res/values-night-v21/styles.xml
  src/main/res/values-v21/styles.xml
  src/main/res/values-v27/styles.xml
  src/main/res/values/dims.xml
Labels: 2. to review, design

#6101 Test CI against latest stable and master on server
  .drone.yml
  scripts/wait_for_server.sh
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
Labels: 2. to review

#5969 Replace media scanner on newer Android versions
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to release

#6139 Fix contacts backup job interval
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
Labels: 2. to review, backport-request

#6128 If we cancel by user, we pass a reason, so app can handle it correctly
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to release

#6140 Add jaxb dependencies for build (with jdk>8)
  build.gradle
Labels: 2. to review

#6112 Revert "[FIX: #5752] Upload files: too much whitespace"
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
Labels: 2. to review, backport-request

#6151 do not let media scanner throw an exception as otherwise upload fails
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 2. to review, backport-request

#6116 New design (UI) - Choose account dialog
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/ui/ChooseAccountDialogFragment.kt
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  src/main/res/drawable/ic_check_circle.xml
  src/main/res/layout/account_item.xml
  src/main/res/layout/dialog_choose_account.xml
  src/main/res/values/dims.xml
Labels: 2. to review, design

#6152 Remove actionBar if none item selected
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#6146 New design (UI) - Replaced the "View profile" by "Switch account" in Accounts Management
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/res/menu/activity_user_info.xml
  src/main/res/menu/item_account.xml
  src/main/res/values/strings.xml
Labels: 2. to review, design

#6163 fix test
  src/test/java/com/owncloud/android/ui/adapter/UserListAdapterTest.java
Labels: 2. to review

#6168 re-add retry rule
  src/androidTest/java/com/owncloud/android/AbstractIT.java
Labels: 2. to review

#6165 Fix UploadFilesActivity toolbar color in light mode
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/res/layout/toolbar_standard.xml
Labels: 2. to review, bug, design

#6156 New design (UI) - Revamp drawer
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/drawable/ic_down.xml
  src/main/res/drawable/ic_up.xml
  src/main/res/drawable/nextcloud_logo.xml
  src/main/res/layout/drawer.xml
  src/main/res/layout/drawer_header.xml
  src/main/res/menu/partial_drawer_entries.xml
  src/main/res/values/colors.xml
  src/main/res/values/dims.xml
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 2. to review, design

#6176 Enhance synced folder dialog, if disabled
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
Labels: 2. to review

#6175 refresh favorites result in actually reloading favorites
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#6145 New design (UI) - Feature/new design gridmode hide share
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/res/layout/grid_item.xml
Labels: 3. to release, design

#6174 correct empty message for "on devices"
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/res/values/strings.xml
Labels: 2. to review

#6177 exclude all files for backup
  res/xml/backup_config.xml
  src/main/res/xml/backup_config.xml
Labels: 2. to review
