Repository nextcloud/android, pull requests merged in 2020-12, with the labels that each got.

#7538 Make PIN activity mimic a dialog
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_dark_blue.png
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/res/layout/passcodelock.xml
  src/main/res/values/dims.xml
Labels: 2. to review, design

#7333 Add shimmer to preview image fragment
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/res/layout/preview_image_fragment.xml
  src/main/res/layout/toolbar_standard.xml
Labels: 1. developing

#7581 Bump to 3.14.1
  Gemfile.lock
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30140190.txt
Labels: 2. to review

#7584 update version number
  Gemfile.lock
  build.gradle
Labels: 2. to review

#7585 Add changelog for 3.14.1
  CHANGELOG.md
Labels: 2. to review

#7527 Move auto upload to settings
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error.png
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_open_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities.png
  scripts/analysis/lint-results.txt
  src/androidTest/java/com/nextcloud/client/SyncedFoldersActivityIT.java
  src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/res/menu/partial_drawer_entries.xml
  src/main/res/values/strings.xml
  src/main/res/xml/preferences.xml
Labels: 2. to review

#7586 Fix coverage tests
  .drone.yml
Labels: 2. to review, backport-request

#7163 use new emulator
  .drone.yml
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities.png
Labels: 2. to review

#7668 Update help link
  src/main/res/values/setup.xml
Labels: 2. to review, backport-request

#7664 Fix issue #7633
  src/main/res/values/styles.xml
Labels: 2. to review

#7649 Fix upload by sharing link with defensive check during mtime read
  src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
Labels: backport-request

#7708 Remove snapshot repo
  build.gradle
Labels: 2. to review, backport-request

#7691 If path is not set or empty do not run any media scanner
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 2. to review

#7694 Stable-3.14: If path is not set or empty do not run any media scanner
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 2. to review

#7619 Fix Push notifications
  gplay.gradle
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
Labels: 2. to review, backport-request

#7674 fix crash when changing theme after showing media pane
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review

#7695 Stable-3.14: fix not updating sharee list after creating a new link
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
Labels: 2. to review

#7673 fix not updating sharee list after creating a new link
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
Labels: 2. to review
