Repository nextcloud/android, pull requests merged in 2021-03, with the labels that each got.

#7620 plugin: 'kotlin-android-extensions' deprecrated
  build.gradle
  src/main/java/com/nextcloud/client/errorhandling/ShowErrorActivity.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmAccountsFragment.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmMigrations.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmPreferencesFragment.kt
  src/main/java/com/nextcloud/ui/ChooseAccountDialogFragment.kt
  src/main/java/com/nextcloud/ui/SetStatusDialogFragment.kt
  src/main/res/layout/activity_show_error.xml
  src/main/res/layout/toolbar_standard.xml
Labels: 2. to review

#8084 Correctly parse share api
  src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
Labels: 2. to review, backport-request

#8094 Use GITHUB_TOKEN
  .github/workflows/qa.yml
  .github/workflows/screenShotTest.yml
  scripts/deleteOldComments.sh
  scripts/uploadArtifact.sh
Labels: 2. to review

#8104 Use github_token also for auto_approve
  .github/workflows/autoApproveDependabot.yml
Labels: 2. to review

#8109 Bump to 3.15.1 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30150152.txt
Labels: 2. to review

#8095 Assemble can run on ubuntu, so we save precious macOS testing time
  .github/workflows/assembleFlavors.yml
Labels: 2. to review

#7892 Reduce number of calls to /index.php/204 if there is nothing to do.
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
Labels: 2. to review

#8106 Use v2 for user info, also switched to typed response
  src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.java
  src/main/java/com/owncloud/android/operations/GetUserProfileOperation.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/common/SyncOperation.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/asynctasks/RetrieveStatusAsyncTask.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
Labels: 2. to review

#8091 Harden notification empty screenshot test
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
Labels: 2. to review

#8142 Bump to 3.15.1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30150190.txt
Labels: 2. to review

#8143 Changelog release 3.15.1
  CHANGELOG.md
Labels: 2. to review

#8167 add debug section for Windows
  README.md
Labels: 2. to review

#8173 Bump to 3.16.0 RC1
  .drone.yml
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30160051.txt
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#7118 fix documentprovider test failure because of asynchronous upload
  src/androidTest/java/com/owncloud/android/providers/DocumentsStorageProviderIT.kt
Labels: 2. to review

#7289 All files -> media --> all files: show sort header
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_showMediaThenAllFiles.png
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#7877 Allow to upload whole folders.
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/interfaces/LocalFileListFragmentInterface.java
  src/main/java/com/owncloud/android/utils/StringUtils.java
  src/test/java/com/owncloud/android/utils/StringUtilsTest.java
Labels: 3. to release

#7794 Themes header: plain background color and logo, if available
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/db/ProviderMeta.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/java/com/owncloud/android/utils/svg/SVGorImage.java
  src/main/java/com/owncloud/android/utils/svg/SvgOrImageBitmapTranscoder.java
  src/main/java/com/owncloud/android/utils/svg/SvgOrImageDecoder.java
  src/main/java/com/owncloud/android/utils/theme/ThemeColorUtils.java
  src/main/res/layout/drawer_header.xml
Labels: 2. to review

#8137 Enhance overlapping multi-avatar display
  src/main/java/com/owncloud/android/ui/AvatarGroupLayout.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/res/layout/list_item.xml
Labels: 2. to review

#8185 Hide curl output
  scripts/uploadReport.sh
Labels: 2. to review

#8187 dismiss only after delay to remove stuck notification
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
Labels: 3. to release, backport-request

#8188 Password dialog
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testEnforcedPasswordDialog.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testOptionalPasswordDialog.png
  src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/res/values/strings.xml
Labels: 2. to review

#8186 Bump to3.16.0rc2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30160052.txt
Labels: 2. to review

#8203 Bump to 3.17.0 Alpha 1
  build.gradle
Labels: 2. to review

#8222 Auto approve: fix gitHub action
  .github/workflows/autoApproveDependabot.yml
Labels: 2. to review, backport-request
