Repository nextcloud/android, pull requests merged in 2021-07, with the labels that each got.

#8565 revert Kotlin version to make Jacoco work again
  .drone.yml
  build.gradle
  scripts/runCombinedTest.sh
Labels: 1. developing

#8647 SyncOperations always need fileDataStorageManager: throw an Exception if not properly started
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/files/downloader/FileTransferService.kt
  src/main/java/com/nextcloud/client/files/downloader/UploadTask.kt
  src/main/java/com/nextcloud/client/jobs/ContactsBackupWork.kt
  src/main/java/com/owncloud/android/operations/common/SyncOperation.java
Labels: 2. to review

#8639 Add new ShareType: GUEST, FEDERATED_GROUP, DECK, DECK_USER
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#8631 Update command-rebase.yml from template
  .github/workflows/command-rebase.yml
  .github/workflows/rebase.yml
Labels: 2. to review

#8630 move service dismissal to handler to prevent race-condition
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
Labels: 2. to review

#8665 Bump 3.17.0 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30170051.txt
Labels: 2. to review

#8667 Add changelog for 3.17.0 RC1
  CHANGELOG.md
Labels: 2. to review

#8664 Bump master after split off of 3.17
  build.gradle
Labels: 2. to review

#8693 Bump to 3.17.0 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30170052.txt
Labels: 2. to review

#8663 Add stable-* to drone.yml
  .drone.yml
Labels: 2. to review

#8543 Respect dark mode for Web Text Editor
  build.gradle
  src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
Labels: 2. to review

#8655 Remove unused UserListItem.getAccount() method
  src/main/java/com/owncloud/android/ui/adapter/UserListItem.java
Labels: 2. to review

#8658 Migrate FileDisplayActivity to User model
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#8535 Normalize input URL scheme during auth process
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.java
  src/test/java/com/owncloud/android/authentication/AuthenticatorUrlUtilsTest.java
Labels: 2. to review

#8654 Fix NPE when navigating out of PreviewMediaFragment during video loading
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review

#8516 Replace Butterknife with native view bindings
  build.gradle
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/media/MediaControlView.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
  src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/StoragePathAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/LocalStoragePathPickerDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java
  src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
Labels: 2. to review

#8511 Remove Account from UploadsStorageManager
  src/androidTest/java/com/owncloud/android/datamodel/UploadStorageManagerTest.java
  src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt
  src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
Labels: 2. to review

#8726 Initialize last displayed user to correct empty Optional in FileDisplayActivity
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#8741 Mockito 3.11.2 seems to have trouble for us, therefore reverting
  build.gradle
Labels: 2. to review

#8740 Fix test for FileDataStorageManager
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
Labels: 2. to review

#8711 Delete outdated comments before running
  .drone.yml
  scripts/runCombinedTest.sh
Labels: 2. to review

#8739 Fix test for DocumentsStorageProvider
  src/androidTest/java/com/owncloud/android/providers/DocumentsStorageProviderIT.kt
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#8754 Change to uppercase
  src/main/res/values/strings.xml
Labels: backport-request

#8670 Fix tests
  scripts/runCombinedTest.sh
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
Labels: 2. to review

#8761 Remove .gitmodules and references to submodules in SETUP.md
  .gitmodules
  SETUP.md
Labels: 2. to review

#8758 Use new dav
  src/androidTest/java/com/owncloud/android/providers/DocumentsStorageProviderIT.kt
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.java
  src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.java
  src/main/java/com/owncloud/android/operations/UpdateOCVersionOperation.java
Labels: 2. to review

#8756 For SyncOperation FileDataStorageManager is required
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  src/androidTest/java/com/owncloud/android/DownloadIT.java
  src/androidTest/java/com/owncloud/android/FileIT.java
  src/androidTest/java/com/owncloud/android/ScreenshotsIT.java
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  src/androidTest/java/com/owncloud/android/operations/RemoveFileOperationIT.java
  src/androidTest/java/com/owncloud/android/util/ErrorMessageAdapterIT.java
  src/main/java/com/nextcloud/client/files/downloader/UploadTask.kt
  src/main/java/com/nextcloud/client/jobs/OfflineSyncWork.kt
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/operations/CheckCurrentCredentialsOperation.java
  src/main/java/com/owncloud/android/operations/CommentFileOperation.java
  src/main/java/com/owncloud/android/operations/CopyFileOperation.java
  src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  src/main/java/com/owncloud/android/operations/CreateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  src/main/java/com/owncloud/android/operations/GetCapabilitiesOperation.java
  src/main/java/com/owncloud/android/operations/GetSharesForFileOperation.java
  src/main/java/com/owncloud/android/operations/GetUserProfileOperation.java
  src/main/java/com/owncloud/android/operations/MoveFileOperation.java
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
  src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
  src/main/java/com/owncloud/android/operations/UnshareOperation.java
  src/main/java/com/owncloud/android/operations/UpdateNoteForShareOperation.java
  src/main/java/com/owncloud/android/operations/UpdateOCVersionOperation.java
  src/main/java/com/owncloud/android/operations/UpdateSharePermissionsOperation.java
  src/main/java/com/owncloud/android/operations/UpdateShareViaLinkOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/operations/common/SyncOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/services/OperationsService.java
  src/main/java/com/owncloud/android/services/SyncFolderHandler.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review

#8738 Update bouncycastle to 1.69
  build.gradle
  lint.xml
Labels: 2. to review

#8752 Fix exception when running CommentFileOperation
  src/main/java/com/owncloud/android/operations/CommentFileOperation.java
Labels: 2. to review, backport-request

#8779 Pass user info result upon success
  src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.java
Labels: 2. to review
