Repository nextcloud/android, pull requests merged in 2021-12, with the labels that each got.

#9385 DrawerActivity: resize server logo if it's too big
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 2. to review, backport-request

#9395 Refresh gallery screen when deleting a file
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 2. to review, backport-request

#9354 Fix crashes during scheme normalization on login
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.java
  src/test/java/com/owncloud/android/authentication/AuthenticatorUrlUtilsTest.java
Labels: 2. to review, backport-request

#6648 Activity compare tests for #6646
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_empty.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_empty_light_white.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_error.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_error_light_white.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_loading.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_showActivities.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_showActivities_light_white.png
  src/androidTest/java/com/nextcloud/client/ActivitiesActivityIT.java
  src/androidTest/java/com/nextcloud/client/ActivitiesActivityIT.kt
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.java
  src/androidTest/java/com/nextcloud/client/FirstRunActivityIT.java
  src/androidTest/java/com/nextcloud/client/SettingsActivityIT.java
  src/androidTest/java/com/nextcloud/client/SyncedFoldersActivityIT.java
  src/androidTest/java/com/nextcloud/client/UploadListActivityActivityIT.java
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/ScreenshotsIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/DrawerActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/FileDisplayActivityTest.java
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/androidTest/java/com/owncloud/android/ui/preview/PreviewTextFileFragmentTest.java
Labels: 2. to review

#9420 Show trashbin error in a better way
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
Labels: 2. to review, backport-request

#9421 Remove unfavorited file from favorited search
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#9422 Upon select all in upload files activity, enable upload button
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 2. to review, backport-request

#9423 Remember selected files in upload files activity upon screen rotation
  src/main/AndroidManifest.xml
Labels: 2. to review, backport-request

#9425 upload files activity: update select all button when selected files changed
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
Labels: 2. to review

#9431 show mnemonic only if requested
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 2. to review, backport-request

#9433 Refresh on favorite/shared view does search again, not showing root folder content
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#9487 Fix upload button not active unless select all is clicked
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 2. to review, backport-request

#9459 Ask for permission in UploadFilesActivity
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 2. to review, backport-request

#9479 Upon move update folder size
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 2. to review, backport-request

#9480 On video player hide next button, as it is always disabled
  src/main/res/layout/fragment_preview_media.xml
Labels: 2. to review

#9482 Fullscreen toggle
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  src/main/res/layout/exo_player_control_view.xml
  src/main/res/layout/video_layout.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#9483 Better positioning of preview media fragment
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/res/layout/fragment_preview_media.xml
  src/main/res/layout/media_control.xml
Labels: 2. to review

#9484 when re-logging in too fast, we stored an empty auth token
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review

#9485 "set picture as" needs temporary read permission
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review

#9460 Show correct empty screen if gallery search returns empty
  src/main/java/com/owncloud/android/ui/asynctasks/GallerySearchTask.java
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/res/values/strings.xml
Labels: 2. to review

#9461 If no search results from any provider, show it
  src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
  src/main/java/com/owncloud/android/ui/fragment/util/PairMediatorLiveData.kt
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#9462 Expand send share dialog when in landscape mode
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
Labels: 2. to review

#9463 Correctly highlight selected sort order
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/utils/FileSortOrder.java
Labels: 2. to review, backport-request

#9464 highlight correct menu drawer icon
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
Labels: 2. to review, backport-request

#9465 Update footer upon restore/delete of a deleted file
  src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
Labels: 2. to review, backport-request

#9466 Play button as overlay on videos is now more sharpe on large displays
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 2. to review

#9478 Empty list is not centered and in landscape cut off
  src/main/res/layout/empty_list.xml
Labels: 1. developing, backport-request

#9467 update file size upon opening share dialog
  src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
Labels: 2. to review, backport-request

#9468 Extract string to get translated
  src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  src/main/res/values/strings.xml
Labels: backport-request

#9469 Explicitly set background for fragments
  src/main/res/layout/file_details_sharing_menu_bottom_sheet_fragment.xml
  src/main/res/layout/send_share_fragment.xml
Labels: 2. to review, backport-request

#9474 Fix vanishing files after gallery search
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review, backport-request

#9475 Rename remote path upon renaming
  src/main/java/com/owncloud/android/operations/RenameFileOperation.java
Labels: 2. to review, backport-request

#9476 After favorite/unfavorite store this also in db, not only change it in UI
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review, backport-request

#9449 FileDetailFragment: prevent NullPointerException if fileDetailSharingFragment is called too soon
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Labels: 2. to review, backport-request

#9418 Don't make note mandatory for sharing
  src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#9494 DatePickerDialog: fix theme
  src/main/res/values/styles.xml
Labels: 2. to review, backport-request

#9426 UnifiedSearch: Fix opening non-file results with relative URLs
  src/main/java/com/owncloud/android/ui/unifiedsearch/UnifiedSearchViewModel.kt
Labels: 2. to review, backport-request

#9493 Code style: remove autowrap false option
  .idea/codeStyles/Project.xml
Labels: 2. to review

#9522 Unified search: clear focus from search view on open
  src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
  src/main/java/com/owncloud/android/ui/fragment/util/PairMediatorLiveData.kt
Labels: 2. to review, backport-request

#9523 FileDisplayActivity: Preserve title bar after resume
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#9520 [stable-3.18] If no search results from any provider, show it
  src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
  src/main/java/com/owncloud/android/ui/fragment/util/PairMediatorLiveData.kt
  src/main/res/values/strings.xml
Labels: 2. to review

#9526 [stable-3.18] Unified search: clear focus from search view on open
  src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
Labels: 2. to review

#9529 Bump versions for 3.18.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30180151.txt
Labels: 2. to review

#9530 PreviewMediaFragment: fix exoplayer crash in stable-3.18
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review

#9531 Add changelog for 3.18.1 RC1
  CHANGELOG.md
Labels: 2. to review

#8730 Migrate FileActivity.EXTRA_ACCOUNT to EXTRA_USER and use User model as well
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/owncloud/android/db/OCUpload.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review

#9535 When stopping PlayerService, do not use foreground service api
  src/main/java/com/nextcloud/client/media/PlayerService.kt
  src/main/java/com/nextcloud/client/media/PlayerServiceConnection.kt
Labels: 2. to review

#9537 Do not set notification manager to null in uploader service
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#9541 "last modified" column might not exist, thus it shall never fail to upload
  src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
Labels: 2. to review, backport-request

#9547 OCFileListFragment: don't delete search event if resuming a search fragment
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#9434 Unified search: show error when there's no connection
  src/androidTest/java/com/owncloud/android/ui/fragment/UnifiedSearchFragmentIT.kt
  src/debug/java/com/nextcloud/client/TestActivity.kt
  src/main/java/com/owncloud/android/ui/unifiedsearch/UnifiedSearchViewModel.kt
Labels: 2. to review, backport-request

#9427 Fix issue where favorites where loaded by triplicate when opening from Media or other search
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request

#9545 UploadFilesActivity: don't attempt to check selectAll if selectAll is not visible in menu
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 2. to review, backport-request

#9528 Huawei flavor
  .github/workflows/assembleFlavors.yml
  build.gradle
  fastlane/Fastfile
  src/huawei/AndroidManifest.xml
  src/huawei/java/com/nextcloud/client/di/VariantComponentsModule.java
  src/huawei/java/com/owncloud/android/ui.activity/HuaweiCommunityActivity.kt
  src/huawei/java/com/owncloud/android/utils/PushUtils.java
  src/huawei/java/com/owncloud/android/utils/SecurityUtils.java
  src/huawei/res/values/bools.xml
  src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  src/main/res/values/bools.xml
Labels: 2. to review

#9435 OcFileListFragment: throttle overflow menu clicks
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/nextcloud/client/utils/Throttler.kt
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/test/java/com/nextcloud/client/utils/ThrottlerTest.kt
Labels: 2. to review, backport-request

#9448 Sharing: better way to send files from file details view
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentIT.kt
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingMenuBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingMenuBottomSheetActions.java
  src/main/res/layout/file_details_sharing_menu_bottom_sheet_fragment.xml
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#9556 Bump versions for 3.18.1 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30180152.txt
Labels: 2. to review

#9558 Add changelog for 3.18.1 RC2
  CHANGELOG.md
Labels: 2. to review

#9546 Bump Android Gradle Plugin to 7.0.4
  build.gradle
Labels: 2. to review, dependencies

#9589 Adjust instruction how to link library in app
  SETUP.md
Labels: 2. to review

#9597 Fix for too many thumbnails in autoupload settings
  src/main/java/com/owncloud/android/datamodel/ContentResolverHelper.kt
  src/main/java/com/owncloud/android/datamodel/MediaProvider.java
Labels: 2. to review, backport-request

#9559 Fastlane: fix release with 3 apks, and minor improvements
  Gemfile.lock
  fastlane/Fastfile
Labels: 2. to review, backport-request

#9602 Bump versions for 3.18.1 final
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30180190.txt
Labels: 2. to review

#9603 Add changelog for 3.18.1
  CHANGELOG.md
Labels: 2. to review

#9610 Bump Gradle for Log4j
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: 2. to review
