Repository nextcloud/android, pull requests merged in 2021-02, with the labels that each got.

#7836 Add changelog for 3.15.0 RC1
  CHANGELOG.md
Labels: 2. to review

#7917 Bump to 3.15.0
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30150090.txt
Labels: 2. to review

#7918 Add changelog for 3.15.0
  CHANGELOG.md
Labels: 2. to review

#7922 Add changelog for 3.14.3
  CHANGELOG.md
Labels: 2. to review

#7924 Server support bumps for 3.16
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/ui/TextDrawable.java
Labels: 2. to review

#7937 Opens bottom share dialog on every file
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
Labels: 2. to review, backport-request

#7919 Do not crash if wrong deep login url is used
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/DeepLinkLoginActivity.java
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#7955 It can happen that client is null during thumbnail generation via SAF, if so let us create it
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review, backport-request

#7963 Add support for GitHub codespaces
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.env
  .devcontainer/devcontainer.json
Labels: 2. to review

#7916 Use full width of drawer for logo
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer_light_white.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_dark_white.png
  src/main/res/drawable/nextcloud_logo.xml
  src/main/res/layout/drawer_header.xml
  src/main/res/values/dims.xml
Labels: 2. to review, backport-request

#7971 Textfield design
  scripts/analysis/lint-results.txt
  src/androidTest/java/com/owncloud/android/ui/LoginIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/PassCodeActivityIT.kt
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/dialog/NoteDialogFragment.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
  src/main/res/layout/note_dialog.xml
  src/main/res/values/colors.xml
  src/main/res/values/strings.xml
  src/main/res/values/styles.xml
Labels: 2. to review, design

#7994 Resize log-in input fields so they don't span 100% width
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer_light_white.png
  screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login.png
  screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login_dark_white.png
  screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login_light_white.png
  src/androidTest/java/com/nextcloud/client/AuthenticatorActivityIT.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
  src/main/res/values/dims.xml
Labels: 2. to review

#8011 Meaningfull project name
  settings.gradle
Labels: 2. to review

#7889 Update SETUP.md
  SETUP.md
Labels: 2. to review

#7997 Pin prompt: add brute force: delay from 1 to 10s when wrong input
  src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/res/values/strings.xml
  src/test/java/com/nextcloud/client/preferences/TestAppPreferences.java
Labels: 2. to review

#7207 Use new GetMethod, drop apache one
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/nextcloud/client/network/ConnectivityServiceImplIT.kt
  src/main/java/com/nextcloud/client/network/ClientFactory.java
  src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  src/main/java/com/nextcloud/client/network/NetworkModule.java
  src/main/java/com/nextcloud/client/network/PlainHttpClient.java
  src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 2. to review

#8005 Template Dialog: template needs to be selected
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_light_white.png
  scripts/analysis/lint-results.txt
  src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/adapter/RichDocumentsTemplateAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/TemplateAdapter.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetActions.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
  src/main/res/layout/choose_template.xml
  src/main/res/layout/template_button.xml
  src/main/res/values-night/colors.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#8022 Replace edge colors for primary color highlighting of tabs
  src/main/java/com/owncloud/android/utils/ThemeUtils.java
Labels: 2. to review

#8025 Use stale actions instead of stale bot
  .github/stale.yml
  .github/workflows/stale.yml
Labels: 2. to review

#8026 After reboot passcode timeout was miscalculated
  src/main/java/com/owncloud/android/authentication/PassCodeManager.java
Labels: 2. to review, backport-request

#8031 Stale actions: update label set
  .github/workflows/stale.yml
Labels: 2. to review

#8027 Try to fetch avatar only if sharee type is "federated"
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 2. to review, backport-request

#7993 user search: when reusing temp file, we first need to delete it
  src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
Labels: 2. to review, backport-request

#7949 Dont dismiss notification after each upload/download
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesNone_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities_light_white.png
  src/androidTest/java/com/owncloud/android/ui/activity/NotificationsActivityIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#8034 Harmonize screenshot test with a matrix
  .github/workflows/blueDark.yml
  .github/workflows/blueLight.yml
  .github/workflows/screenShotTest.yml
  .github/workflows/whiteDark.yml
Labels: 2. to review

#8035 [Testing] Matrix screenshot
  .github/workflows/blueDark.yml
  .github/workflows/blueLight.yml
  .github/workflows/screenShotTest.yml
  .github/workflows/whiteDark.yml
Labels: 1. developing

#8024 Fix: uncommon files add bin
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/helpers/UriUploader.java
  src/main/java/com/owncloud/android/utils/UriUtils.java
  src/main/java/com/owncloud/android/utils/UriUtils.kt
  src/main/res/values/strings.xml
Labels: 2. to review

#7867 Migrate UriUploader to User model
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
  src/main/java/com/owncloud/android/ui/helpers/UriUploader.java
Labels: 2. to review

#7868 Migrate ThumbnailsCacheManager to User model
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/TextDrawable.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#8044 Backport of #7916
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer_light_white.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer_light_white.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer_dark_blue.png
  screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request_dark_white.png
  src/main/res/drawable/nextcloud_logo.xml
  src/main/res/layout/drawer_header.xml
  src/main/res/values/dims.xml
Labels: 2. to review

#7992 Fix wrong sharing behavior.
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
Labels: 2. to review, backport-request

#8043 [Testing] Build flavors with matrix
  .github/workflows/assembleFlavors.yml
  .github/workflows/gPlayFlavor.yml
  .github/workflows/genericFlavor.yml
Labels: 1. developing

#8036 Build flavors with matrix
  .github/workflows/assembleFlavors.yml
  .github/workflows/gPlayFlavor.yml
  .github/workflows/genericFlavor.yml
Labels: 3. to release

#8033 Dependabot for actions
  .github/dependabot.yml
Labels: 2. to review

#8048 Harmonize check CI jobs
  .github/workflows/check.yml
  .github/workflows/detekt.yml
Labels: 2. to review

#8012 Moving "cancel" dialog-button-action
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testNewFolderDialog.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testNewFolderDialog_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testNewFolderDialog_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testNewFolderDialog_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRenameFileDialog.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRenameFileDialog_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRenameFileDialog_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRenameFileDialog_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendShareDialogTest_showDialog_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesNone_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities_dark_white.png
  src/androidTest/java/com/owncloud/android/ui/dialog/SendShareDialogTest.kt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/StorageMigration.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/dialog/AccountRemovalConfirmationDialog.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/ConfirmationDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/LocalStoragePathPickerDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/NoteDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/RenamePublicShareDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/utils/theme/ThemeButtonUtils.java
Labels: 2. to review

#8046 Grab Espresso results and apk
  .github/workflows/screenShotTest.yml
Labels: 2. to review

#8045 Proposal to change max line length
  .editorconfig
  .gitignore
Labels: 2. to review

#8058 Fix screenshot tests on TestActivity
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendShareDialogTest_showDialog_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_error_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_error_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesError_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesError_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesError_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesNone_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesNone_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivities_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsSharing_dark_blue.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsSharing_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsSharing_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes_light_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showSharedFiles_dark_white.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showSharedFiles_light_white.png
  src/debug/java/com/nextcloud/client/TestActivity.kt
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Labels: 2. to review

#8060 Before uploading failed reports check if secrets are set
  scripts/uploadReport.sh
Labels: 1. developing

#8068 Reduce stored artifact size
  .github/workflows/screenShotTest.yml
Labels: 2. to review
