Repository nextcloud/android, pull requests merged in 2021-05, with the labels that each got.

#8340 Attach view to parent when calling Inflater
  src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
Labels: 2. to review, backport-request

#8344 l10n: Spelling unification
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#8334 Prevent NPE on non-existing account
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 2. to review

#8321 Prevent http redirection if https is used during login
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/res/values/strings.xml
Labels: 2. to review

#8356 Avatar generation can take long, so better check if ChooseAccountDialogFragment is still active
  scripts/uploadReport.sh
  src/main/java/com/nextcloud/ui/ChooseAccountDialogFragment.kt
Labels: 2. to review, backport-request

#8396 Android Studio 4.2
  .github/workflows/assembleFlavors.yml
  .idea/codeStyles/Project.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  scripts/analysis/lint-results.txt
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
Labels: 2. to review

#8346 l10n: Change to lowercase
  src/main/res/values/strings.xml
Labels: 2. to review

#8385 Fix ConnectivityService.isInternetWalled() check when content length is -1
  src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 2. to review

#8343 Avoid leaking AccountManagerService via InputStreamBinder
  src/main/java/com/owncloud/android/services/AccountManagerService.java
Labels: 3. to release

#6949 Allow upload only if a file is selected
  src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
Labels: 2. to review

#8433 prevent upload from sensitive path
  src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 2. to review

#8439 re-order account removal
  src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt
Labels: 2. to review, backport-request

#8438 check e2e keys
  src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review, backport-request

#8467 Remove jaxb
  build.gradle
Labels: 2. to review

#8469 Remove jcenter, use maven instead
  build.gradle
Labels: 2. to review

#8480 analysis-wrapper.sh: fix not Null check
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#8228 Use web/http input type
  src/main/res/layout-land/account_setup.xml
  src/main/res/layout/account_setup.xml
Labels: 3. to release

#8472 Remove spotbug version
  build.gradle
  scripts/analysis/findbugs-results.txt
Labels: 2. to review

#8488 Rebase action: /rebase as comment
  .github/workflows/rebase.yml
Labels: 1. developing

#8489 Fix not null fix
  scripts/analysis/analysis-wrapper.sh
Labels: 2. to review

#8490 Bump to 3.16.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30160151.txt
Labels: 2. to review

#8491 Add changelog for 3.16.1 RC1
  CHANGELOG.md
Labels: 2. to review

#8475 Use JDK11 and Gradle 6.7.1 in Android container
  .drone.yml
  .github/workflows/assembleFlavors.yml
  scripts/uploadReport.sh
Labels: 1. developing

#8390 Gradle 6.9
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 1. developing

#8471 Update Kotlin
  build.gradle
Labels: 2. to review

#8470 Replace fragment by fragment-ktx as suggested
  build.gradle
Labels: 2. to review

#8359 Use correct eTag to check if something has changed on server
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 2. to review

#8290 Optimize writing out files to Nextcloud via SAF
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 3. to release

#7874 New upload manager
  src/androidTest/java/com/nextcloud/client/files/downloader/DownloaderServiceTest.kt
  src/androidTest/java/com/nextcloud/client/files/downloader/RegistryTest.kt
  src/androidTest/java/com/nextcloud/client/files/downloader/TransferManagerConnectionTest.kt
  src/androidTest/java/com/nextcloud/client/files/downloader/TransferManagerTest.kt
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/androidTest/java/com/owncloud/android/datamodel/UploadStorageManagerTest.java
  src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/etm/EtmViewModel.kt
  src/main/java/com/nextcloud/client/etm/pages/EtmFileTransferFragment.kt
  src/main/java/com/nextcloud/client/files/downloader/DownloadTask.kt
  src/main/java/com/nextcloud/client/files/downloader/FileTransferService.kt
  src/main/java/com/nextcloud/client/files/downloader/PostUploadAction.kt
  src/main/java/com/nextcloud/client/files/downloader/Request.kt
  src/main/java/com/nextcloud/client/files/downloader/Transfer.kt
  src/main/java/com/nextcloud/client/files/downloader/TransferManager.kt
  src/main/java/com/nextcloud/client/files/downloader/TransferManagerConnection.kt
  src/main/java/com/nextcloud/client/files/downloader/TransferManagerImpl.kt
  src/main/java/com/nextcloud/client/files/downloader/UploadTask.kt
  src/main/java/com/nextcloud/client/files/downloader/UploadTrigger.kt
  src/main/java/com/nextcloud/client/jobs/ContactsBackupWork.kt
  src/main/java/com/nextcloud/client/notifications/AppNotificationManager.kt
  src/main/java/com/nextcloud/client/notifications/AppNotificationManagerImpl.kt
  src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  src/main/java/com/owncloud/android/db/OCUpload.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/files/services/NameCollisionPolicy.java
  src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.java
  src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/UriUploader.java
  src/main/res/drawable/ic_cloud_download.xml
  src/main/res/drawable/ic_cloud_upload.xml
  src/main/res/layout/etm_transfer_list_item.xml
  src/main/res/layout/fragment_etm_downloader.xml
  src/main/res/menu/fragment_etm_file_transfer.xml
  src/main/res/values/strings.xml
  src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java
Labels: 3. to release

#8499 l10n: With a capital letter
  src/main/res/values/strings.xml
Labels: backport-request
