Repository nextcloud/android, pull requests merged in 2021-06, with the labels that each got.

#8505 Bump to 3.16.1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30160190.txt
Labels: 2. to review

#8506 Fix preview test, due to incomplete backport
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
Labels: 2. to review

#8509 Drop Android 5.0 Support
  CHANGELOG.md
  build.gradle
  scripts/analysis/lint-results.txt
  src/main/java/com/nextcloud/client/device/DeviceInfo.kt
  src/main/java/com/nextcloud/client/device/PowerManagementServiceImpl.kt
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
  src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  src/test/java/com/nextcloud/client/device/TestPowerManagementService.kt
Labels: 2. to review

#8405 Allow 3rd party apps to open the trashbin for a specific account
  src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinActivityIT.kt
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
Labels: 2. to review

#8537 l10n: Separate words
  src/main/res/values/strings.xml
Labels: 2. to review, backport-request

#8132 Replace video player by ExoPlayer
  build.gradle
  scripts/analysis/lint-results.txt
  src/main/java/com/nextcloud/client/media/Player.kt
  src/main/java/com/nextcloud/client/media/PlayerService.kt
  src/main/java/com/nextcloud/client/media/PlayerServiceConnection.kt
  src/main/java/com/nextcloud/client/media/PlaylistItem.kt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  src/main/res/layout/fragment_preview_media.xml
  src/main/res/layout/video_layout.xml
  src/main/res/values/strings.xml
Labels: 1. developing

#8554 Correct etag check/store when it has changed
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 2. to review

#8579 Create SECURITY.md
  SECURITY.md
Labels: 2. to review

#8634 Lint: ignore zero, as we do not show those translated strings in case of zero/empty
  lint.xml
Labels: 2. to review, backport-request

#8567 better localId
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/test/java/com/owncloud/android/datamodel/OCFileTest.java
Labels: 2. to review
