Repository nextcloud/android, pull requests merged in 2021-09, with the labels that each got.

#8934 Replace Facebook lib to get screenshots again
  build.gradle
  scripts/androidScreenshotTest
Labels: 2. to review

#8933 Revert "Bump hwsecurity-fido from 4.1.0 to 4.4.0"
  build.gradle
Labels: 2. to review, backport-request

#8936 Minor script improvements
  .drone.yml
  .github/workflows/screenShotTest.yml
  scripts/androidScreenshotTest
  scripts/deleteOldComments.sh
  scripts/runAllScreenshotCombinations
  scripts/runCombinedTest.sh
  scripts/uploadReport.sh
Labels: 2. to review

#8656 Migrate ThumbnailCacheManager to User model
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/UploaderAdapter.java
Labels: 2. to review

#8965 l10n: Spelling unification
  src/main/res/values/strings.xml
Labels: backport-request

#8967 Fix old screenshot test comments deletion
  .github/workflows/screenShotTest.yml
  scripts/deleteOldComments.sh
Labels: 2. to review

#9014 Minor improvements to git hooks
  scripts/hooks/pre-commit
  scripts/hooks/pre-push
Labels: 2. to review

#8818 add custom PatchMethod class to use http PATCH requests with the Nextcloud SSO api
  scripts/analysis/findbugs-results.txt
  src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  src/main/java/com/nextcloud/android/sso/PatchMethod.java
Labels: 2. to review

#9024 Bump to 3.17.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30170151.txt
Labels: 2. to review

#8703 Enhance screenshot handling
  .drone.yml
  .github/workflows/screenShotTest.yml
  screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login.png
  screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.NotificationsActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open.png
  screenshots/gplay/debug/com.nextcloud.client.etm.EtmActivityTest_accounts.png
  screenshots/gplay/debug/com.nextcloud.client.etm.EtmActivityTest_overview.png
  screenshots/gplay/debug/com.nextcloud.client.etm.EtmActivityTest_preferences.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_open.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_userInfoDetail.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.NotificationsActivityIT_loading.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete.png
  screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request.png
  scripts/generateScreenshotOverview.sh
  scripts/runAllScreenshotCombinations
  scripts/screenshotCombinations
  scripts/screenshotSummary.sh
  scripts/uploadScreenshotSummary.sh
  src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.java
  src/androidTest/java/com/nextcloud/client/etm/EtmActivityTest.kt
  src/androidTest/java/com/owncloud/android/AbstractIT.java
  src/androidTest/java/com/owncloud/android/ui/activity/NotificationsActivityIT.kt
  src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  src/main/java/com/owncloud/android/ui/asynctasks/RetrieveStatusAsyncTask.java
Labels: 2. to review

#9027 scripts/drone: Use deleteOldComments everywhere
  .drone.yml
  scripts/deleteOutdatedComments.sh
  scripts/runAllScreenshotCombinations
  scripts/runCombinedTest.sh
Labels: 2. to review

#8831 Fix: boxed primitive for compare
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
  src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 2. to review

#9032 Re-add retryTestRule
  src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java
  src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
Labels: 2. to review

#9033 Test against stable 22
  .drone.yml
Labels: 2. to review

#9039 Remove setHasFixedSize as it is not needed
  src/main/java/com/owncloud/android/ui/dialog/SendFilesDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
Labels: 2. to review
