Repository nextcloud/android, pull requests merged in 2022-01, with the labels that each got.

#9582 Player: don't try to pause a non-running media player
  src/main/java/com/nextcloud/client/media/Player.kt
Labels: 1. developing

#9644 Clean up AccountRemovalWork
  src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
Labels: 2. to review

#9607 AuthenticatorAsyncTask: check if user info result is success before proceeding
  src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.java
Labels: 2. to review

#9591 SettingsActivityIT: fix showMnemonic running on wrong thread
  src/androidTest/java/com/nextcloud/client/SettingsActivityIT.java
  src/androidTest/java/com/nextcloud/client/SettingsActivityIT.kt
Labels: 2. to review

#9359 Fix dependabot.yml syntax
  .github/dependabot.yml
Labels: 2. to review

#9646 Run contacts backup job only when network is connected
  src/androidTest/java/com/nextcloud/client/migrations/MigrationsManagerTest.kt
  src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  src/main/java/com/nextcloud/client/jobs/ContactsBackupWork.kt
  src/main/java/com/nextcloud/client/migrations/Migrations.kt
  src/main/java/com/nextcloud/client/migrations/MigrationsManagerImpl.kt
Labels: 2. to review

#9572 URI permissions
  src/main/java/com/nextcloud/client/utils/IntentUtil.kt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/dialog/SendFilesDialog.java
  src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review

#9666 FileOperationsHelper: fix aliasing when toggling favorite files
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 2. to review

#9674 Fix failing username/password upon uploading failing screenshots
  .github/workflows/screenShotTest.yml
  scripts/uploadReport.sh
  src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
Labels: 2. to review

#9642 ChooseTemplateDialog: Fix crash on prefillFilenameIfEmpty
  src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java
Labels: 2. to review

#9622 Fix sliders theming for calendar backup settings
  src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.java
  src/main/java/com/owncloud/android/utils/theme/ThemeCheckableUtils.java
  src/main/res/layout/backup_fragment.xml
Labels: 2. to review

#9687 Codecov: wait for CI
  .codecov.yml
Labels: 2. to review

#9677 Fix sending multiple files
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialogDifferentTypes_Screenshot.png
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialog_Screenshot.png
  src/androidTest/java/com/owncloud/android/ui/dialog/SendFilesDialogTest.kt
  src/main/java/com/nextcloud/client/utils/IntentUtil.kt
  src/main/java/com/owncloud/android/ui/dialog/SendFilesDialog.java
  src/main/res/values/strings.xml
Labels: 2. to review

#9688 Run analysis workflow in github actions
  .drone.yml
  .github/workflows/analysis.yml
  scripts/analysis/findbugs-up.rb
  scripts/analysis/lint-up.rb
Labels: 2. to review

#9699 Remove unused test automation
  automationTest/.classpath
  automationTest/.gitignore
  automationTest/.project
  automationTest/.settings/org.eclipse.jdt.core.prefs
  automationTest/.settings/org.eclipse.m2e.core.prefs
  automationTest/README.md
  automationTest/pom.xml
  automationTest/resources/.gitignore
  automationTest/src/test/java/com/owncloud/android/test/ui/actions/Actions.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/FailingTestCategory.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/FlexibleCategories.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/IgnoreTestCategory.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/InProgressCategory.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/NoIgnoreTestCategory.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/OtherTestCategory.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/PatternClasspathClassesFinder.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/SmokeTestCategory.java
  automationTest/src/test/java/com/owncloud/android/test/ui/groups/UnfinishedTestCategory.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/CertificatePopUp.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/ElementMenuOptions.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/FileDetailsView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/FileListView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/GmailEmailListView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/GmailEmailView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/GmailSendMailView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/ImageView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/LoginForm.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/MenuList.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/MoveView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/NewFolderPopUp.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/NotificationView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/PassCodeRequestView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/PassCodeView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/RemoveConfirmationView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/SettingsView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/ShareView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/UploadFilesView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/UploadView.java
  automationTest/src/test/java/com/owncloud/android/test/ui/models/WaitAMomentPopUp.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/.gitignore
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/Common.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/Config.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/CreateFolderTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/DeleteFileTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/DeleteFolderTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/LoginTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/LogoutTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/MoveFileTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/MoveFolderTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/PasscodeTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/RefreshFolderTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/RenameFileTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/RenameFolderTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/RunFailingTests.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/RunInProgressTest.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/RunNoIgnoreTests.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/RunSmokeTests.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/ShareLinkFileTestSuite.java
  automationTest/src/test/java/com/owncloud/android/test/ui/testSuites/UploadTestSuite.java
  automationTest/src/test/resources/.gitignore
Labels: 2. to review

#9692 Screenshot tests: Improve Activities activity tests
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_empty.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_error.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_loading.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer.png
  screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_showActivities.png
  src/androidTest/java/com/nextcloud/client/ActivitiesActivityIT.kt
  src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#9606 Fix NPE in BackupFragment when fragment exits while refresh is happening
  src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.java
Labels: 2. to review

#9691 Improvements in sync conflict resolution
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
Labels: 2. to review

#9710 SessionMixin: set currentAccount to null when no accounts are available
  src/main/java/com/nextcloud/client/mixins/SessionMixin.kt
Labels: 2. to review

#9711 Codecov: don't annotate diffs
  .codecov.yml
Labels: 2. to review

#9708 remove not used videos drawer entry
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/main/res/drawable/nav_videos.xml
  src/main/res/menu/partial_drawer_entries.xml
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#9694 FileContentProvider: use projections for helper queries
  .github/workflows/analysis.yml
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentResolverIT.java
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentResolverIT.kt
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 1. developing

#9121 Update README.md
  CONTRIBUTING.md
  README.md
  screenshots/gplay/debug/com.nextcloud.client.CommunityActivityIT_open.png
  src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  src/main/res/layout/community_layout.xml
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#9719 Clear DNS cache on network changes
  src/main/java/com/owncloud/android/utils/ReceiversHelper.java
Labels: 2. to review

#9651 Use capability in SearchRemoteOperation
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentProviderClientIT.java
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
  src/main/java/com/owncloud/android/ui/asynctasks/FetchRemoteFileTask.java
  src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#9721 workflows: Use temurin JDK instead of adopt
  .github/workflows/analysis.yml
  .github/workflows/assembleFlavors.yml
  .github/workflows/check.yml
  .github/workflows/detectSnapshot.yml
  .github/workflows/qa.yml
  .github/workflows/screenShotTest.yml
Labels: 2. to review

#9722 Bump versons for 3.19.0 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30190051.txt
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#9723 Bump version to 3.20.0 on master
  build.gradle
Labels: 2. to review

#9729 Add tests
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentIT_testRecentlyModified_NoResults.png
  screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentIT_testRecentlyModified_Results.png
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentIT.kt
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#9737 Bump versions for fastlane and plugins
  Gemfile.lock
Labels: 2. to review, backport-request

#9742 Run analysis workflow on push too
  .github/workflows/analysis.yml
Labels: 2. to review, backport-request

#9718 Fix minor issues with recently modified view
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  src/main/res/menu/partial_drawer_entries.xml
  src/main/res/values/setup.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#9758 Analysis: fix checkout and commit generation
  .github/workflows/analysis.yml
  scripts/analysis/findbugs-up.rb
  scripts/analysis/lint-up.rb
Labels: 2. to review

#9759 [stable-3.19] Analysis: fix checkout and commit generation
  .github/workflows/analysis.yml
  scripts/analysis/findbugs-results.txt
  scripts/analysis/findbugs-up.rb
  scripts/analysis/lint-up.rb
Labels: 2. to review

#9726 Make PendingIntents immutable
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.java
  src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  src/main/java/com/nextcloud/client/media/PlayerService.kt
  src/main/java/com/nextcloud/client/notifications/AppNotificationManagerImpl.kt
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
Labels: 2. to review, backport-request

#9751 Fix some crashes and weird behaviours when clearing data
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.kt
Labels: 2. to review, backport-request

#9764 [stable-3.19] Make PendingIntents immutable
  scripts/analysis/lint-results.txt
  src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.java
  src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  src/main/java/com/nextcloud/client/media/PlayerService.kt
  src/main/java/com/nextcloud/client/notifications/AppNotificationManagerImpl.kt
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/files/services/FileUploader.java
  src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
Labels: 2. to review

#9760 PassCodeActivity: enable cancel button when re-created in confirmation step
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
Labels: 2. to review

#9761 Improve freezes in local files screens when folder contains many files
  scripts/analysis/lint-results.txt
  src/androidTest/java/com/owncloud/android/util/TestSorting.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/interfaces/LocalFileListFragmentInterface.java
  src/main/java/com/owncloud/android/utils/FileSortOrder.java
  src/main/java/com/owncloud/android/utils/FileSortOrder.kt
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByDate.kt
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.java
  src/main/java/com/owncloud/android/utils/FileSortOrderByName.kt
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.java
  src/main/java/com/owncloud/android/utils/FileSortOrderBySize.kt
  src/main/java/third_parties/daveKoeller/AlphanumComparator.java
Labels: 2. to review

#9743 Fix crashes and double loading in GalleryFragment when changing dark theme
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 2. to review, backport-request

#9768 Bump versions for 3.19 RC2
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30190052.txt
Labels: 2. to review

#9769 Add changelog for 3.19.0 RC2
  CHANGELOG.md
Labels: 2. to review

#9770 i18n: Change to a capital letter
  src/main/res/values/strings.xml
Labels: backport-request, i18n

#9776 OCFileListFragment: set title when attached to activity
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review, backport-request
