Repository nextcloud/android, pull requests merged in 2022-10, with the labels that each got.

#10795 Close FOS
  app/src/main/java/com/owncloud/android/ui/asynctasks/PrintAsyncTask.java
Labels: 2. to review

#10719 Dashboard
  app/screenshots/gplay/debug/com.nextcloud.ui.BitmapIT_glideSVG.png
  app/screenshots/gplay/debug/com.nextcloud.ui.BitmapIT_roundBitmap.png
  app/src/androidTest/java/com/nextcloud/ui/BitmapIT.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/client/network/ClientFactoryImpl.java
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/java/com/nextcloud/client/preferences/PreferencesModule.java
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetConfigurationActivity.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetConfigurationInterface.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetProvider.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetService.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetUpdater.kt
  app/src/main/java/com/nextcloud/client/widget/WidgetConfiguration.kt
  app/src/main/java/com/nextcloud/client/widget/WidgetRepository.kt
  app/src/main/java/com/nextcloud/ui/ChooseAccountDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/EmptyRecyclerView.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/DashboardWidgetListAdapter.kt
  app/src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/UserListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/WidgetListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/dialog/AccountChooserInterface.kt
  app/src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  app/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupListAdapter.kt
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/java/com/owncloud/android/utils/svg/SvgDecoder.java
  app/src/main/java/com/owncloud/android/utils/svg/SvgDrawableTranscoder.java
  app/src/main/java/com/owncloud/android/utils/svg/SvgSoftwareLayerSetter.java
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_dashboard.xml
  app/src/main/res/layout/dashboard_widget.xml
  app/src/main/res/layout/dashboard_widget_configuration_layout.xml
  app/src/main/res/layout/widget_item.xml
  app/src/main/res/layout/widget_item_load_more.xml
  app/src/main/res/layout/widget_list_item.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/dashboard_widget_info.xml
  app/src/test/java/com/nextcloud/client/preferences/TestAppPreferences.java
  app/src/test/java/com/owncloud/android/ui/adapter/UserListAdapterTest.java
  drawable_resources/dashboard.svg
Labels: 2. to review

#10737 Upload in background
  app/src/androidTest/java/com/owncloud/android/UploadIT.java
  app/src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
  app/src/androidTest/java/com/owncloud/android/files/services/FileUploadWorkerIT.kt
  app/src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  app/src/androidTest/java/com/owncloud/android/files/services/LegacyFileUploaderIT.kt
  app/src/androidTest/java/com/owncloud/android/operations/RemoveFileOperationIT.java
  app/src/main/java/com/nextcloud/client/di/AppComponent.java
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/nextcloud/client/utils/FileUploaderDelegate.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  app/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
  app/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  app/src/main/java/com/owncloud/android/utils/FilesUploadHelper.kt
  app/src/main/java/com/owncloud/android/utils/ReceiversHelper.java
  app/src/test/java/com/nextcloud/client/jobs/BackgroundJobFactoryTest.kt
Labels: 2. to review

#10797 Bump to SDK31
  app/build.gradle
Labels: 2. to review

#10816 stable-3.22: Remove duplicate strings caused by bad transifex sync
  app/src/main/res/values/strings.xml
Labels: 2. to review

#10819 ThumbnailsCacheManager: null out cache when clearing it
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 2. to review

#10823 stable-3.22: Fix strings before release
  app/src/main/res/values-de-rDE/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: 2. to review

#10814 Bumps on master after 3.22 branched out
  .drone.yml
  app/build.gradle
Labels: 2. to review

#10824 Add changelog for 3.22.0
  CHANGELOG.md
Labels: 2. to review

#10829 Restore OCFileListGridImageViewHolder
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridImageViewHolder.kt
  app/src/main/res/layout/grid_image.xml
  app/src/main/res/values/dims.xml
Labels: 2. to review, backport-request

#10834 Fix crash in GalleryFragment when menu button is double-tapped
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 2. to review, backport-request

#10832 Add missing injector for SslUntrustedCertDialog
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
Labels: 2. to review, backport-request

#10831 Fix pending intent mutability for widget
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetUpdater.kt
Labels: 2. to review, backport-request

#10849 Bump to 3.22.1 to fix crashes in 3.22.0
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30220190.txt
Labels: 2. to review

#10860 Add changelog for 3.22.1
  CHANGELOG.md
Labels: 2. to review

#10877 SslUntrustedCertDialog: fix inflation to avoid NPE and add test to ensure it doesn't happen again
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testSslUntrustedCertDialog.png
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java
Labels: 2. to review, backport-request

#10890 Minor updates to README for Windows syntax for logcat instructions.
  README.md
Labels: hacktoberfest-accepted

#10883 Fix creation and result logic for StoragePermissionDialogFragment
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testStoragePermissionDialog.png
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/main/java/com/owncloud/android/ui/dialog/StoragePermissionDialogFragment.kt
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
Labels: 2. to review, backport-request

#10909 Add changelog for 3.22.2
  CHANGELOG.md
Labels: 2. to review

#10914 Preserve local file behaviour when uploading files with new upload worker
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/utils/FilesUploadHelper.kt
Labels: 2. to review, backport-request

#10913 Prevent NPE if gallery search is triggered without a container activity
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 2. to review, backport-request

#10924 PermissionUtil: ensure fragment result is listened to on activity thread
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
Labels: 2. to review, backport-request

#10925 Fix login colors in NC25
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 2. to review, backport-request

#10931 Bump for 3.22.3 RC1
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30220351.txt
Labels: 2. to review

#10946 Optimizations for uploads
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/utils/FilesUploadHelper.kt
Labels: 2. to review, backport-request

#10962 Fix keyboard opening on dialogs causing squished dialogs in Material3
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  app/src/main/java/com/owncloud/android/ui/dialog/NoteDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/RenamePublicShareDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  app/src/main/java/com/owncloud/android/utils/KeyboardUtils.kt
Labels: 2. to review, backport-request

#10952 Bump to 3.22.3 RC2
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30220352.txt
Labels: 2. to review

#10964 Bump library to 2.12.1 rc1
  build.gradle
Labels: 2. to review
