Repository nextcloud/android, pull requests merged in 2022-04, with the labels that each got.

#10042 Correct scan permission handling
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
Labels: 2. to review, backport-request

#10043 [stable-3.20] Correct scan permission handling
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
Labels: 2. to review

#10015 Optimize loading time for Shared view
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverter.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt
  app/src/test/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverterTest.kt
Labels: 2. to review

#10007 Use remoteId to properly fetch streaming video url
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review

#10049 AndroidManifest: set camera2 feature to not required
  app/src/main/AndroidManifest.xml
Labels: 2. to review, backport-request

#10034 Better approach for avoiding state loss in FileDetailFragment
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: 2. to review, backport-request

#10059 Do not use ExceptionHandler on debug builds
  app/src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review

#10051 Don't include document scanner in FDroid version
  app/build.gradle
  app/src/generic/AndroidManifest.xml
  app/src/generic/java/com/owncloud/android/ui/activity/AppScanActivity.kt
  app/src/gplay/java/com/owncloud/android/ui/activity/AppScanActivity.kt
  app/src/huawei/java/com/owncloud/android/ui.activity/HuaweiCommunityActivity.kt
  app/src/huawei/java/com/owncloud/android/ui/activity/AppScanActivity.kt
  app/src/huawei/java/com/owncloud/android/ui/activity/HuaweiCommunityActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/qa/java/com/owncloud/android/ui/activity/AppScanActivity.kt
  app/src/versionDev/java/com/owncloud/android/ui/activity/AppScanActivity.kt
  build.gradle
Labels: 2. to review, backport-request

#10062 Bump versions for 3.20.0 RC2
  app/build.gradle
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30200052.txt
Labels: 2. to review

#10063 Add changelog for 3.20.0 RC2
  CHANGELOG.md
Labels: 2. to review

#10060 Let us no longer create java files
  .github/workflows/detectNewJavaFiles.yml
  scripts/analysis/detectNewJavaFiles.sh
Labels: 2. to review

#9985 Fastscroll for all lists
  app/build.gradle
  app/src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
  app/src/main/java/com/owncloud/android/ui/EmptyRecyclerView.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/interfaces/OCFileListFragmentInterface.java
  app/src/main/java/com/owncloud/android/utils/FileSortOrder.kt
  app/src/main/res/layout/list_fragment.xml
  scripts/analysis/findbugs-results.txt
Labels: 1. developing

#10070 Fix trashbin navigation
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#10074 Replace equals with == on enums
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/UnshareOperation.java
  app/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  app/src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
  scripts/analysis/findbugs-results.txt
Labels: 2. to review

#10083 [stable-3.20] Fastscroll for all lists
  app/build.gradle
  app/src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
  app/src/main/java/com/owncloud/android/ui/EmptyRecyclerView.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/interfaces/OCFileListFragmentInterface.java
  app/src/main/java/com/owncloud/android/utils/FileSortOrder.kt
  app/src/main/res/layout/list_fragment.xml
  scripts/analysis/findbugs-results.txt
Labels: 2. to review

#10050 Group photos as timeline by month
  app/src/main/java/com/owncloud/android/datamodel/GalleryItems.kt
  app/src/main/java/com/owncloud/android/ui/adapter/CommonOCFileListAdapterInterface.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryAdapter.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryHeaderViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ListGridItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListFooterViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListHeaderViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/asynctasks/GallerySearchTask.java
  app/src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListSearchAsyncTask.kt
  app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt
  app/src/main/java/com/owncloud/android/ui/interfaces/OCFileListFragmentInterface.java
  app/src/main/java/com/owncloud/android/utils/DataHolderUtil.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/res/layout/gallery_header.xml
  app/src/test/java/com/owncloud/android/ui/adapter/GalleryAdapterTest.kt
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  spotbugs-filter.xml
Labels: 2. to review

#10097 [stable-3.20] Optimize load time for Shared view
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverter.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt
  app/src/test/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverterTest.kt
  build.gradle
Labels: 2. to review

#10098 [stable-3.20] Group photos as timeline by month
  app/src/main/java/com/owncloud/android/datamodel/GalleryItems.kt
  app/src/main/java/com/owncloud/android/ui/adapter/CommonOCFileListAdapterInterface.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryAdapter.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryHeaderViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ListGridItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListFooterViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListHeaderViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/asynctasks/GallerySearchTask.java
  app/src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListSearchAsyncTask.kt
  app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt
  app/src/main/java/com/owncloud/android/ui/interfaces/OCFileListFragmentInterface.java
  app/src/main/java/com/owncloud/android/utils/DataHolderUtil.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/res/layout/gallery_header.xml
  app/src/test/java/com/owncloud/android/ui/adapter/GalleryAdapterTest.kt
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  spotbugs-filter.xml
Labels: 2. to review

#10112 Fix LoginIT for server master
  app/src/androidTest/java/com/owncloud/android/ui/LoginIT.java
  app/src/androidTest/java/com/owncloud/android/ui/LoginIT.kt
Labels: 2. to review

#10113 Run unit tests in GH actions
  .drone.yml
  .github/workflows/unit-tests.yml
  app/build.gradle
  scripts/runCombinedTest.sh
Labels: 2. to review

#10014 Spotbugs improvements
  .github/workflows/analysis.yml
  .gitignore
  app/build.gradle
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/findbugs-results.txt
  scripts/analysis/findbugs-up.rb
  scripts/analysis/spotbugs-up.rb
  scripts/analysis/spotbugsComparison.py
  scripts/analysis/spotbugsSummary.py
Labels: 2. to review

#10122 Fixes for tests due changes in Activity constructor in library
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
  app/src/test/java/com/owncloud/android/ui/activities/ActivitiesPresenterTest.java
Labels: 2. to review

#10080 Parallel thumbnail fetching
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#10117 Screenshot tests reliability improvements
  app/src/androidTest/java/com/nextcloud/client/ActivitiesActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/activity/PassCodeActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragmentIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinActivityIT.kt
Labels: 2. to review

#10129 build: Disable LeakCanary unless manually activated with a property
  app/build.gradle
Labels: 2. to review, backport-request

#10131 [stable-3.20] build: Disable LeakCanary unless manually activated with a property
  app/build.gradle
Labels: 2. to review

#10128 Fix expiration date picker layout when rotating screen
  app/src/main/java/com/owncloud/android/ui/dialog/ExpirationDatePickerDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
Labels: 2. to review, backport-request
