Repository nextcloud/android, pull requests merged in 2022-02, with the labels that each got.

#9794 Bump versions for 3.19.0 final
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30190090.txt
Labels: 2. to review

#9796 Add changelog for 3.19.0
  CHANGELOG.md
Labels: 2. to review

#9801 Update sorting tests
  src/androidTest/java/com/owncloud/android/util/TestSorting.java
  src/test/java/com/nextcloud/client/utils/NaturalSortTest.kt
  src/test/java/com/nextcloud/client/utils/OCFileSortTest.kt
Labels: 2. to review

#9820 Update drone server image
  .drone.yml
Labels: 2. to review

#9805 High-res thumbnails
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/res/values-sw600dp/dims.xml
Labels: 2. to review

#9083 remove gplay.gradle, use gplayImplementation instead
  build.gradle
  gplay.gradle
  scripts/analysis/lint-up.rb
Labels: 2. to review

#9821 FileContentProvider: fix crash on certain upgrades
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 2. to review

#9808 resuming TextEditor after splitting screens works now again
  src/main/AndroidManifest.xml
Labels: 2. to review

#9812 Use 512px for avatar
  src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  src/main/java/com/owncloud/android/ui/AvatarGroupLayout.java
  src/main/res/values/dims.xml
Labels: 2. to review

#9822 ConflictsResolveActivity: Add log messages when dialog can't be created
  src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
Labels: 2. to review

#9791 FileActivity: fix crash on share operations when FileDetailFragment is second fragment
  src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#9823 Chore: replace `com.nhaarman.mockitokotlin2` with `org.mockito.kotlin`
  build.gradle
  src/androidTest/java/com/nextcloud/client/files/DeepLinkHandlerTest.kt
  src/androidTest/java/com/nextcloud/client/integrations/deck/DeckApiTest.kt
  src/androidTest/java/com/nextcloud/client/jobs/BackgroundJobManagerTest.kt
  src/androidTest/java/com/nextcloud/client/migrations/MigrationsDbTest.kt
  src/androidTest/java/com/nextcloud/client/migrations/MigrationsManagerTest.kt
  src/androidTest/java/com/owncloud/android/datamodel/ContentResolverHelperTest.kt
  src/test/java/com/nextcloud/client/core/ManualAsyncRunnerTest.kt
  src/test/java/com/nextcloud/client/core/TaskTest.kt
  src/test/java/com/nextcloud/client/core/ThreadPoolAsyncRunnerTest.kt
  src/test/java/com/nextcloud/client/device/TestPowerManagementService.kt
  src/test/java/com/nextcloud/client/etm/TestEtmViewModel.kt
  src/test/java/com/nextcloud/client/jobs/BackgroundJobFactoryTest.kt
  src/test/java/com/nextcloud/client/jobs/ContentObserverWorkTest.kt
  src/test/java/com/nextcloud/client/logger/LoggerTest.kt
  src/test/java/com/nextcloud/client/logger/ui/AsyncFilterTest.kt
  src/test/java/com/nextcloud/client/logger/ui/LogsViewModelTest.kt
  src/test/java/com/nextcloud/client/media/AudioFocusManagerTest.kt
  src/test/java/com/nextcloud/client/media/PlayerStateMachineTest.kt
  src/test/java/com/nextcloud/client/mixins/MixinRegistryTest.kt
  src/test/java/com/nextcloud/client/mixins/SessionMixinTest.kt
  src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
  src/test/java/com/nextcloud/client/onboarding/OnboardingServiceTest.kt
  src/test/java/com/owncloud/android/ui/db/OCUploadComparatorTest.kt
Labels: 2. to review

#9208 Add RetryTestRule to DrawerActivityIT
  src/androidTest/java/com/owncloud/android/ui/activity/DrawerActivityIT.java
Labels: 2. to review

#9736 Make use of upload and creation timestamp
  src/androidTest/java/com/owncloud/android/UploadIT.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
Labels: 2. to review

#9816 Improve PIN lockout handling
  src/main/java/com/nextcloud/client/core/Clock.kt
  src/main/java/com/nextcloud/client/core/ClockImpl.kt
  src/main/java/com/nextcloud/client/di/AppModule.java
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  src/main/java/com/owncloud/android/authentication/PassCodeManager.java
  src/main/java/com/owncloud/android/authentication/PassCodeManager.kt
  src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
Labels: 1. developing, backport-request

#9806 Fallback pdf viewer
  screenshots/gplay/debug/com.owncloud.android.ui.preview.PreviewBitmapScreenshotIT_showBitmap.png
  screenshots/gplay/debug/com.owncloud.android.ui.preview.pdf.PreviewPdfFragmentScreenshotIT_showPdf.png
  src/androidTest/assets/test.pdf
  src/androidTest/java/com/owncloud/android/ui/preview/PreviewBitmapScreenshotIT.kt
  src/androidTest/java/com/owncloud/android/ui/preview/pdf/PreviewPdfFragmentScreenshotIT.kt
  src/main/AndroidManifest.xml
  src/main/java/com/nextcloud/client/di/ComponentsModule.java
  src/main/java/com/nextcloud/client/di/ViewModelModule.kt
  src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/java/com/owncloud/android/ui/preview/PreviewBitmapActivity.kt
  src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfAdapter.kt
  src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfFragment.kt
  src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfViewModel.kt
  src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  src/main/res/layout/activity_preview_bitmap.xml
  src/main/res/layout/preview_pdf_fragment.xml
  src/main/res/layout/preview_pdf_page_item.xml
  src/main/res/values-v27/styles.xml
  src/main/res/values/colors.xml
  src/main/res/values/strings.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#9783 Enhance media tab
  scripts/analysis/lint-results.txt
  src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/adapter/OCFileListAdapterIT.kt
  src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/GallerySearchTask.java
  src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/interfaces/OCFileListFragmentInterface.java
  src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  src/main/res/layout/grid_image.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#9717 Scan doc
  build.gradle
  drawable_resources/ic_scan_document.svg
  screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testBottomSheet.png
  src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  src/main/AndroidManifest.xml
  src/main/java/com/owncloud/android/ui/activity/AppScanActivity.kt
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetActions.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  src/main/res/drawable/ic_scan_document.xml
  src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
  src/main/res/values/strings.xml
Labels: 2. to review

#9858 Fix UX issues with toolbar in preview media fragment when using the "share" option
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 2. to review

#9862 Fix LeakedCloseableViolations in getScaledBitmap
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
Labels: 2. to review

#9859 Misc fixes for video player
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
  src/main/res/drawable/ripple.xml
  src/main/res/layout/activity_preview_video.xml
  src/main/res/layout/exo_player_control_view.xml
  src/main/res/values/styles.xml
Labels: 2. to review, backport-request

#9872 [stable-3.19] Misc fixes for video player
  scripts/analysis/findbugs-results.txt
  scripts/analysis/lint-results.txt
  src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.java
  src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
  src/main/res/drawable/ripple.xml
  src/main/res/layout/activity_preview_video.xml
  src/main/res/layout/exo_player_control_view.xml
  src/main/res/values/styles.xml
Labels: 2. to review

#9877 Use androidx for espresso-intents
  build.gradle
Labels: 2. to review

#9866 Migrate from Parceler to kotlin-parcelize
  build.gradle
  src/androidTest/java/com/owncloud/android/ui/activity/UserInfoActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  src/gplay/java/com/owncloud/android/utils/PushUtils.java
  src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.java
  src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.kt
  src/main/java/com/owncloud/android/datamodel/ExternalLinksProvider.java
  src/main/java/com/owncloud/android/datamodel/SignatureVerification.java
  src/main/java/com/owncloud/android/datamodel/SignatureVerification.kt
  src/main/java/com/owncloud/android/datamodel/Template.java
  src/main/java/com/owncloud/android/datamodel/Template.kt
  src/main/java/com/owncloud/android/files/FetchTemplateOperation.java
  src/main/java/com/owncloud/android/files/FileMenuFilter.java
  src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  src/main/java/com/owncloud/android/ui/activity/UserInfoActivity.java
  src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  src/main/java/com/owncloud/android/ui/adapter/TemplateAdapter.java
  src/main/java/com/owncloud/android/ui/asynctasks/GallerySearchTask.java
  src/main/java/com/owncloud/android/ui/asynctasks/TextEditorLoadUrlTask.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.java
  src/main/java/com/owncloud/android/ui/events/SearchEvent.java
  src/main/java/com/owncloud/android/ui/events/SearchEvent.kt
  src/main/java/com/owncloud/android/ui/events/SyncEventFinished.kt
  src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/SearchType.kt
  src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 2. to review

#9880 Fix LoggerImpl to also log throwable
  src/main/java/com/nextcloud/client/logger/LoggerImpl.kt
Labels: 2. to review

#9879 Bump versions for 3.19.1 RC1
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30190151.txt
Labels: 2. to review

#8805 Add stacktrace directly to github issue
  src/main/java/com/nextcloud/client/errorhandling/ExceptionHandler.kt
  src/main/java/com/nextcloud/client/errorhandling/ShowErrorActivity.kt
  src/main/java/com/owncloud/android/MainApp.java
  src/main/java/com/owncloud/android/utils/StringUtils.java
  src/main/res/values/setup.xml
Labels: 2. to review

#9886 Add changelog for 3.19.1 RC1
  CHANGELOG.md
Labels: 2. to review

#9890 remove mail notification on failure during CI, as this is shown in GitHub anyways
  .drone.yml
Labels: 2. to review

#9888 Remove third party licenses for libs we don't use (anymore)
  THIRD_PARTY.txt
  third_party/touch-image-view/LICENSE
Labels: 2. to review

#9895 Revert "Bump exoplayer from 2.16.1 to 2.17.0"
  build.gradle
Labels: 2. to review

#9893 remoteId not needed when deleting a file
  scripts/analysis/findbugs-results.txt
  src/androidTest/java/com/owncloud/android/FileIT.java
  src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentResolverIT.kt
  src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  src/androidTest/java/com/owncloud/android/ui/adapter/OCFileListAdapterIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/BackupListFragmentIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
  src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  src/main/java/com/owncloud/android/datamodel/OCFile.java
  src/main/java/com/owncloud/android/providers/FileContentProvider.java
Labels: 2. to review

#9894 Remove not needed toString() call
  scripts/analysis/findbugs-results.txt
  src/main/java/com/owncloud/android/db/OCUpload.java
  src/main/java/com/owncloud/android/files/services/FileDownloader.java
  src/main/java/com/owncloud/android/operations/UpdateOCVersionOperation.java
  src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#9902 OCFile: fix NPE in getLocalId when remoteID is null
  src/main/java/com/owncloud/android/datamodel/OCFile.java
Labels: 2. to review
