Repository nextcloud/android, pull requests merged in 2022-11, with the labels that each got.

#10965 Add changelog for 3.22.3 RC2
  CHANGELOG.md
Labels: 2. to review

#10967 Show warning when trying to access an encrypted folder, when not yet setup
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/res/values/strings.xml
Labels: 2. to review

#10961 use existing method via eventbus to encrypt folder
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#10966 Show cancel button when entering mnemonic
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
Labels: 2. to review, backport-request

#10976 Fix webauthn crashes due to PendingIntent mutability
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: 2. to review, backport-request

#10974 List fragments: Add empty list as a child of SwipeRefreshLayout, not outside it.
  app/src/main/res/layout/list_fragment.xml
Labels: 2. to review, backport-request

#10978 Bump for 3.22.3 final
  app/build.gradle
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30220390.txt
Labels: 2. to review

#10984 Add changelog for 3.22.3
  CHANGELOG.md
Labels: 2. to review

#10985 fastlane: add skip_upload_apk to play store config
  fastlane/Fastfile
Labels: 2. to review

#10989 Fixed folder content visibility
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 2. to review

#11001 Use material 3 style for SSO dialog
  app/src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
  app/src/main/java/com/owncloud/android/utils/theme/ViewThemeUtils.kt
  app/src/main/res/layout/activity_sso_grant_permission.xml
  app/src/main/res/layout/dialog_sso_grant_permission.xml
Labels: 2. to review

#11006 Give groupfolders priority when choosing icon for folder
  app/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
Labels: 2. to review

#11015 Bump compileSDK to 32
  app/build.gradle
Labels: 2. to review

#11033 File list "jumps" after scrolling when an asynchronous operation finishes
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: bug, 2. to review, ui/ux

#10977 Setup Room database
  app/build.gradle
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/65.json
  app/src/androidTest/java/com/owncloud/android/providers/DocumentsProviderUtils.kt
  app/src/androidTest/java/com/owncloud/android/providers/DocumentsStorageProviderIT.kt
  app/src/main/java/com/nextcloud/client/database/DatabaseModule.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/ArbitraryDataEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/CapabilityEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/ExternalLinkEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/FileEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/FilesystemEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/ShareEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/SyncedFolderEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/UploadEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/VirtualEntity.kt
  app/src/main/java/com/nextcloud/client/database/migrations/LegacyMigration.kt
  app/src/main/java/com/nextcloud/client/database/migrations/LegacyMigrationHelper.java
  app/src/main/java/com/nextcloud/client/database/migrations/RoomMigration.kt
  app/src/main/java/com/nextcloud/client/di/AppComponent.java
  app/src/main/java/com/nextcloud/client/di/AppModule.java
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/providers/FileContentProvider.java
  build.gradle
  scripts/analysis/lint-results.txt
  spotbugs-filter.xml
Labels: 2. to review, technical debt

#11037 Only show "set encrypted" if folder is empty and has no empty files/folder in it
  app/src/androidTest/java/com/owncloud/android/files/FileMenuFilterIT.kt
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
Labels: 2. to review

#11046 OCFileListFragment: also reset search type when resetting search event
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 2. to review

#11039 FileDisplayActivity: fix restoring selected menu item when resuming
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review

#11040 Fix toolbar home icon being arrow in places where it should be hamburger menu
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/utils/theme/FilesSpecificViewThemeUtils.kt
Labels: 2. to review

#10996 Cache walled check for 10 minutes
  app/src/androidTest/java/com/nextcloud/client/network/ConnectivityServiceImplIT.kt
  app/src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  app/src/main/java/com/nextcloud/client/network/NetworkModule.java
  app/src/main/java/com/nextcloud/client/network/WalledCheckCache.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/files/BootupBroadcastReceiver.java
  app/src/main/java/com/owncloud/android/utils/ReceiversHelper.java
  app/src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 2. to review

#11041 Fix storage permission loop when permission denied, and remember permission asked
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
Labels: 2. to review

#11008 Redesign file actions menu as a BottomSheet
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testFileActionsBottomSheet.png
  app/src/androidTest/java/com/owncloud/android/files/FileMenuFilterIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/debug/java/com/nextcloud/client/TestActivity.kt
  app/src/main/java/com/nextcloud/android/files/FileLockingMenuCustomization.kt
  app/src/main/java/com/nextcloud/android/files/ThemedPopupMenu.kt
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/client/di/ViewModelModule.kt
  app/src/main/java/com/nextcloud/ui/fileactions/FileAction.kt
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsBottomSheet.kt
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsViewModel.kt
  app/src/main/java/com/nextcloud/utils/EditorUtils.kt
  app/src/main/java/com/nextcloud/utils/MenuUtils.kt
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/asynctasks/TextEditorLoadUrlTask.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfFragment.kt
  app/src/main/res/drawable/file_multiple.xml
  app/src/main/res/drawable/ic_decrypt.xml
  app/src/main/res/drawable/ic_encrypt.xml
  app/src/main/res/drawable/ic_export.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_move.xml
  app/src/main/res/drawable/ic_rename.xml
  app/src/main/res/drawable/ic_wallpaper.xml
  app/src/main/res/layout/file_actions_bottom_sheet.xml
  app/src/main/res/layout/file_actions_bottom_sheet_item.xml
  app/src/main/res/layout/file_thumbnail.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/menu/custom_menu_placeholder.xml
  app/src/main/res/menu/fragment_file_detail.xml
  app/src/main/res/menu/item_file.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 2. to review

#11051 chore: Remove unused legacy migration code
  app/src/main/java/com/nextcloud/client/database/DatabaseModule.kt
  app/src/main/java/com/nextcloud/client/database/migrations/LegacyMigration.kt
  app/src/main/java/com/nextcloud/client/database/migrations/LegacyMigrationHelper.java
Labels: 2. to review, technical debt

#11052 prohibit share of an encrypted folder
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
Labels: 2. to review

#11053 Bump for 3.23.0 RC1
  app/build.gradle
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30230051.txt
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 2. to review

#11056 Add changelog for 3.23.0 RC1
  CHANGELOG.md
Labels: 2. to review

#11050 Use Room DAO instead of ContentProvider for arbitrary data table access
  app/src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java
  app/src/androidTest/java/com/nextcloud/client/SettingsActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/datamodel/ArbitraryDataProviderIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/debug/java/com/nextcloud/client/TestActivity.kt
  app/src/gplay/java/com/owncloud/android/utils/PushUtils.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  app/src/main/java/com/nextcloud/client/database/DatabaseModule.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/dao/ArbitraryDataDao.kt
  app/src/main/java/com/nextcloud/client/database/migrations/LegacyMigrationHelper.java
  app/src/main/java/com/nextcloud/client/di/AppModule.java
  app/src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt
  app/src/main/java/com/nextcloud/client/jobs/ContactsBackupWork.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/ArbitraryDataProvider.java
  app/src/main/java/com/owncloud/android/datamodel/ArbitraryDataProvider.kt
  app/src/main/java/com/owncloud/android/datamodel/ArbitraryDataProviderImpl.java
  app/src/main/java/com/owncloud/android/datamodel/ArbitraryDataSet.kt
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/providers/FileContentProvider.java
  app/src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 2. to review, technical debt

#10968 Check if e2e is available in DocumentsStorageProvider
  app/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 2. to review

#11059 Allow Pin to Home with file actions bottom sheet
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/ui/fileactions/FileAction.kt
  app/src/main/java/com/nextcloud/utils/ShortcutUtil.kt
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/res/drawable/add_to_home_screen.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: 2. to review

#11074 CalendarBackupWork: upload to configured account, not current account
  app/src/main/java/com/nextcloud/client/jobs/CalendarBackupWork.kt
Labels: 2. to review, backport-request

#11068 FileDisplayActivity: fix drawer menu item when browsing back from favorite folder
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 2. to review, backport-request

#11067 GalleryFragment: fix crash when scrolling slowly until the end of the list
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 2. to review, backport-request

#10928 Fix issues with calendar exporting
  app/src/main/java/com/nextcloud/client/jobs/CalendarBackupWork.kt
  app/src/main/java/third_parties/sufficientlysecure/AndroidCalendar.java
  app/src/main/java/third_parties/sufficientlysecure/ProcessVEvent.java
  app/src/main/java/third_parties/sufficientlysecure/SaveCalendar.java
Labels: 2. to review, backport-request

#11084 Bump for 3.23.0 RC2
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30230052.txt
Labels: 2. to review

#11031 E2e ux
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/66.json
  app/screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open.png
  app/screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error.png
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/CapabilityEntity.kt
  app/src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SetupEncryptionActivity.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/preferences.xml
Labels: 2. to review

#11097 i18n: Change name of encryption
  app/src/main/res/values/strings.xml
Labels: backport-request, i18n

#11105 Update screenshot test results for E2E strings
  app/screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open.png
  app/screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error.png
Labels: 2. to review

#11073 Disable StrictMode by default
  CONTRIBUTING.md
  app/build.gradle
  app/src/main/java/com/owncloud/android/MainApp.java
Labels: 2. to review, backport-request, technical debt

#11089 Video preview: use fullscreen dialog for video instead of new activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewVideoActivity.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFullscreenDialog.kt
  app/src/main/res/layout/dialog_preview_video.xml
  app/src/main/res/layout/exo_player_control_view.xml
  app/src/main/res/layout/fragment_preview_media.xml
  app/src/main/res/values/styles.xml
Labels: 2. to review

#11075 Bump targetSdk to 32
  app/build.gradle
Labels: 2. to review

#11087 Add changelog for 3.23.0 RC2
  CHANGELOG.md
Labels: 2. to review
