Repository nextcloud/android, pull requests merged in 2022-09, with the labels that each got.

#10693 Revert "Bump targetSdkVersion to 31"
  app/build.gradle
Labels: 2. to review, high, backport-request

#10694 Bump for 3.22.2 patch version
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30210290.txt
Labels: 2. to review

#10688 Avoid full folder refresh during onBrowseUp
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 2. to review, performance

#10703 Restart account creation with AuthenticatorActivity, which helps to add account in restricted profiles, e.g. MDM or Samsung second users
  app/src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
Labels: 2. to review

#10706 PreviewImageFragment: prevent crash when redrawing menu after file deletion
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
Labels: 2. to review

#10705 AndroidManifest: disable backup&restore
  app/src/main/AndroidManifest.xml
Labels: 2. to review

#10745 Add monochrome icon
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
Labels: 2. to review

#10760 TextDrawable: handle spaces at start/end of displayNames
  app/src/main/java/com/owncloud/android/ui/TextDrawable.java
  app/src/test/java/com/owncloud/android/ui/TextDrawableTest.kt
Labels: 2. to review
