Repository nextcloud/android, pull requests merged in 2023-11, with the labels that each got.

#12071 Convert create folder dialog to kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.kt
Labels: 3. to review

#12085 Use Material Design 3 For File Details Sharing Process Fragment
  app/src/main/java/com/nextcloud/utils/extensions/BundleExtensions.kt
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
  app/src/main/res/layout/file_details_sharing_process_fragment.xml
  app/src/main/res/values/dims.xml
Labels: 3. to review

#12121 test replacing kt with java version
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.kt
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
Labels: 2. developing, don't merge

#12123 Remove trailing comma
  .devcontainer/devcontainer.json
Labels: 3. to review

#12077 Use Material Design 3 For Setup Encryption Dialog Fragment
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testConfirmationDialogWithOneAction.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testConfirmationDialogWithThreeAction.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testConfirmationDialogWithThreeActionRTL.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testConfirmationDialogWithTwoAction.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testFileActionsBottomSheet.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testLoadingDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialogDifferentTypes_Screenshot.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialog_Screenshot.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendShareDialogTest_showDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_error.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic.png
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/main/java/com/owncloud/android/ui/dialog/LoadingDialog.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.kt
  app/src/main/res/layout/setup_encryption_dialog.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#12068 Bugfix Disable focus change via tap
  app/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  app/src/main/java/com/owncloud/android/ui/components/PassCodeEditText.kt
  app/src/main/res/layout/passcodelock.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#12118 Convert WhatsNewActivity to Kotlin
  app/src/main/java/com/nextcloud/client/onboarding/WhatsNewActivity.java
  app/src/main/java/com/nextcloud/client/onboarding/WhatsNewActivity.kt
Labels: 3. to review

#12051 test on Stable 27
  .drone.yml
Labels: 3. to review

#12131 Convert Deep Link Login Activity to Kotlin
  app/src/main/java/com/owncloud/android/authentication/DeepLinkLoginActivity.java
  app/src/main/java/com/owncloud/android/authentication/DeepLinkLoginActivity.kt
Labels: 3. to review

#12133 Convert TrashbinActivity to Kotlin
  app/src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinLocalRepository.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.java
  app/src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.java
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinContract.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinPresenter.java
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinPresenter.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinRepository.kt
Labels: 3. to review

#12132 Convert Media Folder to Kotlin
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/MediaFolder.kt
  app/src/main/java/com/owncloud/android/datamodel/MediaFolderType.kt
  app/src/main/java/com/owncloud/android/datamodel/MediaFoldersModel.java
  app/src/main/java/com/owncloud/android/datamodel/MediaFoldersModel.kt
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  app/src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.java
  app/src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
Labels: 3. to review

#12127 Fix Crash When User Tap Back Button From Add Account Page
  app/src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.kt
Labels: 3. to review

#12094 Bugfix Share Is No Longer Available After Renaming Folder
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  scripts/analysis/lint-results.txt
Labels: bug, 3. to review

#12158 Convert Rich Documents Editor Web View to Kotlin
  app/src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
  app/src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.kt
Labels: 3. to review

#12148 Convert PasscodeActivity To Kotlin, Material Design 3 Implementation
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_check.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_delete.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.PassCodeActivityIT_request.png
  app/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.kt
  app/src/main/res/layout/passcodelock.xml
Labels: 3. to review

#12106 Update M3 library, Increase target sdk to 34
  app/build.gradle
  app/src/androidTest/java/com/nextcloud/client/ActivitiesActivityIT.kt
  app/src/main/java/com/owncloud/android/ui/activity/ContactsPreferenceActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/test/java/com/nextcloud/client/core/LocalConnectionTest.kt
Labels: 3. to review

#12182 Update Styles For Material Design 3
  app/src/main/res/values/styles.xml
Labels: design, 3. to review

#12167 Convert NotificationsActivity to Kotlin
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.kt
Labels: 3. to review

#12189 Remove Unused Translation Key
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs-rCZ/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hu-rHU/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#12190 Fix GradleProperties for CI/CD
  gradle.properties
Labels: 2. developing

#12173 Convert CommunityActivity to Kotlin
  app/src/huawei/java/com/owncloud/android/ui/activity/HuaweiCommunityActivity.kt
  app/src/main/java/com/nextcloud/utils/extensions/TextViewExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/CommunityActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/CommunityActivity.kt
Labels: 3. to review

#12059 Share screen email selection from contact book
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileNone.png
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  app/src/main/res/drawable/ic_contact_book.xml
  app/src/main/res/layout/file_details_sharing_fragment.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12179 Fix SSO on applications with shared uid
  app/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
Labels: 3. to review

#12191 scrolling kills test
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/UploadIT.java
Labels: 2. developing

#12202 Build(deps): Bump com.android.tools.build:gradle from 8.1.1 to 8.1.4
  build.gradle
Labels: 3. to review, dependencies

#12194 Bugfix/Make cancelation work again for Android >= 11 via Worker
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/utils/FilesUploadHelper.kt
Labels: 4. to release

#12204 Update deprecated api calls in EditImageActivity
  app/src/main/java/com/nextcloud/client/editimage/EditImageActivity.kt
Labels: 4. to release

#12192 Fix Crash on Android 14 When Start Foreground Service
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/files/downloader/FileTransferService.kt
  app/src/main/java/com/nextcloud/client/media/PlayerService.kt
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: 4. to release
