Repository nextcloud/android, pull requests merged in 2023-12, with the labels that each got.

#12211 Use custom quota exceeded error message
  app/src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
  app/src/main/res/values/strings.xml
Labels: 4. to release

#12172 Convert ConflictsResolveActivity to Kotlin
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
Labels: 4. to release

#12213 Feature/Add cancel button to upload notification
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
Labels: enhancement, 3. to review, feature: activity and notification, feature: sync and upload

#12221 Bump AGP to 8.2.0
  app/build.gradle
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/res/values/styles.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  scripts/analysis/lint-results.txt
Labels: 3. to review, technical debt

#12228 Provide Better Feedback For Failed Uploads
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/res/values/strings.xml
Labels: 2. developing

#12207 Bugfix Mp3-and-sometimes-.md-files-assume-folder-thumbnails-on-refresh'
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 3. to review

#12162 Bugfix Search Not Working When Sharing File From Outside of the App
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/ReceiveExternalFilesAdapter.kt
  app/src/main/java/com/owncloud/android/ui/adapter/UploaderAdapter.java
  app/src/main/res/layout/receive_external_files.xml
Labels: 4. to release, backport-request

#12241 Revert "Merge pull request #12228
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/res/values/strings.xml
Labels: 2. developing

#11948 if e2e server app is disabled, do not show secure file drop
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
Labels: backport-request

#12212 Use custom quota exceeded error message in UploadList
  app/src/main/java/com/owncloud/android/db/UploadResult.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
Labels: 3. to review

#12247 Implement other interface functions regarding file upload for upload worker
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/utils/FilesUploadHelper.kt
Labels: 3. to review, backport-request

#12139 Live Photo
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/75.json
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showFiles.png
  app/src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/fragment/UnifiedSearchFragmentIT.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/FileEntity.kt
  app/src/main/java/com/nextcloud/client/media/ExoplayerListener.kt
  app/src/main/java/com/nextcloud/utils/extensions/Extensions.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/media/MediaControlView.java
  app/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/ListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/UnifiedSearchListAdapter.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/java/com/owncloud/android/ui/unifiedsearch/UnifiedSearchModel.kt
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  app/src/main/res/drawable/ic_live_photo.xml
  app/src/main/res/layout/grid_image.xml
  app/src/main/res/layout/grid_item.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/layout/preview_image_fragment.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 4. to release, backport-request

#12093 Bugfix Check Network Connection When File Item Clicked
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/androidTest/java/com/owncloud/android/UploadIT.java
  app/src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  app/src/debug/java/com/nextcloud/test/TestActivity.kt
  app/src/main/java/com/nextcloud/client/network/ConnectivityService.java
  app/src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 4. to release, backport-request

#12246 Fix: To many old notifications
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/java/com/owncloud/android/ui/notifications/NotificationUtils.java
Labels: 2. developing, backport-request

#12263 Hwsecurity bump
  build.gradle
Labels: 3. to review, backport-request

#12270 Bump to 3.27.0 RC2
  app/build.gradle
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30270052.txt
Labels: 3. to review

#12257 Fix Crash Register Broadcast
  app/src/main/java/com/nextcloud/client/device/PowerManagementServiceImpl.kt
  app/src/main/java/com/nextcloud/utils/extensions/ContextExtensions.kt
  app/src/main/java/com/owncloud/android/datamodel/ReceiverFlag.kt
  app/src/main/java/com/owncloud/android/utils/ReceiversHelper.java
  app/src/test/java/com/nextcloud/client/device/TestPowerManagementService.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#12251 Better Feedback For Failed Uploads
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/nextcloud/model/HTTPStatusCodes.kt
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12279 Bump to 3.27.0
  app/build.gradle
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30270090.txt
Labels: 3. to review

#11965 Unintended UI elements showing
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: bug, 3. to review

#12283 Fix Multi Select Crash
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 3. to review

#12209 Add Files Action to Search
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UnifiedSearchItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/UnifiedSearchListAdapter.kt
  app/src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
  app/src/main/res/layout/unified_search_item.xml
Labels: 3. to review

#12092 Bugfix After Selecting File From Search It Doesn't Open
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/FetchRemoteFileTask.java
  app/src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
Labels: 3. to review

#12286 fix(i18n): Fixed typo and changed grammar
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#12298 restore fab icon when going back
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review

#12300 Use try-with-resources for Cursor in getUploadByRemotePath
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
Labels: 3. to review, technical debt

#12307 Add AS project logo
  .idea/icon.svg
Labels: 4. to release

#12309 Fix suggestion
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: bug, 3. to review

#12278 New Grid Layout
  app/src/main/java/com/nextcloud/utils/extensions/ViewExtensions.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/ui/adapter/ListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridImageViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListGridItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListItemViewHolder.kt
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/res/layout/grid_image.xml
  app/src/main/res/layout/grid_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
Labels: design, 3. to review

#12306 Add info for background worker execution
  app/src/androidTest/java/com/nextcloud/client/jobs/BackgroundJobManagerTest.kt
  app/src/androidTest/java/com/nextcloud/client/jobs/ContactsBackupIT.kt
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/client/etm/pages/EtmBackgroundJobsFragment.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/ContentObserverWork.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/HealthStatusWork.kt
  app/src/main/java/com/nextcloud/client/jobs/JobInfo.kt
  app/src/main/java/com/nextcloud/client/jobs/JobsModule.kt
  app/src/main/java/com/nextcloud/client/jobs/TestJob.kt
  app/src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/res/layout/etm_background_job_list_item.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12315 Handle restoring fab icon from drawer view
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review

#12303 Use Only Work Manager For File Upload
  app/src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  app/src/main/java/com/nextcloud/client/documentscan/DocumentScanViewModel.kt
  app/src/main/java/com/nextcloud/client/documentscan/GeneratePdfFromImagesWork.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/owncloud/android/files/services/FileUploader.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
  app/src/main/java/com/owncloud/android/ui/helpers/UriUploader.kt
Labels: 3. to review

#12330 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#12332 Refactor Folder Picker Activity
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
Labels: 3. to review
