Repository nextcloud/android, pull requests merged in 2023-02, with the labels that each got.

#11335 Codecov config improvements
  .codecov.yml
Labels: 3. to review

#11341 fix interrupted e2e uploads
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to review

#11339 Fix shared view
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/events/FavoriteEvent.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 3. to review

#11362 Use adaptive colors for pre-login screens
  app/build.gradle
  app/screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login.png
  app/src/main/java/com/nextcloud/client/di/AppComponent.java
  app/src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  app/src/main/java/com/nextcloud/client/onboarding/WhatsNewActivity.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FeatureFragment.java
  app/src/main/java/com/owncloud/android/ui/whatsnew/ProgressIndicator.java
  app/src/main/java/com/owncloud/android/utils/theme/MaterialSchemesProvider.kt
  app/src/main/java/com/owncloud/android/utils/theme/MaterialSchemesProviderImpl.kt
  app/src/main/java/com/owncloud/android/utils/theme/ViewThemeUtils.kt
Labels: 3. to review, backport-request

#11376 [stable-3.24] Use adaptive colors for pre-login screens (#11362)
  app/build.gradle
  app/screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login.png
  app/src/main/java/com/nextcloud/client/di/AppComponent.java
  app/src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  app/src/main/java/com/nextcloud/client/onboarding/WhatsNewActivity.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FeatureFragment.java
  app/src/main/java/com/owncloud/android/ui/whatsnew/ProgressIndicator.java
  app/src/main/java/com/owncloud/android/utils/theme/MaterialSchemesProvider.kt
  app/src/main/java/com/owncloud/android/utils/theme/MaterialSchemesProviderImpl.kt
  app/src/main/java/com/owncloud/android/utils/theme/ViewThemeUtils.kt
Labels: 3. to review

#11356 Bumps for 3.24.0 final
  app/build.gradle
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30240090.txt
Labels: 3. to review

#11375 Delete scorecards-analysis.yml
  .github/workflows/scorecards-analysis.yml
Labels: 3. to review

#11379 Add changelog for 3.24.0
  CHANGELOG.md
Labels: 3. to review

#11408 Bump for 3.24.1
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30240190.txt
Labels: 3. to review

#11412 Add changelog for 3.24.1
  CHANGELOG.md
Labels: 3. to review

#11384 Improve error message when download fails due to invalid filename
  app/src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
  app/src/main/res/values/strings.xml
Labels: 3. to review

#11381 i18n: Change to capital letter
  app/src/main/res/values/strings.xml
Labels: i18n

#11411 fix: FileStorageUtils: prevent NPE when checking encryption status
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 3. to review, backport-request

#11149 mTime: use typed parameter (long) instead of String
  app/src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
Labels: 3. to review

#11417 Refactor onCreate() method by breaking it down into smaller methods
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review
