Repository nextcloud/android, pull requests merged in 2023-10, with the labels that each got.

#12024 Fix FileDetailFragmentStaticServerIT failing
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailDetailsFragment.png
  app/src/androidTest/assets/gps.jpg
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
Labels: 3. to review

#12032 Feature/use-material-design-3-for-rename-dialog
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRenameFileDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailDetailsFragment.png
  app/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
Labels: design, 3. to review

#12014 Fix softKeyboard not appearing
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/NoteDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/RenamePublicShareDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  app/src/main/java/com/owncloud/android/utils/KeyboardUtils.kt
Labels: 3. to review

#12030 fix remaining CI tests
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/androidTest/java/com/owncloud/android/UploadIT.java
  app/src/androidTest/java/com/owncloud/android/ui/LoginIT.kt
Labels: 3. to review

#12033 Use M3 for CreateFolderDialog
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testNewFolderDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesError.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailDetailsFragment.png
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.java
Labels: design, 3. to review

#12042 Use Material Design 3 for AccountRemovalConfirmationDialog
  app/src/main/java/com/owncloud/android/ui/dialog/AccountRemovalConfirmationDialog.java
Labels: 3. to review

#12048 Remove SSL Validator Dialog
  app/src/main/java/com/owncloud/android/ui/dialog/SslValidatorDialog.java
  app/src/main/res/layout/ssl_validator_layout.xml
  app/src/main/res/values/dims.xml
Labels: 3. to review

#12043 Use M3 for ChooseRichDocumentsTemplateDialogFragment
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
Labels: 3. to review

#12045 Use Material Design 3 For Expiration Date Picker Dialog
  app/src/main/java/com/owncloud/android/ui/dialog/ExpirationDatePickerDialogFragment.java
Labels: 3. to review

#12034 Use Material Design 3 for RemoveFilesDialog
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFileDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFilesDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFolderDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFoldersDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showDetailsActivitiesError.png
  app/src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java
  app/src/main/res/values/strings.xml
Labels: design, 3. to review

#12050 Use Material Design 3 for StoragePermissionDialogFragment
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testStoragePermissionDialog.png
  app/src/main/java/com/owncloud/android/ui/dialog/StoragePermissionDialogFragment.kt
  app/src/main/res/layout/storage_permission_dialog.xml
Labels: 3. to review

#12056 README: Expand "How to contribute" opener to give readers ideas
  README.md
Labels: 3. to review, meta

#12054 README: Fix link to "starter" issues
  README.md
Labels: 3. to review, meta

#12035 Use Material Design For Rename Public Share Dialog
  app/src/main/java/com/owncloud/android/ui/dialog/RenamePublicShareDialogFragment.java
Labels: design, 3. to review

#12062 CHANGELOG: Add last two production releases, fix dates, add link
  CHANGELOG.md
Labels: 3. to review, meta

#12036 Use Material Design 3 For ConflictResolve Dialog
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles.png
  app/src/main/java/com/owncloud/android/ui/dialog/ConflictsResolveDialog.java
Labels: design, 3. to review

#12044 Use Material Design 3 ChooseTemplateDialogFragment
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.kt
Labels: 3. to review

#12088 Cancel codeql.yml after re-pushing
  .github/workflows/codeql.yml
Labels: 3. to review, developer experience

#12087 Use Material Design 3 For Backup Fragment
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ContactsPreferenceActivityIT_openContactsPreference.png
  app/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.kt
  app/src/main/res/layout/backup_fragment.xml
  app/src/main/res/values/dims.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#12049 Use M3 for SyncedFolderPreferencesDialogFragment
  app/screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_testSyncedFolderDialog.png
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.kt
  app/src/main/res/layout/synced_folders_settings_layout.xml
Labels: 3. to review

#12096 Bugfix Search View Width
  app/src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
Labels: 3. to review

#12098 Bugfix Choose Storage Location UI bug 11996
  app/src/main/java/com/owncloud/android/ui/adapter/StoragePathAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/StoragePathAdapter.kt
  app/src/main/java/com/owncloud/android/ui/dialog/LocalStoragePathPickerDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/LocalStoragePathPickerDialogFragment.kt
  app/src/main/res/layout/storage_path_item.xml
Labels: bug, 3. to review, storage

#12105 Fixed outdated server condition for server version
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: bug, backport-request

#12108 Check WebView Version For Login Functionality
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/utils/WebViewUtil.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12070 Use Material Design 3 For Loading Popup
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/main/java/com/owncloud/android/ui/dialog/LoadingDialog.java
  app/src/main/java/com/owncloud/android/ui/dialog/LoadingDialog.kt
  app/src/main/res/layout/loading_dialog.xml
Labels: 3. to review

#12081 Use Material Design 3 For SyncFileNotEnoughSpaceDialogFragment
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragmentTest.java
  app/src/main/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragment.kt
Labels: 3. to review

#12110 Convert Deck Api to Kotlin
  app/src/main/java/com/nextcloud/client/integrations/deck/DeckApi.kt
  app/src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.java
  app/src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
Labels: 3. to review

#12082 Convert Java to Kotlin Indeterminate Progress Dialog
  app/src/main/java/com/owncloud/android/ui/dialog/IndeterminateProgressDialog.java
  app/src/main/java/com/owncloud/android/ui/dialog/IndeterminateProgressDialog.kt
Labels: 3. to review

#12101 Convert FragmentInjector to Kotlin
  app/src/main/java/com/nextcloud/client/di/FragmentInjector.kt
Labels: 3. to review

#12083 Convert Java to Kotlin Multiple Accounts Dialog
  app/src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.java
  app/src/main/java/com/owncloud/android/ui/dialog/MultipleAccountsDialog.kt
Labels: 3. to review

#12099 Convert SquareLoaderImageView to Kotlin
  app/src/main/java/com/nextcloud/ui/SquareLoaderImageView.kt
Labels: 3. to review

#12041 Use Material Design 3 For Confirmation Dialog
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFileDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFilesDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFolderDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRemoveFoldersDialog.png
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/dialog/ConfirmationDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/ConfirmationDialogFragment.kt
Labels: 3. to review

#12047 Use Material Design 3 share password dialog fragment
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testEnforcedPasswordDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testOptionalPasswordDialog.png
  app/src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/SharePasswordDialogFragment.kt
Labels: 3. to review

#12052 Use Material Design 3 File Downloader Notification
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.java
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.kt
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12111 Build Fix
  app/src/main/java/com/owncloud/android/files/services/FileDownloader.kt
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  app/src/main/java/com/owncloud/android/ui/dialog/ConfirmationDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragment.kt
Labels: 3. to review

#12100 Convert ActivityInjector to Kotlin
  app/src/main/java/com/nextcloud/client/di/ActivityInjector.java
  app/src/main/java/com/nextcloud/client/di/ActivityInjector.kt
Labels: 3. to review

#12058 Use Material Desing 3 For File Actions Bottom Sheet
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testFileActionsBottomSheet.png
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsBottomSheet.kt
  app/src/main/res/layout/file_actions_bottom_sheet.xml
  app/src/main/res/values/dims.xml
Labels: 3. to review

#12063 Use Material Design 3 For Send Share Dialog Bottomsheet
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendShareDialogTest_showDialog.png
  app/src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.java
  app/src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.kt
  app/src/main/res/layout/send_share_fragment.xml
  app/src/main/res/values/dims.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review

#12067 Use Material Design 3 For Gallery Bottom Sheet
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragmentBottomSheetDialog.kt
  app/src/main/res/layout/fragment_gallery_bottom_sheet.xml
Labels: 3. to review

#12114 Convert FirstRunActivity to Kotlin
  app/src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  app/src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.kt
  app/src/main/res/layout/first_run_activity.xml
Labels: 3. to review

#12064 Use Material Design 3 For Send Files Bottom Sheet
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialogDifferentTypes_Screenshot.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendFilesDialogTest_showDialog_Screenshot.png
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/owncloud/android/ui/dialog/SendFilesDialog.java
  app/src/main/java/com/owncloud/android/ui/dialog/SendFilesDialog.kt
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/res/layout/send_files_fragment.xml
Labels: 3. to review
