Repository nextcloud/android, pull requests merged in 2023-04, with the labels that each got.

#11505 fix(i18n): Adjust links to transifex
  CONTRIBUTING.md
  README.md
  app/src/main/res/values/setup.xml
Labels: 3. to review, i18n

#11321 Fix issues with Media Tab & performance improvement.
  app/src/main/java/com/owncloud/android/ui/asynctasks/GallerySearchTask.java
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 3. to review

#11402 when resuming note directly after creating, url is not working anymore, thus we need a new one
  app/src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
Labels: 3. to review

#11518 User check added when sync folder runs after user clears the data.
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 4. to release

#11548 Handling empty state for rich document dialog.
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.kt
Labels: 3. to review
