Repository nextcloud/android, pull requests merged in 2023-01, with the labels that each got.

#11194 fix/random lint
  app/src/main/java/com/owncloud/android/media/MediaControlView.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploaderAdapter.java
  app/src/main/res/layout/contacts_preference.xml
  app/src/main/res/layout/files.xml
  app/src/main/res/layout/preview_image_activity.xml
  scripts/analysis/lint-results.txt
Labels: 1. developing

#11242 PassCodeManager: add some logic to avoid counting the same activity twice
  app/src/androidTest/java/com/owncloud/android/authentication/PassCodeManagerIT.kt
  app/src/main/java/com/owncloud/android/authentication/PassCodeManager.kt
  app/src/test/java/com/owncloud/android/authentication/PassCodeManagerTest.kt
Labels: 3. to review

#11248 Enable overriding injections in AndroidInjection classes during connected tests
  app/src/androidTest/java/com/nextcloud/client/AuthenticatorActivityIT.java
  app/src/androidTest/java/com/nextcloud/client/CommunityActivityIT.java
  app/src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.kt
  app/src/androidTest/java/com/nextcloud/client/ScreenshotTestRunner.java
  app/src/androidTest/java/com/nextcloud/client/ScreenshotTestRunner.kt
  app/src/androidTest/java/com/nextcloud/client/SettingsActivityIT.kt
  app/src/androidTest/java/com/nextcloud/test/GrantStoragePermissionRule.kt
  app/src/androidTest/java/com/nextcloud/test/InjectionOverrideRule.kt
  app/src/androidTest/java/com/nextcloud/test/InjectionTestActivityTest.kt
  app/src/androidTest/java/com/nextcloud/test/RetryTestRule.kt
  app/src/androidTest/java/com/nextcloud/test/TestMainApp.kt
  app/src/androidTest/java/com/nextcloud/ui/BitmapIT.kt
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/authentication/PassCodeManagerIT.kt
  app/src/androidTest/java/com/owncloud/android/files/FileMenuFilterIT.kt
  app/src/androidTest/java/com/owncloud/android/providers/UsersAndGroupsSearchProviderIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/LoginIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/activity/DrawerActivityIT.java
  app/src/androidTest/java/com/owncloud/android/ui/activity/FileDisplayActivityTest.java
  app/src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SendFilesDialogTest.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SendShareDialogTest.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragmentIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/fragment/AvatarIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/fragment/GalleryFragmentIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/fragment/UnifiedSearchFragmentIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/helpers/UriUploaderIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/preview/PreviewImageFragmentIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/preview/pdf/PreviewPdfFragmentScreenshotIT.kt
  app/src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/com/nextcloud/client/di/BuildTypeComponentsModule.kt
  app/src/debug/java/com/nextcloud/test/InjectionTestActivity.kt
  app/src/debug/java/com/nextcloud/test/TestActivity.kt
  app/src/debug/res/layout/activity_injection_test.xml
Labels: 3. to review

#11192 Reset search when browsing to a folder from the favorites list
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityIT.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review

#11250 fix(EditorWebView): Move local image upload to the editor web view
  app/src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  app/src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.java
Labels: bug, 3. to review

#11251 Avoid JSON deserialization in common trivial cases
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 3. to review, technical debt, performance, ui/ux

#11268 Chore: copy wait_for_server from library
  scripts/wait_for_server.sh
Labels: 3. to review

#11272 drone: Fix branchname for text app
  .drone.yml
Labels: 3. to review

#8643 Use localID from webdav
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/67.json
  app/src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerContentProviderClientIT.java
  app/src/androidTest/java/com/owncloud/android/datamodel/FileDataStorageManagerIT.java
  app/src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  app/src/androidTest/java/com/owncloud/android/ui/fragment/GalleryFragmentIT.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/FileEntity.kt
  app/src/main/java/com/nextcloud/client/media/LoadUrlTask.kt
  app/src/main/java/com/nextcloud/client/media/Player.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/files/StreamMediaFileOperation.java
  app/src/main/java/com/owncloud/android/operations/CommentFileOperation.java
  app/src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.java
  app/src/main/java/com/owncloud/android/operations/RichDocumentsUrlOperation.java
  app/src/main/java/com/owncloud/android/services/OperationsService.java
  app/src/main/java/com/owncloud/android/ui/events/EncryptionEvent.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  app/src/test/java/com/owncloud/android/datamodel/OCFileTest.kt
Labels: 3. to review

#11269 ChooseTemplateDialogFragment: check selectedTemplate is not null before attempting to get the extension
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.kt
Labels: 3. to review

#11273 build: Bump compileSdk to 33
  app/build.gradle
  app/src/androidTest/java/com/nextcloud/client/integrations/deck/DeckApiTest.kt
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review, technical debt

#11227 Skip check for existing files when reading file data from local DB
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
Labels: 3. to review, technical debt, performance

#11100 Refresh UI only when changes are detected on the server
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
Labels: 3. to review, performance, ui/ux

#11287 upon upgrade localID may be null, better use default value
  app/build.gradle
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/68.json
  app/src/androidTest/java/com/nextcloud/client/database/migrations/MigrationTest.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/FileEntity.kt
  app/src/main/java/com/nextcloud/client/database/migrations/DatabaseMigrationUtil.kt
  app/src/main/java/com/nextcloud/client/database/migrations/Migration67to68.kt
  app/src/main/java/com/nextcloud/client/database/migrations/RoomMigration.kt
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
Labels: 3. to review

#11230 Show setup e2e only when
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 3. to review

#11146 Show "unset encryption" only when E2E is setup
  app/src/androidTest/java/com/owncloud/android/files/FileMenuFilterIT.kt
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
Labels: 3. to review

#11138 Shows favorite state in share overview
  app/src/main/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverter.kt
  app/src/test/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverterTest.kt
Labels: 3. to review

#10558 When uploading files to an encrypted folder do not allow to upload entire folders
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review, backport-request

#11296 Bumps for 3.24.0 RC1
  app/build.gradle
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30240051.txt
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 3. to review

#11299 Bumps on master after 3.24
  app/build.gradle
  app/src/main/java/com/owncloud/android/MainApp.java
Labels: 3. to review

#11300 Add changelog for 3.24.0 RC1
  CHANGELOG.md
Labels: 3. to review

#11302 Drone: update server images to use php 8
  .drone.yml
Labels: 3. to review

#11301 Fastfile: fix check for screenshots
  fastlane/Fastfile
Labels: 3. to review, backport-request

#11309 Update SettingsActivity screenshots to fix screenshot tests
  app/screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_open.png
  app/screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error.png
Labels: 3. to review, backport-request

#11327 Bump for 3.24.0 RC2
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30240052.txt
Labels: 3. to review

#11330 Add changelog for 3.24.0 RC2
  CHANGELOG.md
Labels: 3. to review
