Repository nextcloud/android, pull requests merged in 2023-07, with the labels that each got.

#11746 Add image editor
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/client/editimage/EditImageActivity.kt
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/utils/MimeType.java
  app/src/main/res/drawable/outline_flip_24.xml
  app/src/main/res/drawable/outline_rotate_90_degrees_ccw_24.xml
  app/src/main/res/drawable/rounded_rect.xml
  app/src/main/res/layout/activity_edit_image.xml
  app/src/main/res/layout/preview_image_activity.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 3. to review

#11761 PreviewMediaFragment: UI/UX improvements
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/res/values/setup.xml
Labels: 3. to review

#11765 Fix crash when emptying bin
  app/src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.java
Labels: 3. to review

#11759 Do not show "stream with" option for encrypted files
  app/src/androidTest/java/com/owncloud/android/files/FileMenuFilterIT.kt
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
Labels: 3. to review

#11774 After successful upload update permission to have correct resharing info
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to review, backport-request

#11794 Support Android 13 / API 33
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#11568 Fix: new folder/file share permission
  app/src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
Labels: 3. to review

#11410 Fix crashes when receiving external files and last upload folder was deleted
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 3. to review

#11799 Fix external links in texteditor
  app/src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  app/src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
Labels: 3. to review

#11430 Add RetryTestRule to ContactsBackupIT
  app/src/androidTest/java/com/nextcloud/client/jobs/ContactsBackupIT.kt
Labels: 3. to review

#11805 Fix preview media file update for file action
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 3. to review

#11804 Crash fix for shared and fav section
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review

#11821 Fix folder picker empty state headline text
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
Labels: bug, 3. to review

#11813 Fix upload list touch target by removing frame layout
  app/src/main/res/layout/upload_list_item.xml
Labels: bug, 3. to review

#11817 Fix empty state for media view
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryAdapter.kt
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: bug, 3. to review

#11778 Hide actionbar title when search input field is opened
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
Labels: 3. to review

#11839 Remove unnecessary call to clear title in UnifiedSearchFragment
  app/src/main/java/com/owncloud/android/ui/fragment/UnifiedSearchFragment.kt
Labels: 3. to review

#11843 When entering fullscreen, allow for paused state
  app/src/main/java/com/owncloud/android/ui/preview/PreviewVideoFullscreenDialog.kt
Labels: 3. to review

#11840 Improve UX when creating rich document
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
Labels: 3. to review

#11689 Fix actions in folder picker
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivityIT.kt
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/res/layout/receive_external_files.xml
  app/src/main/res/menu/activity_folder_picker.xml
  app/src/main/res/menu/activity_receive_external_files.xml
Labels: 3. to review

#11736 Fix file actions available in BottomSheet
  app/detekt.yml
  app/src/androidTest/java/com/owncloud/android/files/FileMenuFilterIT.kt
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsBottomSheet.kt
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsViewModel.kt
  app/src/main/java/com/owncloud/android/files/FileMenuFilter.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  scripts/analysis/lint-results.txt
Labels: 3. to review

#11846 Refactor links
  app/src/main/java/com/nextcloud/client/errorhandling/ShowErrorActivity.kt
  app/src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.java
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 3. to review

#11769 Fix back arrow appearing as hamburger icon
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review
