Repository nextcloud/android, pull requests merged in 2023-06, with the labels that each got.

#11673 fix showing only one groupfolder
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.GroupfolderListFragmentIT_showEmpty.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.GroupfolderListFragmentIT_showGroupfolder.png
  app/src/androidTest/java/com/owncloud/android/ui/fragment/GroupfolderListFragmentIT.kt
  app/src/main/java/com/owncloud/android/ui/fragment/GroupfolderListFragment.kt
Labels: 3. to review, backport-request

#11644 Prevent having double entries after rotate
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsBottomSheet.kt
Labels: 3. to review, backport-request

#11682 bump to 3.25.0 RC2
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30250052.txt
Labels: 3. to review

#11687 upon update reset capabilities
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/71.json
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/migrations/DatabaseMigrationUtil.kt
  app/src/main/java/com/nextcloud/client/database/migrations/Migration70to71.kt
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
Labels: 3. to review, backport-request

#11546 Use resultData for Push and Notifications
  app/src/gplay/java/com/owncloud/android/utils/PushUtils.java
  app/src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.java
Labels: 3. to review

#11694 Remember mnemonic on device rotation
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragmentIT.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review, backport-request

#11560 Triggering one email for newly created share.
  app/src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
Labels: 3. to review

#11706 Fixed grammar
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#11557 Increase max heap space in base gradle.properties
  gradle.properties
Labels: 3. to review

#11715 Make actions cancelable
  .github/workflows/analysis.yml
  .github/workflows/assembleFlavors.yml
  .github/workflows/check.yml
  .github/workflows/detectSnapshot.yml
  .github/workflows/qa.yml
  .github/workflows/screenShotTest.yml
  .github/workflows/unit-tests.yml
Labels: 4. to release

#11693 Notification list customization
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.NotificationsActivityIT_showNotifications.png
  app/src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  app/src/main/res/layout/notification_list_item.xml
  app/src/main/res/values/dims.xml
Labels: design, 3. to review

#11591 Launcher screen
  app/build.gradle
  app/screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login.png
  app/src/androidTest/java/com/nmc/android/ui/LauncherActivityIT.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nmc/android/ui/LauncherActivity.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/res/drawable-hdpi/logo.png
  app/src/main/res/drawable/launch_screen.xml
  app/src/main/res/drawable/logo.xml
  app/src/main/res/drawable/nextcloud_splash_logo.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/setup.xml
  app/src/main/res/values/styles.xml
  drawable_resources/logo.svg
  drawable_resources/nextcloud-logo.svg
  drawable_resources/nextcloud-splash-logo.svg
  scripts/analysis/lint-results.txt
Labels: design, 3. to review

#11228 E2E setup is only possible with internet connection
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/res/values/strings.xml
Labels: 4. to release

#11732 Detect if beta is true
  .github/workflows/detectSnapshot.yml
  .github/workflows/detectWrongSettings.yml
  app/src/main/res/values/setup.xml
  scripts/analysis/detectSNAPSHOT.sh
  scripts/analysis/detectWrongSettings.sh
Labels: 2. developing, backport-request

#11730 Fix file actions in bottom sheet cut off
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testFileActionsBottomSheet.png
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsBottomSheet.kt
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/res/layout/file_actions_bottom_sheet.xml
Labels: 3. to review

#11756 Fix encrypted folder icon
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review

#11523 E2EE dialog crash on clicking "Set as Encrypted" multiple times
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.java
Labels: 3. to review
