Repository nextcloud/android, pull requests merged in 2024-02, with the labels that each got.

#12479 Use commit instead of SNAPSHOT for library version due to dependency …
  build.gradle
  gradle/verification-metadata.xml
  scripts/analysis/analysis-wrapper.sh
Labels: 4. to release

#12512 Fix QA failure
  .github/workflows/qa.yml
Labels: 3. to review

#12525 Add httpclient dependency keys
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review, dependencies, technical debt

#12473 Personal view
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/res/menu/partial_drawer_entries.xml
  app/src/main/res/values/strings.xml
Labels: 2. developing

#12529 Update to latest lib snapshot metadata
  build.gradle
  gradle/verification-metadata.xml
Labels: dependencies, technical debt

#12530 remove dependabot due to switch to renovatebot
  .github/dependabot.yml
Labels: technical debt

#12533 Update library meta data
  build.gradle
  gradle/verification-metadata.xml
Labels: 4. to release, dependencies, technical debt

#12535 Replace ampersand with "and"
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request, i18n

#12542 Update to latest lib build on master branch
  build.gradle
  gradle/verification-metadata.xml
Labels: 4. to release, dependencies, technical debt

#12323 Feature/add exclude hidden file or folder option when create custom media folder type
  app/build.gradle
  app/detekt.yml
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/78.json
  app/src/androidTest/java/com/nextcloud/client/SyncedFoldersActivityIT.java
  app/src/androidTest/java/com/owncloud/android/utils/SyncedFolderUtilsTest.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/SyncedFolderEntity.kt
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolderDisplayItem.java
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/parcel/SyncedFolderParcelable.java
  app/src/main/java/com/owncloud/android/utils/FileUtil.java
  app/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  app/src/main/java/com/owncloud/android/utils/WebViewUtil.kt
  app/src/main/res/layout/synced_folders_settings_layout.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java
Labels: enhancement, design, 3. to review

#12519 Bugfix for unspecific errors when renaming files from different session
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
Labels: bug, 3. to review

#12527 Add global upload pause button
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadHelper.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploaderIntents.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
  app/src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/res/drawable/ic_pause.xml
  app/src/main/res/drawable/ic_play.xml
  app/src/main/res/menu/activity_upload_list.xml
  app/src/main/res/menu/upload_list_failed_options.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: sync and upload

#12544 Fixes #11337 - UI drawer overlapping
  app/screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  app/src/main/res/layout/drawer.xml
  app/src/main/res/menu/partial_drawer_entries.xml
Labels: 3. to review

#12554 Revert screenshots for 3.28
  app/screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_openDrawer.png
  app/screenshots/gplay/debug/com.nextcloud.client.ActivitiesActivityIT_showActivities.png
  app/screenshots/gplay/debug/com.nextcloud.client.CommunityActivityIT_open.png
  app/screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer.png
  app/screenshots/gplay/debug/com.nextcloud.client.SettingsActivityIT_showMnemonic_Error.png
  app/screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_testSyncedFolderDialog.png
  app/screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  app/screenshots/gplay/debug/com.nextcloud.client.etm.EtmActivityTest_overview.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_open.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_testChooseLocationAction.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_testMoveOrCopy.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_userInfoDetail.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.NotificationsActivityIT_empty.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.NotificationsActivityIT_error.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.NotificationsActivityIT_showNotifications.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ReceiveExternalFilesActivityIT_open.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ReceiveExternalFilesActivityIT_openMultiAccount.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.UserInfoActivityIT_fullUserInfoDetail.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testEnforcedPasswordDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testOptionalPasswordDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testRenameFileDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testStoragePermissionDialog.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SetupEncryptionDialogFragmentIT_showMnemonic.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailFragmentStaticServerIT_showFileDetailDetailsFragment.png
Labels: technical debt

#12559 Add further keys/metadata
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: technical debt

#12546 Bugfix Check ClassCastException edge, Nullability of Bundle or Intent
  app/src/androidTest/java/com/nextcloud/extensions/BundleExtensionTests.kt
  app/src/androidTest/java/com/nextcloud/extensions/IntentExtensionTests.kt
  app/src/androidTest/java/com/nextcloud/test/model/TestModels.kt
  app/src/main/java/com/nextcloud/utils/extensions/BundleExtensions.kt
  app/src/main/java/com/nextcloud/utils/extensions/IntentExtensions.kt
Labels: 2. developing, backport-request

#12540 BugFix Check emptiness of previousSortGroupState
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 3. to review, backport-request

#12549 Add resume option for cancelled uploads
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadHelper.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/db/OCUpload.java
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/res/menu/upload_list_cancelled_options.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review

#12573 fix(i18n): Fixed typo
  app/src/main/res/values/strings.xml
Labels: backport-request

#12587 On branded clients NPE can occur
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: backport-request

#12584 Remove previousSortGroupState Usage For Set Visibility Of Sort List Group
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review

#12616 Fix SecurityException in UsersAndGroupsSearchProvider
  app/src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
Labels: 3. to review
