Repository nextcloud/android, pull requests merged in 2024-04, with the labels that each got.

#12777 Add SPDX header template
  .idea/copyright/Nextcloud___Android_Client.xml
  .idea/copyright/profiles_settings.xml
Labels: 4. to release, technical debt

#12738 Add changelog for 3.28.1
  CHANGELOG.md
Labels: 3. to review

#12785 Fix naming errors
  drawable_resources/first_run_files.svg.license
  drawable_resources/first_run_groupware.svg.license
  drawable_resources/icon-background.svg.license
Labels: bug, technical debt

#12786 Add SPDX headers
  drawable_resources/modification_asc.svg.license
  drawable_resources/modification_desc.svg.license
Labels: technical debt

#12791 Add Status for Assistant Tasks
  app/src/main/java/com/nextcloud/client/assistant/AssistantViewModel.kt
  app/src/main/java/com/nextcloud/client/assistant/AsssistantScreen.kt
  app/src/main/java/com/nextcloud/client/assistant/component/TaskView.kt
  app/src/main/java/com/nextcloud/client/assistant/extensions/TaskExtensions.kt
  app/src/main/java/com/nextcloud/ui/composeActivity/ComposeActivity.kt
  app/src/main/res/drawable/ic_expand_less.xml
  app/src/main/res/drawable/ic_expand_more.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_unknown.xml
  app/src/main/res/layout/toolbar_standard.xml
  app/src/main/res/values-bg-rBG/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs-rCZ/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es-rEC/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu-rHU/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ja-rJP/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt-rLT/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sc/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12795 Simplify main app get string logic
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datastorage/providers/SystemDefaultStoragePointProvider.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/java/com/owncloud/android/utils/theme/ThemeUtils.java
Labels: 3. to review

#12797 Fix enableOnBackInvokedCallback Warning
  app/src/main/AndroidManifest.xml
Labels: 3. to review

#12803 Add SPDX header
  app/src/main/aidl/com/nextcloud/android/sso/aidl/IInputStreamService.aidl
  app/src/main/java/com/nextcloud/android/sso/Constants.java
  app/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  app/src/main/java/com/nextcloud/android/sso/aidl/IThreadListener.java
  app/src/main/java/com/nextcloud/android/sso/aidl/NextcloudRequest.java
  app/src/main/java/com/nextcloud/android/sso/aidl/ParcelFileDescriptorUtil.java
  app/src/main/java/com/owncloud/android/services/AccountManagerService.java
  app/src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  app/src/main/java/com/owncloud/android/ui/activities/ActivitiesContract.java
  app/src/main/java/com/owncloud/android/ui/activities/ActivitiesPresenter.java
  app/src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesRepository.java
  app/src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApi.java
  app/src/main/java/com/owncloud/android/ui/activities/data/activities/ActivitiesServiceApiImpl.java
  app/src/main/java/com/owncloud/android/ui/activities/data/activities/ActivityRepositories.java
  app/src/main/java/com/owncloud/android/ui/activities/data/activities/RemoteActivitiesRepository.java
  app/src/main/java/com/owncloud/android/ui/activities/data/files/FileRepositories.java
  app/src/main/java/com/owncloud/android/ui/activities/data/files/FilesRepository.java
  app/src/main/java/com/owncloud/android/ui/activities/data/files/FilesServiceApi.java
  app/src/main/java/com/owncloud/android/ui/activities/data/files/FilesServiceApiImpl.java
  app/src/main/java/com/owncloud/android/ui/activities/data/files/RemoteFilesRepository.java
  app/src/main/java/com/owncloud/android/ui/activity/SsoGrantPermissionActivity.java
  app/src/main/java/third_parties/aosp/SQLiteTokenizer.java
  app/src/main/java/third_parties/sufficientlysecure/ProcessVEvent.java
  app/src/main/java/third_parties/sufficientlysecure/SaveCalendar.java
  app/src/test/java/com/owncloud/android/ui/activities/ActivitiesPresenterTest.java
  app/src/test/java/com/owncloud/android/ui/activities/data/activities/RemoteActivitiesRepositoryTest.java
  app/src/test/java/com/owncloud/android/ui/activities/data/files/RemoteFilesRepositoryTest.java
  app/src/test/java/com/owncloud/android/utils/OwnCloudSessionTest.java
Labels: 3. to review, 4. to release, technical debt

#12790 Add SPDX header
  app/src/main/java/com/nextcloud/android/sso/aidl/IThreadListener.java
  app/src/main/java/com/nextcloud/android/sso/aidl/NextcloudRequest.java
  app/src/main/java/com/nextcloud/android/sso/aidl/ParcelFileDescriptorUtil.java
  app/src/main/java/com/owncloud/android/services/AccountManagerService.java
Labels: 3. to review, feedback-requested

#12808 Add SPDX header
  app/src/huawei/res/values/bools.xml
  app/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
  app/src/main/java/com/nextcloud/android/sso/PatchMethod.java
  app/src/main/java/com/nextcloud/android/sso/PlainHeader.java
  app/src/main/java/com/nextcloud/android/sso/Response.java
  app/src/main/java/com/nextcloud/client/account/AnonymousUser.kt
  app/src/main/java/com/nextcloud/client/account/MockUser.kt
  app/src/main/java/com/nextcloud/client/account/RegisteredUser.kt
  app/src/main/java/com/nextcloud/client/account/Server.kt
  app/src/main/java/com/nextcloud/client/account/User.kt
  app/src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
Labels: 2. developing, technical debt

#12810 Replace Optional backport with actual java implementation
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/main/java/com/nextcloud/client/account/UserAccountManager.java
  app/src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  app/src/main/java/com/nextcloud/client/integrations/deck/DeckApi.kt
  app/src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/AccountRemovalWork.kt
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadHelper.kt
  app/src/main/java/com/nextcloud/client/mixins/SessionMixin.kt
  app/src/main/java/com/nextcloud/client/widget/WidgetConfiguration.kt
  app/src/main/java/com/nextcloud/client/widget/WidgetRepository.kt
  app/src/main/java/com/nextcloud/java/util/Optional.java
  app/src/main/java/com/nextcloud/java/util/function/Predicate.java
  app/src/main/java/com/nextcloud/java/util/package-info.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/services/OperationsService.java
  app/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  app/src/main/java/com/owncloud/android/utils/theme/CapabilityUtils.java
Labels: 4. to release, technical debt

#12794 Fix upload download problems
  app/src/main/java/com/nextcloud/client/jobs/OfflineSyncWork.kt
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadHelper.kt
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.java
Labels: 3. to review, backport-request

#12817 Enhance Passcode
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/authentication/PassCodeManager.kt
Labels: 3. to review, backport-request

#12796 Fix Upload Problems For Encrypted Folder
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review, backport-request

#12838 Add SPDX header
  app/src/main/res/layout/gallery_header.xml
  app/src/main/res/layout/gallery_row.xml
  app/src/main/res/layout/unified_search_footer.xml
  app/src/main/res/layout/unified_search_header.xml
  app/src/main/res/layout/unified_search_item.xml
  app/src/main/res/layout/widget_item.xml
  app/src/main/res/layout/widget_item_load_more.xml
  app/src/main/res/layout/widget_list_item.xml
  app/src/main/res/menu/activity_file_display.xml
  app/src/main/res/menu/activity_trashbin.xml
  app/src/main/res/menu/activity_upload_list.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-sw360dp/dims.xml
  app/src/main/res/values-sw600dp/dims.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  app/src/qa/java/com/nextcloud/client/di/VariantComponentsModule.java
  app/src/test/java/com/owncloud/android/authentication/AuthenticatorDataUrlTest.java
  app/src/test/java/com/owncloud/android/authentication/AuthenticatorUrlUtilsTest.java
  app/src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java
  app/src/test/java/com/owncloud/android/ui/adapter/ActivityListAdapterTest.java
  app/src/test/java/com/owncloud/android/ui/adapter/UserListAdapterTest.java
  app/src/test/java/com/owncloud/android/utils/DisplayUtilsTest.java
  app/src/versionDev/java/com/nextcloud/client/di/VariantComponentsModule.java
Labels: 4. to release, technical debt

#12824 Add changelog for 3.28.2
  CHANGELOG.md
Labels: 3. to review

#12844 Add SPDX header
  app/src/main/java/com/nextcloud/client/errorhandling/ExceptionHandler.kt
  app/src/main/java/com/nextcloud/client/integrations/deck/DeckApi.kt
  app/src/main/java/com/nextcloud/client/integrations/deck/DeckApiImpl.kt
  app/src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/authentication/AccountAuthenticator.java
  app/src/main/java/com/owncloud/android/authentication/AccountAuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/authentication/AccountAuthenticatorService.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.kt
  app/src/main/java/com/owncloud/android/authentication/LoginUrlInfo.java
  app/src/main/java/com/owncloud/android/datamodel/DecryptedPushMessage.kt
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
  app/src/main/java/com/owncloud/android/operations/RenameFileOperation.java
  appscan/build.gradle
Labels: 3. to review, technical debt

#12848 Add missing SPDX header and check
  .github/workflows/reuse.yml
  README.md
  THIRD_PARTY.txt
  app/src/main/java/com/owncloud/android/providers/UsersAndGroupsSearchProvider.java
  app/src/main/java/com/owncloud/android/services/SyncFolderHandler.java
  app/src/main/java/com/owncloud/android/syncadapter/AbstractOwnCloudSyncAdapter.java
  app/src/main/java/com/owncloud/android/syncadapter/FileSyncAdapter.java
  app/src/main/java/com/owncloud/android/syncadapter/FileSyncService.java
  app/src/main/java/com/owncloud/android/ui/CheckBoxPreferenceWithLongTitle.java
  app/src/main/java/com/owncloud/android/ui/ExtendedListView.java
  app/src/main/java/com/owncloud/android/ui/SquareImageView.java
  app/src/main/java/com/owncloud/android/ui/SquareLinearLayout.java
  app/src/main/java/com/owncloud/android/ui/activity/ComponentsGetter.java
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/ErrorsWhileCopyingHandlerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/HookActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/OnEnforceableRefreshListener.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ShareActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/CertificateCombinedExceptionViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
  app/src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/SslCertificateViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/SslErrorViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/X509CertificateViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/notifications/NotificationUtils.java
  app/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  app/src/main/java/com/owncloud/android/ui/trashbin/RemoteTrashbinRepository.kt
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
  app/src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  app/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  app/src/main/java/com/owncloud/android/utils/OwnCloudSession.java
  app/src/main/res/layout/files_folder_picker.xml
  app/src/test/java/com/owncloud/android/ui/db/OCUploadComparatorTest.kt
  build.gradle
Labels: 4. to release, technical debt

#12856 Optimize and fix some bugs for autoupload
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/81.json
  app/src/androidTest/java/com/nextcloud/client/SyncedFoldersActivityIT.java
  app/src/androidTest/java/com/nextcloud/client/jobs/BackgroundJobManagerTest.kt
  app/src/androidTest/java/com/owncloud/android/utils/SyncedFolderUtilsTest.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/SyncedFolderEntity.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/ContentObserverWork.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolderDisplayItem.java
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolderProvider.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  app/src/test/java/com/owncloud/android/ui/activity/SyncedFoldersActivityTest.java
Labels: 3. to review

#12880 Assistant Feature UI/UX Fixes
  app/src/main/java/com/nextcloud/client/assistant/AsssistantScreen.kt
  app/src/main/java/com/nextcloud/client/assistant/extensions/TaskExtensions.kt
  app/src/main/java/com/nextcloud/client/assistant/repository/AssistantMockRepository.kt
  app/src/main/java/com/nextcloud/client/assistant/task/TaskStatus.kt
  app/src/main/java/com/nextcloud/client/assistant/task/TaskView.kt
  app/src/main/java/com/nextcloud/client/assistant/taskDetail/TaskDetailBottomSheet.kt
  app/src/main/java/com/nextcloud/client/assistant/taskTypes/TaskTypesRow.kt
  app/src/main/java/com/nextcloud/ui/composeActivity/ComposeActivity.kt
  app/src/main/java/com/nextcloud/utils/extensions/StringExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  app/src/main/res/drawable/ic_expand_less.xml
  app/src/main/res/layout/toolbar_standard.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12828 Bugfix Handle Temp Encrypted File Correctly
  app/src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadHelper.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 3. to review

#12899 fix(i18n): Improved grammar
  app/src/main/res/values/strings.xml
Labels: backport-request

#12917 Update pdf icon
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.UploadFilesActivityIT_noneSelected.png
  app/src/main/res/drawable/file_pdf.xml
Labels: design, 3. to review, backport-request, papercut

#12925 Add changelog for 3.29.0
  CHANGELOG.md
Labels: 3. to review

#12938 Have correct SPDX license header for logo/trademarked items
  .reuse/dep5
  LICENSES/LicenseRef-NextcloudTrademarks.txt
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/logo.xml
Labels: bug, 4. to release, backport-request, technical debt

#12877 Show snackbar above FAB
  .github/workflows/screenShotTest.yml
  app/screenshots/gplay/debug/com.owncloud.android.ui.preview.PreviewTextFileFragmentTest_displayJavaSnippetFile.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.preview.PreviewTextFileFragmentTest_displaySimpleTextFile.png
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 3. to review

#12944 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#12943 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#12922 Login Flow v2
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/res/layout/account_setup_webview.xml
  app/src/main/res/layout/login_flow_info_layout_v2.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12875 Add automatic Per App Languages
  app/build.gradle
  app/src/main/res/resources.properties
Labels: enhancement, 3. to review, feedback-requested

#12927 Use getFileNameText for nullable field
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.java
Labels: 3. to review
