Repository nextcloud/android, pull requests merged in 2024-09, with the labels that each got.

#13471 BugFix - Observe Worker State
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/nextcloud/model/WorkerState.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
Labels: 3. to review

#13487 BugFix - Check Thumbnail Existence and Shimmering
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 3. to review

#13472 BugFix - LauncherActivityIT Tests
  app/src/androidTest/java/com/nmc/android/ui/LauncherActivityIT.kt
Labels: 3. to review

#13544 3.30.0 RC2
  app/build.gradle
  src/versionDev/fastlane/metadata/android/en-US/changelogs/30300052.txt
  src/versionDev/fastlane/metadata/android/en-US/changelogs/30300052.txt.license
Labels: 3. to review

#13541 BugFix - Dont Set Connectivity Cache True When Base Server Address Is Empty & Fix Screenshot Tests
  app/screenshots/gplay/debug/com.nextcloud.client.SyncedFoldersActivityIT_open.png
  app/screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ContactsPreferenceActivityIT_openContactsPreference.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ContactsPreferenceActivityIT_openVCF.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_open.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_testChooseLocationAction.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.FolderPickerActivityIT_testMoveOrCopy.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ManageAccountsActivityIT_open.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ReceiveExternalFilesActivityIT_open.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ReceiveExternalFilesActivityIT_openMultiAccount.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.BackupListFragmentIT_showCalendarList.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.BackupListFragmentIT_showContactList.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.BackupListFragmentIT_showLoading.png
  app/src/androidTest/java/com/owncloud/android/files/services/LegacyFileUploaderIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/preview/PreviewTextFileFragmentTest.java
  app/src/androidTest/java/com/owncloud/android/ui/preview/PreviewTextFileFragmentTest.kt
  app/src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  app/src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 3. to review

#13551 Do not allow multiple instances of LoadingDialog
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
Labels: 3. to review

#13513 BugFix - Unify Drawer Menu Item Handling
  app/src/main/java/com/nextcloud/ui/composeActivity/ComposeActivity.kt
  app/src/main/java/com/nextcloud/utils/extensions/DrawerActivityExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/CommunityActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.kt
Labels: 3. to review

#13518 BugFix - Share Link
  app/src/androidTest/java/com/nextcloud/client/files/DeepLinkHandlerTest.kt
  app/src/main/java/com/nextcloud/client/files/DeepLinkConstants.kt
  app/src/main/java/com/nextcloud/client/files/DeepLinkHandler.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review

#13533 Flag FLAG_SECURE should only be active when in passcode screen
  app/src/main/java/com/owncloud/android/authentication/PassCodeManager.kt
  app/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/RequestCredentialsActivity.java
Labels: 3. to review

#13467 Improve Media Player
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/di/AppComponent.java
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/client/media/BackgroundPlayerService.kt
  app/src/main/java/com/owncloud/android/media/MediaControlView.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.kt
  app/src/main/res/layout/activity_preview_media.xml
  app/src/main/res/layout/fragment_preview_media.xml
  gradle/verification-metadata.xml
Labels: 3. to review, feature: media player, feedback-requested

#13552 BugFix - Check Filename Limitation With Correct Server Version and Configuration
  app/src/androidTest/java/com/nextcloud/utils/FileNameValidatorTests.kt
  app/src/main/java/com/nextcloud/utils/fileNameValidator/FileNameValidator.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+en+001/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ga/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13556 BugFix - Loading Dialog Must Run On Main Thread
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
Labels: 3. to review

#13561 3.30 RC3
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30300053.txt
  fastlane/metadata/android/en-US/changelogs/30300053.txt.license
Labels: 3. to review

#13562 3.30.0 Final
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30300090.txt
  fastlane/metadata/android/en-US/changelogs/30300090.txt.license
Labels: 3. to review

#13514 BugFix - E2E Solve File Conflict NPE
  app/src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
Labels: 3. to review

#13577 File Name Validator Improvements
  app/src/androidTest/java/com/nextcloud/utils/FileNameValidatorTests.kt
  app/src/main/java/com/nextcloud/utils/fileNameValidator/FileNameValidator.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13512 [Bug Fix] Attach snackbar only to respective fragment item in viewpager
  app/src/main/res/layout/preview_image_fragment.xml
Labels: 3. to review, feedback-requested

#13578 Fix ANR During Uploads
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadHelper.kt
Labels: 3. to review

#13580 Show New Notifications Only For File Specific Errors
  app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
  app/src/main/java/com/nextcloud/utils/extensions/RemoteOperationResultExtensions.kt
Labels: 3. to review

#13575 BugFix - Use Activity When Fragment Added
  app/src/main/java/com/nextcloud/utils/extensions/FragmentExtensions.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.kt
Labels: 3. to review

#13534 Always download if image is unsupported
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, feedback-requested

#13620 Improve issue reporting guidance
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  SECURITY.md
Labels: 4. to release, developer experience

#13625 Fix Flaky FileDetailFragmentStaticServerIT Tests
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailFragmentStaticServerIT.kt
Labels: 3. to review

#13613 Simplify FileNameValidator Check
  app/src/main/java/com/nextcloud/utils/extensions/OCCapabilityExtensions.kt
  app/src/main/java/com/nextcloud/utils/fileNameValidator/FileNameValidator.kt
Labels: 3. to review

#13583 Feature - Auto Rename
  app/src/androidTest/java/com/nextcloud/utils/AutoRenameTests.kt
  app/src/main/java/com/nextcloud/utils/autoRename/AutoRename.kt
  app/src/main/java/com/nextcloud/utils/extensions/OCCapabilityExtensions.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/java/com/owncloud/android/ui/helpers/UriUploader.kt
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtilsV2.kt
  app/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13656 Fix typo?
  app/src/main/java/com/nextcloud/utils/autoRename/AutoRename.kt
  app/src/main/java/com/nextcloud/utils/extensions/OCCapabilityExtensions.kt
Labels: 3. to review

#12998 Removed Autofill Attribute from account setup xml file
  app/src/main/res/layout-land/account_setup.xml
  app/src/main/res/layout/account_setup.xml
Labels: 3. to review, feedback-requested

#12924 Test new NC versions
  app/src/androidTest/java/com/owncloud/android/utils/theme/CapabilityUtilsIT.kt
Labels: 3. to review
