Repository nextcloud/android, pull requests merged in 2024-08, with the labels that each got.

#13344 Bugfix - Not attached to an activity on GalleryFragment
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 3. to review

#13346 Convert PreviewTextFragment to Kotlin
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFileFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewTextStringFragment.java
Labels: 3. to review

#12809 Add SPDX header
  app/src/androidTest/java/com/owncloud/android/files/FileMenuFilterIT.kt
  app/src/main/java/com/nextcloud/client/device/DeviceModule.kt
  app/src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverter.kt
  app/src/main/java/com/owncloud/android/ui/dialog/StoragePermissionDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/events/FileLockEvent.kt
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListSearchAsyncTask.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewBitmapActivity.kt
  app/src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfAdapter.kt
  app/src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfViewModel.kt
  app/src/test/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverterTest.kt
Labels: 2. developing, feedback-requested

#13343 Bugfix - Sync NPE Check
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
  app/src/main/java/com/owncloud/android/files/services/IndexedForest.java
Labels: 3. to review

#13350 Bugfix - Not attached to an activity on PreviewMediaFragment
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.kt
Labels: 3. to review

#13322 Check Existence of File in onStop().PreviewMediaActivity
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
Labels: 3. to review

#13356 Bugfix - Delete Video While Previewing
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
Labels: 3. to review

#13192 Fix ss tests
  app/build.gradle
  app/screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_empty.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.trashbin.TrashbinActivityIT_loading.png
  app/src/androidTest/java/com/nextcloud/client/AuthenticatorActivityIT.java
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.kt
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/ui/activity/NotificationsActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/trashbin/TrashbinActivityIT.kt
  app/src/androidTest/java/com/owncloud/android/utils/EspressoIdlingResource.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinContract.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinPresenter.kt
  gradle/verification-metadata.xml
Labels: 3. to review

#13380 BugFix - Change Layout Gravity Of Empty View To The Center
  app/src/main/res/layout/empty_list.xml
Labels: 3. to review

#13407 Revert "BugFix - Change Layout Gravity Of Empty View To The Center"
  app/src/main/res/layout/empty_list.xml
Labels: 3. to review

#13405 BugFix - Passcode Match
  app/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.kt
Labels: 3. to review

#13409 Shift Empty View for Preview Media Activity
  app/src/main/java/com/nextcloud/utils/extensions/ContextExtensions.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
  app/src/main/res/layout/empty_list.xml
Labels: 3. to review

#13068 Upload filter
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.UploadFilesActivityIT_search.png
  app/src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
  app/src/main/java/com/nextcloud/client/etm/pages/EtmBackgroundJobsFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/SearchType.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13410 Sharing to our app can cause troubles and is not needed (use copy)
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.SendShareDialogTest_showDialog.png
  app/src/main/java/com/owncloud/android/ui/dialog/SendShareDialog.kt
Labels: 3. to review

#13419 BugFix - Setup Encryption Dialog Pop Up Twice
  app/src/main/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragment.kt
Labels: 3. to review

#13416 BugFix - NPE CommonAdapter
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review

#13415 BugFix - Preserve Selected Drawer Tab State When App Returns to Foreground
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review

#13414 BugFix - Resolve Keyboard Not Showing After Lock and Re-enable Password Entry After Delay
  app/src/main/java/com/owncloud/android/ui/activity/PassCodeActivity.kt
  app/src/main/java/com/owncloud/android/ui/components/PassCodeEditText.kt
Labels: 3. to review

#13257 Fix auto upload not working when "Also upload existing files" not checked
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
Labels: bug, 3. to review, feedback-requested

#12892 Add changelog for 3.29.0 RC1
  fastlane/CHANGELOG.md
Labels: 3. to review

#12820 Handle Missing DeepLinks
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review

#13232 Set content length to -1 for InputStream request bodies from the nextcloud/Android-SingleSignOn library
  app/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java
Labels: bug, 3. to review, performance: OOM :brain:, feedback-requested

#13108 mdm only needs to provide server address
  .idea/inspectionProfiles/ktlint.xml
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 3. to review

#13426 Fix - ActivitiesActivityIT Screentshot Tests
  app/src/androidTest/java/com/nextcloud/client/ActivitiesActivityIT.kt
Labels: 3. to review

#13422 Update library to 2024-08-18
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review, dependencies

#13164 use preview endpoint instead of thumbnail
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 3. to review

#13440 BugFix - Check Account Type Before Sync Operation Execution and Instead Crashing The App Inform User
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 3. to review

#13220 Feature Compatible File Names
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/82.json
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testNewFolderDialog.png
  app/src/androidTest/java/com/nextcloud/utils/FileNameValidatorTests.kt
  app/src/androidTest/java/com/owncloud/android/utils/EspressoIdlingResource.kt
  app/src/main/java/com/nextcloud/client/assistant/repository/AssistantMockRepository.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/CapabilityEntity.kt
  app/src/main/java/com/nextcloud/utils/extensions/OCCapabilityExtensions.kt
  app/src/main/java/com/nextcloud/utils/extensions/StringExtensions.kt
  app/src/main/java/com/nextcloud/utils/fileNameValidator/FileNameValidator.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/providers/DocumentsStorageProvider.java
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/TemplateAdapter.java
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseRichDocumentsTemplateDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/ChooseTemplateDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/RenamePublicShareDialogFragment.java
  app/src/main/java/com/owncloud/android/ui/dialog/RenamePublicShareDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/helpers/UriUploader.kt
  app/src/main/java/com/owncloud/android/utils/glide/HttpStreamFetcher.kt
  app/src/main/res/color/card_border_selector.xml
  app/src/main/res/drawable/rounded_rect_8dp.xml
  app/src/main/res/layout/template_button.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle.properties
  gradle/verification-metadata.xml
  scripts/analysis/detectWrongSettings.sh
  scripts/analysis/lint-results.txt
Labels: 3. to review

#13455 Refactor - Utils Code Cleanup
  app/src/androidTest/java/com/owncloud/android/utils/EncryptionTestUtils.kt
  app/src/androidTest/java/com/owncloud/android/utils/EncryptionUtilsV2IT.kt
  app/src/main/java/com/nextcloud/utils/extensions/DecryptedUserExtensions.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/e2e/v2/decrypted/DecryptedUser.kt
  app/src/main/java/com/owncloud/android/operations/CreateShareWithShareeOperation.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtilsV2.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13456 Refactor Setup Dialog
  app/src/androidTest/assets/credentials.json
  app/src/androidTest/java/com/nextcloud/utils/CertificateValidatorTests.kt
  app/src/androidTest/java/com/owncloud/android/datamodel/Credentials.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SetupEncryptionDialogFragmentIT.kt
  app/src/main/java/com/nextcloud/client/di/AppModule.java
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/utils/extensions/StringExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SetupEncryptionActivity.kt
  app/src/main/java/com/owncloud/android/ui/dialog/setupEncryption/CertificateValidator.kt
  app/src/main/java/com/owncloud/android/ui/dialog/setupEncryption/SetupEncryptionDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#13443 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#13468 3.29.3 Final
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30290390.txt
  fastlane/metadata/android/en-US/changelogs/30290390.txt.license
Labels: 3. to review

#13470 Update Android lib
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review
