Repository nextcloud/android, pull requests merged in 2024-01, with the labels that each got.

#12344 Transifex fails on renaming strings
  app/src/main/res/layout/etm_background_job_list_item.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12349 Fix collabora files not loading
  app/src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.kt
Labels: 3. to review, backport-request

#12304 On branded clients always use branding info
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
Labels: 3. to review, backport-request

#12360 Optional proxy support
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  app/src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  app/src/main/java/com/owncloud/android/utils/WebViewUtil.kt
  app/src/main/res/values/setup.xml
Labels: 3. to review

#12388 Bump androidPluginVersion to match library
  build.gradle
Labels: 3. to review

#12374 Update README: FAQ/known issues section + misc
  README.md
Labels: enhancement, 3. to review, documentation

#12408 Client cert
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/ui/NextcloudWebViewClient.kt
Labels: 3. to review

#12430 Add dependency checksums and signing key information
  .gitignore
  gradle.properties
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  scripts/checkIfRunDrone.sh
Labels: 4. to release, technical debt

#12443 larger splash screen icon
  app/src/main/res/values/dims.xml
Labels: backport-request

#12452 [stable-3.28] Remove user notification for autoupload edge cases
  app/src/main/java/com/nextcloud/client/jobs/FilesUploadWorker.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/db/UploadResult.java
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
  app/src/main/java/com/owncloud/android/utils/FilesUploadHelper.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#12459 Allow to add custom name to user agent
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/res/values/setup.xml
Labels: 3. to review, backport-request
