Repository nextcloud/android, pull requests merged in 2024-12, with the labels that each got.

#14114 Update icon to Material Symbol variant
  app/src/main/res/drawable/ic_external.xml
Labels: design, 3. to review, ui/ux, feature: sharing

#14031 BugFix - Add Missing Checks For Signature Verification
  app/src/main/java/com/owncloud/android/utils/EncryptionUtilsV2.kt
Labels: 3. to review

#14099 MANAGE_EXTERNAL_STORAGE not possible for gplay flavor anylonger
  app/src/gplay/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/java/com/nextcloud/utils/BuildHelper.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.kt
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#14081 fix(Thumbnails): Use local id rather than remote id
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: bug, 3. to review, backport-request, feature: previews and thumbnails

#14128 correct warning on delete/move
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review, backport-request

#14127 BugFix - Infinite Storage Permission Check
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
Labels: 3. to review, backport-request

#14142 Update library to 2024-12-08
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showFiles.png
  build.gradle
  gradle/verification-metadata.xml
Labels: 4. to release, dependencies

#14084 Upgrade The SDK Version to 35
  app/build.gradle
  app/src/main/java/com/nextcloud/client/appinfo/AppInfoImpl.kt
  app/src/main/java/com/owncloud/android/utils/WebViewUtil.kt
  appscan/build.gradle
Labels: 3. to review

#14089 Increase Build Speed
  app/build.gradle
  build.gradle
  gradle.properties
  gradle/verification-metadata.xml
Labels: 3. to review

#14051 Fix FileDetailFragment not starting
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
Labels: 3. to review, feedback-requested

#14140 Improve RTL support
  app/src/main/res/layout/activity_list_item.xml
  app/src/main/res/layout/dialog_data_storage_location.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/layout/notification_list_item.xml
  app/src/main/res/layout/trashbin_item.xml
  app/src/main/res/layout/version_list_item.xml
Labels: design, 3. to review

#14097 Fix BackupListFragmentIT SS Tests
  app/src/androidTest/java/com/owncloud/android/ui/fragment/BackupListFragmentIT.kt
Labels: 3. to review

#13680 Do Not Throw An Exception in SyncOperation
  app/src/main/java/com/owncloud/android/operations/common/SyncOperation.java
Labels: 3. to review

#13982 Add Bulk Action Support to Trashbin
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/client/di/ViewModelModule.kt
  app/src/main/java/com/nextcloud/ui/trashbinFileActions/TrashbinFileAction.kt
  app/src/main/java/com/nextcloud/ui/trashbinFileActions/TrashbinFileActionsBottomSheet.kt
  app/src/main/java/com/nextcloud/ui/trashbinFileActions/TrashbinFileActionsViewModel.kt
  app/src/main/java/com/nextcloud/utils/extensions/Extensions.kt
  app/src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  app/src/main/java/com/owncloud/android/ui/interfaces/TrashbinActivityInterface.java
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinContract.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinPresenter.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feature: trashbin, feedback-requested

#14169 update gem
  Gemfile.lock
Labels: 3. to review

#14185 ignore "implied quantity" on translated files
  app/lint.xml
Labels: 3. to review

#14161 BugFix - Get Files For Auto Upload
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
Labels: 3. to review

#14177 Add Backward Compatibility for Assistant API v1
  app/src/androidTest/java/com/nextcloud/client/assistant/AssistantRepositoryTests.kt
  app/src/main/java/com/nextcloud/client/assistant/AssistantViewModel.kt
  app/src/main/java/com/nextcloud/client/assistant/AsssistantScreen.kt
  app/src/main/java/com/nextcloud/client/assistant/extensions/TaskExtensions.kt
  app/src/main/java/com/nextcloud/client/assistant/model/ScreenOverlayState.kt
  app/src/main/java/com/nextcloud/client/assistant/repository/AssistantMockRepository.kt
  app/src/main/java/com/nextcloud/client/assistant/repository/AssistantRepository.kt
  app/src/main/java/com/nextcloud/client/assistant/repository/AssistantRepositoryType.kt
  app/src/main/java/com/nextcloud/client/assistant/task/TaskStatusView.kt
  app/src/main/java/com/nextcloud/client/assistant/task/TaskView.kt
  app/src/main/java/com/nextcloud/client/assistant/taskDetail/TaskDetailBottomSheet.kt
  app/src/main/java/com/nextcloud/client/assistant/taskTypes/TaskTypesRow.kt
  app/src/main/java/com/nextcloud/ui/composeActivity/ComposeActivity.kt
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#14146 Feature - Bottom Navigation View
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.kt
  app/src/main/java/com/owncloud/android/utils/DrawerMenuUtil.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtilsV2.kt
  app/src/main/res/layout/files.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#14196 Feature - Add Bottom Nav Bar To The Assistant Screen
  app/src/main/java/com/nextcloud/ui/composeActivity/ComposeActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/res/layout/activity_compose.xml
Labels: 3. to review

#14203 Check added for StringIndexOutOfBoundException
  app/src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
Labels: bug

#14072 Uniform icon colour
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.BackupListFragmentIT_showCalendarAndContactsList.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.BackupListFragmentIT_showCalendarList.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.BackupListFragmentIT_showContactList.png
  app/src/main/res/drawable-night/shared_via_users.xml
  app/src/main/res/drawable/all_files.xml
  app/src/main/res/drawable/file_calendar.xml
  app/src/main/res/drawable/ic_activity.xml
  app/src/main/res/drawable/ic_assistant.xml
  app/src/main/res/drawable/ic_user.xml
  app/src/main/res/drawable/shared_via_users.xml
Labels: 3. to review, feedback-requested
