Repository nextcloud/android, pull requests merged in 2024-05, with the labels that each got.

#12966 Fix Image Preview Header
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
Labels: 3. to review

#12930 Fix NullPointerException when invoking equals() on limitToPersonalFiles
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 3. to review

#12942 Bugfix E2E File Deletion For V1
  app/src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.java
  app/src/main/java/com/owncloud/android/operations/RemoveRemoteEncryptedFileOperation.kt
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review

#12934 Refactor Encrypted Upload
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/operations/e2e/E2EClientData.kt
  app/src/main/java/com/owncloud/android/operations/e2e/E2EData.kt
  app/src/main/java/com/owncloud/android/operations/e2e/E2EFiles.kt
Labels: 3. to review

#12969 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#12950 Give better feedback to the user for UNHANDLED_HTTP_CODE in PreviewMediaActivity
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
  app/src/main/java/com/owncloud/android/utils/ErrorMessageAdapter.java
  app/src/main/res/values/strings.xml
  gradle/verification-metadata.xml
Labels: 3. to review

#12792 Use non nullable context for PreviewMediaFragment
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
Labels: 3. to review

#13005 Update pdf icon color
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.UploadFilesActivityIT_noneSelected.png
  app/src/main/res/drawable/file_pdf.xml
Labels: enhancement, 3. to review, backport-request

#13016 Bugfix Media Item Delete Crash
  app/src/main/java/com/owncloud/android/ui/components/CustomViewPager.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.kt
  app/src/main/res/layout/preview_image_activity.xml
  app/src/main/res/layout/preview_image_fragment.xml
Labels: 3. to review

#13025 Login Flow V2 Fix Compatibility Problems With Some Browsers
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  scripts/analysis/lint-results.txt
Labels: 3. to review

#12964 Replaced own walkFileTree with correct implementation from nnio package.
  app/build.gradle
  app/src/main/java/com/owncloud/android/utils/FileUtil.java
  app/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  gradle/verification-metadata.xml
Labels: feedback-requested

#13026 Bugfix Android 14 Widgets
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetConfigurationActivity.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetProvider.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetService.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetUpdater.kt
Labels: 3. to review

#13002 fix(l10n): grammar fixes for plural usage
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#13013 Dismiss notification of successful downloads
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
Labels: 3. to review

#13041 fix(files): Use "favorites" versus "favourites" consistently
  app/src/main/res/values/strings.xml
Labels: bug, 3. to review, backport-request, feature: files

#13039 fix(files): "Create new" -> "New"
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testBottomSheet.png
  app/src/main/res/values/strings.xml
Labels: bug, 3. to review, backport-request, feature: files

#13040 fix(files): "Add folder info" -> "Add folder description"
  app/src/main/res/values/strings.xml
Labels: bug, 3. to review, feature: files

#13049 Annotate overridden function
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 4. to release, technical debt

#13037 Fix Crash Show Fragment During FileActivity Lifecycle Change
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
Labels: 3. to review

#13038 Check FragmentManager Before commit new FragmentTransaction
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review
