Repository nextcloud/android, pull requests merged in 2024-10, with the labels that each got.

#13610 check and show notification bell
  app/screenshots/gplay/debug/com.nextcloud.client.FileDisplayActivityScreenshotIT_drawer.png
  app/screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  app/src/main/java/com/nextcloud/client/files/DeepLinkConstants.kt
  app/src/main/java/com/nextcloud/utils/extensions/DrawerActivityExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/res/drawable/ic_arrow_back_foreground.xml
  app/src/main/res/drawable/nav_notifications.xml
  app/src/main/res/layout/notifications_layout.xml
  app/src/main/res/layout/toolbar_back_button.xml
  app/src/main/res/layout/toolbar_standard.xml
  app/src/main/res/menu/partial_drawer_entries.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13499 pause audio/video when swiping away
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.kt
Labels: 3. to review

#13671 Fix - FileDisplayActivityScreenshotIT Tests
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.kt
Labels: 3. to review

#13664 Update Dependency & Fix UI - Assistant Screen
  app/build.gradle
  app/src/main/java/com/nextcloud/client/assistant/AssistantViewModel.kt
  app/src/main/java/com/nextcloud/client/assistant/AsssistantScreen.kt
  app/src/main/java/com/nextcloud/client/assistant/component/CenterText.kt
  app/src/main/java/com/nextcloud/client/assistant/taskDetail/TaskDetailBottomSheet.kt
  app/src/main/java/com/nextcloud/ui/composeComponents/alertDialog/SimpleAlertDialog.kt
  app/src/main/java/com/owncloud/android/ui/activity/ToolbarActivity.java
  app/src/main/res/values/strings.xml
  gradle/verification-metadata.xml
Labels: 3. to review

#13612 BugFix - NPE internalFolderSyncTimestamp & File Existence Check
  app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
Labels: 3. to review, backport-request

#13624 Simplify FileDisplayActivity onBackPressed
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review

#13717 Update library to 2024-10-06
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#13727 3.30.1 RC1
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30301051.txt
  fastlane/metadata/android/en-US/changelogs/30301051.txt.license
Labels: 3. to review

#13730 Fix license name 3.30.1 rc1
  fastlane/metadata/android/en-US/changelogs/30300151.txt
  fastlane/metadata/android/en-US/changelogs/30300151.txt.license
Labels: 3. to review

#13695 Remove fido since we do not need it with login flow v2
  app/build.gradle
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/res/layout/dialog_set_status.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: 3. to review

#13599 BugFix - Filter Root
  app/src/main/java/com/nextcloud/model/OCFileFilterType.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review

#13746 Fix Crashes When Opening File Details from Media and Other Tabs
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Labels: 3. to review

#13501 Feature - Offline File Creation
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/85.json
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/androidTest/java/com/owncloud/android/UploadIT.java
  app/src/androidTest/java/com/owncloud/android/files/services/FileUploaderIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragmentTest.java
  app/src/androidTest/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragmentTest.kt
  app/src/debug/java/com/nextcloud/test/TestActivity.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/dao/OfflineOperationDao.kt
  app/src/main/java/com/nextcloud/client/database/entity/OfflineOperationEntity.kt
  app/src/main/java/com/nextcloud/client/database/migrations/DatabaseMigrationUtil.kt
  app/src/main/java/com/nextcloud/client/database/typeAdapter/OfflineOperationTypeAdapter.kt
  app/src/main/java/com/nextcloud/client/database/typeConverter/OfflineOperationTypeConverter.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  app/src/main/java/com/nextcloud/client/jobs/offlineOperations/OfflineOperationsWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/offlineOperations/repository/OfflineOperationsRepository.kt
  app/src/main/java/com/nextcloud/client/jobs/offlineOperations/repository/OfflineOperationsRepositoryType.kt
  app/src/main/java/com/nextcloud/client/network/ConnectivityService.java
  app/src/main/java/com/nextcloud/client/network/ConnectivityServiceImpl.java
  app/src/main/java/com/nextcloud/model/OfflineOperationType.kt
  app/src/main/java/com/nextcloud/receiver/NetworkChangeReceiver.kt
  app/src/main/java/com/nextcloud/receiver/OfflineOperationActionReceiver.kt
  app/src/main/java/com/nextcloud/utils/extensions/FragmentExtensions.kt
  app/src/main/java/com/nextcloud/utils/fileNameValidator/FileNameValidator.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCShareToOCFileConverter.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/dialog/RenameFileDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/SearchType.kt
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
  app/src/main/res/drawable/ic_cloud_sync.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13745 BugFix - Check Existence of OCUpload
  app/src/main/java/com/owncloud/android/ui/adapter/UploadListAdapter.java
Labels: 3. to review

#13767 Add changelog for 3.30.1
  CHANGELOG.md
Labels: 3. to review

#13847 2way sync: sync only on wifi
  app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
Labels: backport-request

#13843 Add changelog for 3.30.2
  CHANGELOG.md
Labels: 3. to review

#13850 Add changelog for 3.30.3
  CHANGELOG.md
Labels: 3. to review

#13897 BugFix - Unnecessary Sync
  app/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
Labels: 3. to review, backport-request

#13494 2way sync: Better view handling
  app/src/main/java/com/owncloud/android/ui/activity/InternalTwoWaySyncActivity.kt
  app/src/main/res/layout/internal_two_way_sync_layout.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#13895 BugFix / AutoRename Capability Order
  app/src/androidTest/java/com/nextcloud/utils/AutoRenameTests.kt
  app/src/main/java/com/nextcloud/utils/autoRename/AutoRename.kt
Labels: 3. to review, backport-request

#13884 Improve Two Way Sync Behaviour
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/InternalTwoWaySyncWork.kt
  app/src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/java/com/nextcloud/utils/extensions/ContextExtensions.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/ui/activity/InternalTwoWaySyncActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/InternalTwoWaySyncAdapter.kt
  app/src/main/res/layout/internal_two_way_sync_layout.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request, feature: sync

#13907 Fix XML SPDX header
  CONTRIBUTING.md
  app/lint.xml
  app/src/main/res/layout/notification_list_item.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/dashboard_widget_info.xml
  app/src/main/res/xml/exposed_filepaths.xml
  app/src/main/res/xml/network_security_config.xml
Labels: 3. to review

#13921 3.30.4
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30300490.txt
  fastlane/metadata/android/en-US/changelogs/30300490.txt.license
Labels: 3. to review
