Repository nextcloud/android, pull requests merged in 2024-03, with the labels that each got.

#12640 Update library 2024-03-04
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#12577 Fix Path Traversal To Internal File ExFiltration
  app/src/androidTest/java/com/owncloud/android/ui/helpers/UriUploaderIT.kt
  app/src/main/java/com/owncloud/android/ui/helpers/UriUploader.kt
Labels: 3. to review

#12664 Add SPDX header from sync
  .github/workflows/pr-feedback.yml
Labels: technical debt, sync

#12276 Fix infinite loading of folders in shared tab
  app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt
Labels: 3. to review

#12668 Bugfix E2E folder file creation
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review

#12406 Fix ReceiveExternalFilesActivity intent
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 3. to review

#12695 pin ubuntu dependency
  .devcontainer/Dockerfile
Labels: technical debt

#12583 Fix Crash When Write Activities From Random Any File
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
Labels: 3. to review

#12685 Fix check if share already exists and give feedback
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/res/values/strings.xml
Labels: 4. to release

#12621 Fix crash when restoring contacts
  app/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.kt
Labels: 3. to review

#12591 Fix MaterialToolbar Crash
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 3. to review

#12128 Convert Authenticator to Kotlin
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.kt
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.java
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorUrlUtils.kt
  app/src/test/java/com/owncloud/android/authentication/AuthenticatorUrlUtilsTest.java
Labels: 4. to release

#12619 Fix back button in trash bin
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinContract.kt
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinPresenter.kt
Labels: 3. to review

#12712 Update dependency com.android.tools.build:gradle to v8.3.1
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review, dependencies, technical debt

#12688 Update mimetype icons
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepNew.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testBottomSheet.png
  app/src/main/res/drawable/file_analytics.xml
  app/src/main/res/drawable/file_doc.xml
  app/src/main/res/drawable/file_image.xml
  app/src/main/res/drawable/file_movie.xml
  app/src/main/res/drawable/file_pdf.xml
  app/src/main/res/drawable/file_ppt.xml
  app/src/main/res/drawable/file_text.xml
  app/src/main/res/drawable/file_xls.xml
Labels: 3. to review

#12717 500 when metadata does not exist
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review, backport-request

#12710 Bug-fix Open Image Inside Encrypted Folder
  app/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
Labels: 3. to review, backport-request

#12723 Bug-fix Encrypted Large File Upload
  app/src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  app/src/main/java/com/owncloud/android/datamodel/e2e/v1/encrypted/EncryptedFile.kt
  app/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review, backport-request

#12719 Try to only process changed files for auto upload
  app/src/androidTest/java/com/nextcloud/client/jobs/BackgroundJobManagerTest.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/ContentObserverWork.kt
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/SyncedFolder.java
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
Labels: backport-request

#12767 Fix strings
  app/src/main/res/values/strings.xml
Labels: 4. to release

#12768 Add SPDX header
  app/src/main/res/values/strings.xml
Labels: 4. to release, technical debt

#12769 Add SPDX Header
  .reuse/dep5
  LICENSES/GPL-3.0-or-later.txt
  app/src/androidTest/AndroidManifest.xml
  app/src/debug/AndroidManifest.xml
  app/src/gplay/AndroidManifest.xml
  app/src/huawei/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/animator/appbar_elevation_off.xml
  app/src/main/res/animator/appbar_elevation_on.xml
  app/src/main/res/color/menu_item_text_color.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/bools.xml
  app/src/qa/AndroidManifest.xml
  appscan/src/main/AndroidManifest.xml
Labels: 4. to release, technical debt
