Repository nextcloud/android, pull requests merged in 2024-06, with the labels that each got.

#12907 Unify Notifications
  app/src/main/java/com/nextcloud/client/jobs/download/DownloadNotificationManager.kt
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/notification/WorkerNotificationManager.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/ui/notifications/NotificationUtils.java
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-b+en+001/strings.xml
  app/src/main/res/values-cs-rCZ/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk-rSK/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rHK/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13057 Added deep link support for screens navigation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/files/DeepLinkConstants.kt
  app/src/main/java/com/nextcloud/client/files/DeepLinkHandler.kt
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: enhancement, 3. to review

#13070 Fix State Loss Crash For SyncedFolderPreferencesDialogFragment
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SyncedFolderPreferencesDialogFragment.kt
Labels: 3. to review

#13065 Bugfix Start Foreground Service When App In Foreground
  app/build.gradle
  app/src/main/java/com/nextcloud/client/jobs/transfer/FileTransferService.kt
  app/src/main/java/com/nextcloud/utils/ForegroundServiceHelper.kt
  gradle/verification-metadata.xml
Labels: 3. to review

#13075 Bugfix Add ActivityExtensions for Checking Dialog Fragments
  app/src/main/java/com/nextcloud/utils/extensions/ActivityExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 3. to review

#13073 Bugfix Fix Rare lateinit Crash on File Download Worker
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
Labels: 3. to review

#13080 Fix Wrong Context Usage
  app/build.gradle
  app/src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  app/src/main/java/com/owncloud/android/MainApp.java
  scripts/analysis/lint-results.txt
Labels: 3. to review

#13081 Show Snackbar Message Instead Throwing Exception For Sync Folder Operations
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13076 Bugfix NPE & Convert to Kotlin SSL Untrusted Cert Dialog
  app/src/main/java/com/owncloud/android/ui/adapter/CertificateCombinedExceptionViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/SslCertificateViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/SslErrorViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/X509CertificateViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java
  app/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.kt
Labels: 3. to review

#13084 Bugfix General Crash Fixes
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/ui/unifiedsearch/UnifiedSearchRemoteRepository.kt
Labels: 3. to review

#13089 Update library to 2024-06-10
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#12266 Deprecate OwncloudClient - Notifications
  app/src/gplay/java/com/owncloud/android/utils/PushUtils.java
  app/src/main/java/com/nextcloud/client/jobs/NotificationWork.kt
  app/src/main/java/com/nextcloud/utils/extensions/OwnCloudClientExtensions.kt
  app/src/main/java/com/owncloud/android/services/OperationsService.java
  app/src/main/java/com/owncloud/android/ui/activity/NotificationsActivity.kt
  app/src/main/java/com/owncloud/android/ui/adapter/NotificationListAdapter.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/DeleteAllNotificationsTask.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/DeleteNotificationTask.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/NotificationExecuteActionTask.java
  build.gradle
  gradle/verification-metadata.xml
  scripts/analysis/detectWrongSettings.sh
Labels: 3. to review, feedback-requested

#13092 Bugfix Audio File Preview
  app/src/main/java/com/nextcloud/client/media/PlayerService.kt
  app/src/main/java/com/nextcloud/client/media/PlayerServiceConnection.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/res/layout/activity_preview_media.xml
Labels: 3. to review

#13093 Migrate to View Pager 2 & Crash-Fix | Farewell to ViewPager 1 🥳
  app/src/main/java/com/nextcloud/client/onboarding/FirstRunActivity.kt
  app/src/main/java/com/nextcloud/client/onboarding/WhatsNewActivity.kt
  app/src/main/java/com/owncloud/android/ui/adapter/FeaturesViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/FeaturesWebViewAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/FileDetailTabAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.kt
  app/src/main/res/layout/file_details_fragment.xml
  app/src/main/res/layout/first_run_activity.xml
  app/src/main/res/layout/whats_new_activity.xml
  gradle/verification-metadata.xml
Labels: 3. to review

#12464 Deprecate OwncloudClient - Comments
  app/src/main/java/com/owncloud/android/operations/CommentFileOperation.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailActivitiesFragment.java
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review, feedback-requested

#13109 Use same logo size
  app/screenshots/gplay/debug/com.nextcloud.client.AuthenticatorActivityIT_login.png
  app/screenshots/gplay/debug/com.nextcloud.client.FirstRunActivityIT_open.png
  app/src/main/res/layout/account_setup.xml
  app/src/main/res/layout/whats_new_element.xml
Labels: 3. to review, backport-request

#13091 new min server is NC17
  app/src/androidTest/java/com/owncloud/android/utils/theme/CapabilityUtilsIT.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 3. to review

#13074 Bugfix Fix NPE FileDataStorageManager
  app/src/main/java/com/nextcloud/client/account/CurrentAccountProvider.java
  app/src/main/java/com/nextcloud/client/account/UserAccountManagerImpl.java
  app/src/main/java/com/nextcloud/client/di/AppModule.java
  app/src/main/java/com/nextcloud/client/mixins/SessionMixin.kt
  app/src/main/java/com/nextcloud/utils/extensions/AccountExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  app/src/main/res/values/strings.xml
  app/src/test/java/com/nextcloud/client/mixins/SessionMixinTest.kt
Labels: 3. to review

#13133 Use Linux runner
  .github/workflows/screenShotTest.yml
Labels: 3. to review

#13132 Bug-Fix Add Last Media Item Position
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
Labels: 3. to review

#13135 use WeakReference for Context
  app/src/main/java/com/owncloud/android/MainApp.java
Labels: 3. to review

#13143 Convert Preview Media Fragment to Kotlin
  app/src/main/java/com/nextcloud/ui/fileactions/FileActionsBottomSheet.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#13145 Bug-Fix Percentage Value During Download or Upload
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/nextcloud/utils/extensions/AccountExtensions.kt
  app/src/main/java/com/nextcloud/utils/extensions/OnDataTransferProgressListenerExtensions.kt
Labels: 3. to review

#12995 Added direct upload from video camera
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/res/values-b+en+001/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 3. to review, feedback-requested

#13165 fix dav4jvm checksum
  gradle/verification-metadata.xml
Labels: backport-request

#13176 Test against stable29
  .drone.yml
Labels: 2. developing

#13157 Convert Preview Image Activity to Kotlin
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
Labels: 3. to review

#13159 Handle Login Flow V2 Response
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/res/values/strings.xml
Labels: 3. to review

#13184 Bugfix Unified Search Load More
  app/src/main/java/com/owncloud/android/ui/adapter/UnifiedSearchListAdapter.kt
  app/src/main/java/com/owncloud/android/ui/unifiedsearch/UnifiedSearchViewModel.kt
Labels: 3. to review

#13167 Crash Fix & Convert to Kotlin Synced Folder Adapter
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/SyncedFolderAdapter.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#13158 fix for media tab not showing thumbnails when image not in cache manager
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 3. to review

#13191 Add changelog for 3.29.1
  CHANGELOG.md
Labels: 3. to review

#13193 Auto Close File Streams
  app/src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
  app/src/main/java/com/owncloud/android/ui/adapter/PrintAdapter.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 3. to review

#13187 Convert Preview Image Fragment to Kotlin
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageErrorFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageErrorFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#13166 Share Link Crash Fix
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review
