Repository nextcloud/android, pull requests merged in 2025-08, with the labels that each got.

#15175 Replace E2EE Async Tasks with Coroutines
  app/src/main/java/com/owncloud/android/ui/dialog/setupEncryption/SetupEncryptionDialogFragment.kt
Labels: 3. to review, technical debt, performance 🚀

#14757 BugFix - CalendarImportWork
  app/screenshots/generic/debug/com.owncloud.android.ui.activity.ContactsPreferenceActivityIT_openContactsPreference.png
  app/src/main/java/com/nextcloud/client/jobs/CalendarImportWork.kt
  app/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.kt
Labels: 3. to review, ux-enhancement

#15127 Redirect to All Files from FileDisplayActivity's Fragments
  app/src/main/java/com/nextcloud/utils/extensions/DrawerActivityExtensions.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/BackupFragment.kt
Labels: 3. to review, backport-request

#15296 chore(deps): Update AGP to 8.12.0
  build.gradle
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 3. to review, dependencies

#15303 Update to Gradle 9.0
  app/src/main/res/values/strings.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: 3. to review, dependencies

#15302 Fix CI
  app/build.gradle
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 3. to review

#15318 Fix grid view spacing
  app/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ViewType.java
  app/src/main/res/layout/grid_image.xml
  app/src/main/res/layout/grid_item.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review

#15335 manual backport - [stable-3.32] Add client side encryption to use sha256 hash algorithm
  app/src/androidTest/java/com/owncloud/android/util/EncryptionTestIT.java
  app/src/main/java/com/nextcloud/utils/extensions/StringExtensions.kt
  app/src/main/java/com/owncloud/android/ui/dialog/setupEncryption/CertificateValidator.kt
  app/src/main/java/com/owncloud/android/ui/dialog/setupEncryption/SetupEncryptionDialogFragment.kt
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
  app/src/main/java/com/owncloud/android/utils/EncryptionUtilsV2.kt
  app/src/main/java/com/owncloud/android/utils/crypto/CryptoError.kt
  app/src/main/java/com/owncloud/android/utils/crypto/CryptoHelper.kt
  app/src/main/java/com/owncloud/android/utils/crypto/CryptoStringUtils.kt
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#15338 BugFix - AutoRename Folder names are lowercased after creation
  app/src/androidTest/java/com/nextcloud/utils/AutoRenameTests.kt
  app/src/main/java/com/nextcloud/utils/autoRename/AutoRename.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.kt
Labels: 3. to review, backport-request

#15273 File Upload Worker Batch Support
  app/src/main/java/com/nextcloud/client/database/migrations/Migration88to89.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/owncloud/android/ui/activity/UploadFilesActivity.java
Labels: 3. to review

#15350 fix: upload progress
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to review, backport-request

#15240 Check Storage Permission Before Upload
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/operations/upload/UploadFileBroadcastReceiver.kt
  app/src/main/java/com/owncloud/android/operations/upload/UploadFileBroadcastReceiverActions.kt
  app/src/main/java/com/owncloud/android/operations/upload/UploadFileException.kt
  app/src/main/java/com/owncloud/android/operations/upload/UploadFileOperationExtensions.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request, ux-enhancement

#15366 switch to correct package name, since renovate complained
  app/build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#15384 fix: settings activity back button behaviour
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 3. to review

#15351 fix: file display activity intent handling
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
Labels: 3. to review

#15400 fix: file display activity restart intent handling
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
Labels: 3. to review, backport-request

#14948 Various Small Optimizations
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/files/services/IndexedForest.java
  app/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/StorageMigration.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/ActivityAndVersionListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/DiskLruImageCache.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/LoadContactsTask.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
  app/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  app/src/main/java/third_parties/ezvcard_android/ContactOperations.java
  app/src/main/java/third_parties/ezvcard_android/DataMappings.java
Labels: 3. to review, feedback-requested

#15428 fix: extended list fragment current npe
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.kt
Labels: 3. to review

#15430 add: version bumps to android 8.1
  app/build.gradle
  app/src/androidTest/java/com/owncloud/android/datamodel/ContentResolverHelperIT.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
  app/src/main/res/values-v27/styles.xml
  app/src/main/res/values/styles.xml
  appscan/build.gradle
Labels: 3. to review

#15435 add: 3.34.0 next minor release
  app/build.gradle
Labels: 3. to review

#15444 chore: update dependencies to TOML format
  app/build.gradle
  gradle/libs.versions.toml
  gradle/verification-metadata.xml
Labels: 3. to review

#15392 fix: share updating
  app/src/main/java/com/owncloud/android/operations/UpdateShareInfoOperation.java
  app/src/main/java/com/owncloud/android/services/OperationsService.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
Labels: 3. to review

#15438 rename to avoid translation problems
  app/src/main/res/layout/account_item.xml
  app/src/main/res/layout/activity_list_item.xml
  app/src/main/res/layout/activity_list_item_header.xml
  app/src/main/res/layout/deep_link_login.xml
  app/src/main/res/layout/file_details_fragment.xml
  app/src/main/res/layout/grid_image.xml
  app/src/main/res/layout/grid_item.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/layout/notification_list_item.xml
  app/src/main/res/layout/richdocuments_webview.xml
  app/src/main/res/layout/share_activity.xml
  app/src/main/res/layout/synced_folders_item_header.xml
  app/src/main/res/layout/synced_folders_settings_layout.xml
  app/src/main/res/layout/trashbin_item.xml
  app/src/main/res/layout/upload_list_item.xml
  app/src/main/res/layout/uploader_list_item_layout.xml
  app/src/main/res/values/strings.xml
  gradle/verification-metadata.xml
Labels: 3. to review, backport-request

#15462 [stable-3.33] fix: share link label
  app/src/main/java/com/owncloud/android/ui/adapter/LinkShareViewHolder.kt
Labels: 3. to review

#15464 feat: preview image activity better display cutout handling
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
Labels: 3. to review
