Repository nextcloud/android, pull requests merged in 2025-06, with the labels that each got.

#14936 BugFix - Thumbnail not updating when replacing remote file with new local file
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
Labels: 3. to review

#14953 Fail on missing migration
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
Labels: 3. to review

#14958 Remove unused functions and variables in OCFileListAdapter
  app/src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
Labels: 3. to review

#14583 Use of Try-With-Resources
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java
  app/src/main/java/com/owncloud/android/ui/decoration/SimpleListItemDividerDecoration.java
  app/src/main/java/third_parties/sufficientlysecure/AndroidCalendar.java
Labels: 3. to review, technical debt, feedback-requested

#14946 Activity/Trashbin: Show correct info if server not reachable
  app/src/main/java/com/owncloud/android/ui/activities/ActivitiesActivity.java
  app/src/main/java/com/owncloud/android/ui/trashbin/TrashbinActivity.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#15008 3.32.0 RC1
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30320051.txt
  fastlane/metadata/android/en-US/changelogs/30320051.txt.license
Labels: 3. to review

#15010 BugFix - Add Manual Migration 88 to 89
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/migrations/DatabaseMigrationUtil.kt
  app/src/main/java/com/nextcloud/client/database/migrations/Migration88to89.kt
  app/src/main/java/com/nextcloud/client/database/migrations/model/SQLiteColumnType.kt
Labels: 3. to review, backport-request

#14981 Check User Before Upload Files
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review, backport-request

#14997 store upload timestamp directly after upload
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to review, backport-request

#14827 Fix error handling issues
  app/src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
Labels: 3. to review, feedback-requested

#15065 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#15068 Add alternative checksum
  gradle/verification-metadata.xml
Labels: 3. to review
