Repository nextcloud/android, pull requests merged in 2025-01, with the labels that each got.

#14250 check if library commit is correct
  scripts/analysis/detectWrongSettings.sh
Labels: 3. to review

#14269 Fix - File Details Screen Share Buttons Visibility
  app/src/main/res/layout/file_details_sharing_process_fragment.xml
  app/src/main/res/values/dims.xml
Labels: 3. to review

#14180 fix: FilesSyncHelper: Shuffle array after null check, else NullPointerException is thrown
  app/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java
  app/src/test/java/com/owncloud/android/utils/FilesSyncHelperTest.java
Labels: bug, 3. to review, feedback-requested

#14209 Convert ManageAccountsActivity to Kotlin
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  app/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/ManageAccountsActivity.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#14151 Improve CI Performance
  .devcontainer/Dockerfile
  .github/workflows/analysis.yml
  .github/workflows/assembleFlavors.yml
  .github/workflows/qa.yml
  .github/workflows/screenShotTest.yml
Labels: 3. to review

#13069 Upload Files: add another test
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.UploadFilesActivityIT_selectAll.png
  app/src/androidTest/java/com/owncloud/android/AbstractIT.java
  app/src/androidTest/java/com/owncloud/android/ui/activity/UploadFilesActivityIT.kt
Labels: 3. to review

#14322 Add content description
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/res/layout/file_details_fragment.xml
  app/src/main/res/layout/file_details_sharing_fragment.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, accessibility

#14335 Migrate to new action
  .github/workflows/unit-tests.yml
Labels: 3. to review, dependencies

#14270 BugFix - ThumbnailCacheManager Software rendering doesn't support hardware bitmaps
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
Labels: 3. to review, backport-request

#14348 BugFix - GPlay Variant E2E Dialog
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review, backport-request

#14332 Bugfix - E2E Share File From Other Apps
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
Labels: 3. to review, backport-request

#14392 3.30.8 RC1
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30300851.txt
  fastlane/metadata/android/en-US/changelogs/30300851.txt.license
Labels: 3. to review

#14396 GPLAY: do not show our custom uploader, due to lack of permission
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testBottomSheet.png
  app/src/main/java/com/nextcloud/utils/BuildHelper.kt
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  app/src/main/res/layout/file_list_actions_bottom_sheet_fragment.xml
Labels: 3. to review, backport-request

#14247 request media_location
  app/src/gplay/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  app/src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
  app/src/main/res/values/strings.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, backport-request

#14405 Don't Ask ACCESS_MEDIA_LOCATION Permission If App Already Has Full Disk Access
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
Labels: 3. to review, backport-request

#14407 Request Media Location and Storage Permissions in the Action of the ReEnableAutoUploadDialog
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#14419 clarify when permission dialog is shown
  app/src/main/res/values/strings.xml
Labels: backport-request

#14421 BugFix - Don't Show Auto Upload Notification More Than Once
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
Labels: 3. to review

#14424 3.30.8 RC2
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30300852.txt
  fastlane/metadata/android/en-US/changelogs/30300852.txt.license
Labels: 3. to review

#14432 Show auto upload notification in all activities
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#14434 3.30.8
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30300890.txt
  fastlane/metadata/android/en-US/changelogs/30300890.txt.license
Labels: 3. to review

#14384 Hard-code ignore files with prefix .trashed
  app/src/androidTest/java/com/owncloud/android/utils/SyncedFolderUtilsTest.kt
  app/src/main/java/com/owncloud/android/utils/SyncedFolderUtils.kt
Labels: enhancement, 3. to review

#14438 Revert Get Files For Auto Upload
  app/src/main/java/com/nextcloud/client/jobs/FilesSyncWork.kt
  app/src/main/java/com/owncloud/android/datamodel/FilesystemDataProvider.java
Labels: 3. to review

#14354 BugFix - TaskProcessingAPI
  app/src/main/java/com/nextcloud/client/assistant/repository/AssistantMockRepository.kt
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#14343 Remove Bottom Navigation Bar From File Details
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Labels: 3. to review

#14339 Feature - Add Tag Color
  app/src/androidTest/java/com/owncloud/android/ui/fragment/OCFileListFragmentStaticServerIT.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#14178 Feature - Recommended Files
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/86.json
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showRichWorkspace.png
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/dao/FileDao.kt
  app/src/main/java/com/nextcloud/client/database/entity/CapabilityEntity.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/adapter/RecommendedFilesAdapter.kt
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/drawable/ic_dots_horizontal.xml
  app/src/main/res/layout/list_header.xml
  app/src/main/res/layout/recommended_files_list_item.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
  gradle/verification-metadata.xml
Labels: enhancement, design, 3. to review, 🍀 2025-Spring

#14412 Support Files Download Limits
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/86.json
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesDownloadLimit.png
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentIT.kt
  app/src/main/java/com/nextcloud/client/database/entity/CapabilityEntity.kt
  app/src/main/java/com/nextcloud/client/database/entity/ShareEntity.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/operations/GetFilesDownloadLimitOperation.kt
  app/src/main/java/com/owncloud/android/operations/GetSharesForFileOperation.java
  app/src/main/java/com/owncloud/android/operations/GetSharesForFileOperation.kt
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/SetFilesDownloadLimitOperation.kt
  app/src/main/java/com/owncloud/android/services/OperationsService.java
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/LinkShareViewHolder.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/res/layout/file_details_share_link_share_item.xml
  app/src/main/res/layout/file_details_sharing_process_fragment.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#14447 bump MINIMUM_SUPPORTED_SERVER_VERSION
  app/src/androidTest/java/com/nextcloud/client/account/RegisteredUserTest.kt
  app/src/androidTest/java/com/owncloud/android/utils/theme/CapabilityUtilsIT.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
Labels: 3. to review

#14448 drop Android 7.0 support
  app/build.gradle
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/dialog/SyncFileNotEnoughSpaceDialogFragment.kt
  appscan/build.gradle
Labels: 3. to review

#14450 use latest lib
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#14445 Bump Nextcloud version to 30 in drone.yml
  .drone.yml
Labels: 3. to review

#14446 Bump OUTDATED_SERVER_VERSION
  app/src/androidTest/java/com/owncloud/android/utils/theme/CapabilityUtilsIT.kt
  app/src/main/java/com/owncloud/android/MainApp.java
Labels: 3. to review

#14452 Update Scripts for 3.31.0
  scripts/analysis/analysis-wrapper.sh
  scripts/analysis/getBranchName.sh
Labels: 3. to review

#14451 3.31.0 RC1
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30310051.txt
  fastlane/metadata/android/en-US/changelogs/30310051.txt.license
Labels: 3. to review

#14453 do not continue when server fails
  app/src/main/java/com/owncloud/android/MainApp.java
  scripts/runCombinedTest.sh
Labels: 2. developing

#14454 Use 2.20.0 RC1 Android-Library
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#14455 check library commit on correct branch
  scripts/analysis/detectWrongSettings.sh
Labels: 3. to review, backport-request

#14456 Upgrade to Next Major Version
  app/build.gradle
Labels: 3. to review
