Repository nextcloud/android, pull requests merged in 2025-02, with the labels that each got.

#14159 ToS
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/dialog/TermsOfServiceDialog.kt
  app/src/main/res/layout/dialog_show_tos.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review, backport-request, 🍀 2025-Spring

#14514 Dismiss Conflict Resolve Dialog Notification After User's Action
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
Labels: 3. to review, backport-request

#14485 BugFix - Observe Download State In Encrypted Folder
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.kt
Labels: 3. to review, backport-request

#14364 Stop Uploads When the Device Doesn’t Have an Internet Connection
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#14498 BugFix - E2EE Delete File
  app/src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
Labels: 3. to review, backport-request

#14461 Remove Login Flow v1
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
  app/src/main/java/com/owncloud/android/ui/activity/ExternalSiteWebView.java
  app/src/main/java/com/owncloud/android/utils/WebViewUtil.kt
  app/src/main/res/layout/account_setup_webview.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#14524 Check API Level for READ_MEDIA_VISUAL_USER_SELECTED Permission
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
  scripts/analysis/lint-results.txt
Labels: 3. to review

#14501 Fix Image Scaling/Rotating
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: bug, 3. to review

#14539 BugFix - Add Missing mTransferWasRequested
  app/src/main/java/com/owncloud/android/operations/SynchronizeFileOperation.java
Labels: 3. to review, backport-request

#14536 BugFix - Check Device Credentials Existance
  app/src/main/java/com/nextcloud/client/preferences/AppPreferences.java
  app/src/main/java/com/nextcloud/client/preferences/AppPreferencesImpl.java
  app/src/main/java/com/owncloud/android/authentication/PassCodeManager.kt
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
Labels: 3. to review

#14410 Don't Show Failed Upload Message For Same File and Handle Local Behavior
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  app/src/main/res/values/strings.xml
Labels: 3. to review

#14546 BugFix - Don't Set Icon If Thumbnail Exists & Handle Thumbnails Properly
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepBoth.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_keepExisting.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.activity.ConflictsResolveActivityIT_screenshotTextFiles.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testFileActionsBottomSheet.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showFiles.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showSharedFiles.png
  app/src/androidTest/java/com/owncloud/android/ui/activity/ConflictsResolveActivityIT.java
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.java
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentIT.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/java/com/owncloud/android/utils/MimeTypeUtil.java
Labels: 3. to review, backport-request

#14577 Enhance CropImageActivity
  app/src/main/AndroidManifest.xml
Labels: backport-request

#14559 Simplified share layout
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesDownloadLimit.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileAllShareTypes.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileNone.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.FileDetailSharingFragmentIT_listSharesFileResharingNotAllowed.png
  app/src/androidTest/java/com/owncloud/android/ui/fragment/FileDetailSharingFragmentIT.kt
  app/src/main/java/com/owncloud/android/datamodel/SharesType.kt
  app/src/main/java/com/owncloud/android/ui/adapter/ShareViewHolder.java
  app/src/main/java/com/owncloud/android/ui/adapter/ShareeListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingMenuBottomSheetDialog.java
  app/src/main/res/layout/file_details_sharing_fragment.xml
  app/src/main/res/layout/file_details_sharing_menu_bottom_sheet_fragment.xml
  app/src/main/res/values/setup.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/owncloud/android/ui/adapter/ShareeListAdapterTest.kt
  scripts/androidScreenshotTest
Labels: 3. to review, backport-request

#14578 enhance clipboard
  app/src/main/java/com/nextcloud/client/jobs/clipboard/ClipboardClearWorker.kt
  app/src/main/java/com/owncloud/android/utils/ClipboardUtil.kt
Labels: backport-request

#14593 3.31.0
  app/build.gradle
  app/src/main/res/values/setup.xml
  fastlane/metadata/android/en-US/changelogs/30310090.txt
  fastlane/metadata/android/en-US/changelogs/30310090.txt.license
Labels: 3. to review

#14581 remove methods that only call super
  app/src/main/java/com/owncloud/android/ui/activity/UploadListActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
Labels: 3. to review

#14585 Fix C-Style Arrays
  app/src/main/java/com/owncloud/android/datastorage/providers/AbstractCommandLineStoragePoint.java
  app/src/main/java/com/owncloud/android/datastorage/providers/MountCommandStoragePointProvider.java
  app/src/main/java/com/owncloud/android/datastorage/providers/VDCStoragePointProvider.java
  app/src/main/java/com/owncloud/android/ui/activity/ReceiveExternalFilesActivity.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/java/third_parties/ezvcard_android/ContactOperations.java
Labels: 3. to review, technical debt

#14588 Use of Pattern Variables
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/db/OCUpload.java
  app/src/main/java/com/owncloud/android/ui/ThemeableSwitchPreference.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/ActivityAndVersionListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/ActivityListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/LocalFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/TrashbinListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsAccount.java
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 3. to review, technical debt

#14568 Fix - onSyncFolderSettingsClick ANR
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
Labels: 3. to review

#14556 Update Thumbnail After Resolving Conflict
  app/src/main/java/com/owncloud/android/ui/activity/ConflictsResolveActivity.kt
Labels: 3. to review
