Repository nextcloud/android, pull requests merged in 2025-05, with the labels that each got.

#14828 Remove unused imports
  app/src/androidTest/java/com/owncloud/android/AbstractOnServerIT.java
  app/src/androidTest/java/com/owncloud/android/UploadIT.java
  app/src/main/java/com/nextcloud/client/account/CurrentAccountProvider.java
  app/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
  app/src/main/java/com/owncloud/android/operations/RemoveFileOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  app/src/main/java/third_parties/ezvcard_android/ContactOperations.java
  app/src/main/java/third_parties/sufficientlysecure/SaveCalendar.java
  app/src/test/java/com/owncloud/android/utils/FilesSyncHelperTest.java
Labels: 3. to review

#14823 Handle Sample Bitmap Decoding Better
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 3. to review

#14840 Fix Lint Result
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
  scripts/analysis/lint-results.txt
Labels: 3. to review

#14775 Handle Downloaded File Open Intent
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java
  app/src/main/res/values/arrays.xml
Labels: 3. to review, backport-request

#14703 Hide Info Box in PreviewMediaActivity
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
Labels: 3. to review, backport-request

#13310 persist upload timestamp
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/89.json
  app/src/androidTest/java/com/owncloud/android/UploadIT.java
  app/src/androidTest/java/com/owncloud/android/datamodel/OCFileUnitTest.java
  app/src/main/java/com/nextcloud/client/database/entity/FileEntity.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/utils/FileStorageUtils.java
Labels: 3. to review, backport-request

#14903 Re-enable Permission
  app/build.gradle
  app/src/gplay/AndroidManifest.xml
  app/src/main/java/com/nextcloud/client/jobs/MediaFoldersDetectionWork.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListBottomSheetDialog.java
  build.gradle
  fastlane/metadata/android/en-US/changelogs/30310251.txt
  fastlane/metadata/android/en-US/changelogs/30310251.txt.license
  fastlane/metadata/android/en-US/changelogs/30310290.txt
  fastlane/metadata/android/en-US/changelogs/30310290.txt.license
  gradle/verification-metadata.xml
Labels: 3. to review

#14880 Fix remove files
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.kt
Labels: 3. to review, backport-request

#14901 Fix Simple signup
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
  app/src/main/res/layout/account_setup_webview.xml
Labels: 3. to review, backport-request

#14916 3.31.3 RC1
  app/build.gradle
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testBottomSheet.png
  fastlane/metadata/android/en-US/changelogs/30310351.txt
  fastlane/metadata/android/en-US/changelogs/30310351.txt.license
  gradle/verification-metadata.xml
Labels: 3. to review

#14819 Add checks for DecryptedFolderMetadataFile object to see if actually encrypted
  app/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
Labels: feedback-requested

#14897 ThumbnailsCacheManager - AsyncTask to Executor
  app/src/androidTest/java/com/owncloud/android/ui/fragment/GalleryFragmentIT.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/datamodel/ThumbnailsCacheManager.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/UnifiedSearchListAdapter.kt
  app/src/main/res/values/dims.xml
Labels: 3. to review

#14733 Fix Image Loading When Offline
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: bug, 3. to review, feedback-requested, feature: sync

#14900 Decode and Scale Together
  app/src/main/java/com/owncloud/android/utils/BitmapUtils.java
Labels: 3. to review
