Repository nextcloud/android, pull requests merged in 2025-03, with the labels that each got.

#13975 Improve File Download Worker
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/download/DownloadNotificationManager.kt
  app/src/main/java/com/nextcloud/client/jobs/download/FileDownloadWorker.kt
  app/src/main/java/com/nextcloud/client/jobs/notification/WorkerNotificationManager.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/UploadNotificationManager.kt
  app/src/main/java/com/nextcloud/utils/numberFormatter/NumberFormatter.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review

#14630 Fix ecosystem app switcher spacing
  app/screenshots/gplay/debug/com.nextcloud.client.UploadListActivityActivityIT_openDrawer.png
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/res/layout/drawer_header.xml
Labels: 3. to review

#14528 Do not release video player on pause
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.kt
Labels: 3. to review, backport-request

#14565 Use Common Library For System Bars
  app/build.gradle
  app/src/main/java/com/nextcloud/utils/extensions/WindowExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/BaseActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/SettingsActivity.java
  appscan/build.gradle
  appscan/src/main/java/com/nextcloud/appscan/AppScanActivity.kt
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#14625 Remove Airplane mode Check Due to Configurable Unmetered Wi-Fi
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
Labels: 3. to review, backport-request

#14626 Improve E2EE dialog description for better clarity
  app/src/main/java/com/owncloud/android/ui/dialog/setupEncryption/SetupEncryptionDialogFragment.kt
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#14566 BugFix - Auto Rename File Extension
  app/src/androidTest/java/com/nextcloud/utils/AutoRenameTests.kt
  app/src/main/java/com/nextcloud/utils/autoRename/AutoRename.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to review, backport-request

#14641 Bump to AGP 8.9.0
  app/src/main/java/com/nextcloud/client/etm/pages/EtmBackgroundJobsFragment.kt
  app/src/main/java/com/nextcloud/client/etm/pages/EtmFileTransferFragment.kt
  app/src/main/java/com/nextcloud/client/migrations/MigrationsDb.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetService.kt
  app/src/main/java/com/nextcloud/client/widget/DashboardWidgetUpdater.kt
  app/src/main/java/com/nextcloud/client/widget/WidgetRepository.kt
  app/src/main/java/com/nextcloud/ui/ImageDetailFragment.kt
  app/src/main/java/com/nextcloud/utils/LinkHelper.kt
  app/src/main/java/com/nextcloud/utils/ShortcutUtil.kt
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorAsyncTask.kt
  app/src/main/java/com/owncloud/android/ui/activity/RichDocumentsEditorWebView.kt
  app/src/main/java/com/owncloud/android/ui/activity/SyncedFoldersActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/TextEditorWebView.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/adapter/UnifiedSearchListAdapter.kt
  app/src/main/java/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ProfileBottomSheetDialog.kt
  app/src/main/java/com/owncloud/android/ui/fragment/util/GalleryFastScrollViewHelper.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaActivity.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewMediaFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/pdf/PreviewPdfAdapter.kt
  app/src/main/java/com/owncloud/android/ui/unifiedsearch/UnifiedSearchViewModel.kt
  app/src/main/java/com/owncloud/android/utils/PermissionUtil.kt
  build.gradle
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
  scripts/analysis/lint-results.txt
Labels: 3. to review, dependencies

#14561 Prepare for build with *.kts files
  app/build.gradle
  appscan/.gitignore
  appscan/build.gradle
  build.gradle
  jacoco.gradle
  scripts/analysis/detectWrongSettings.sh
  settings.gradle
Labels: 3. to review, feedback-requested, ♻️ refactor

#14562 Fix deprecated github action and simplify CI
  .github/workflows/assembleFlavors.yml
  .github/workflows/gradle-wrapper-validation.yml
Labels: 3. to review, feedback-requested, ♻️ refactor

#14544 fix(richdocuments): Let new file load on creation
  app/src/main/java/com/owncloud/android/ui/activity/EditorWebView.java
Labels: bug, 3. to review, feature: editor, feedback-requested

#14590 Optional Tag Removal
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
Labels: 3. to review, technical debt

#14589 fix obsolete method plus force use of type
  app/src/main/java/com/owncloud/android/ui/activity/DrawerActivity.java
  app/src/main/java/com/owncloud/android/utils/DisplayUtils.java
  app/src/main/java/third_parties/sufficientlysecure/SaveCalendar.java
Labels: 3. to review, technical debt, feedback-requested

#14663 BugFix - AuthenticatorActivity Add LifeCycle Observer For Both Condition
  app/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java
Labels: 3. to review, backport-request

#14658 Fix - ChooseStorageLocationDialogFragment NoSuchElementException
  app/src/main/java/com/nextcloud/ui/ChooseStorageLocationDialogFragment.kt
Labels: 3. to review, backport-request

#14676 BugFix - Highlight Tab Layout When Scrolled
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
Labels: 3. to review, backport-request

#14659 BugFix - Auto Rename Creating New folder
  app/src/androidTest/java/com/nextcloud/utils/AutoRenameTests.kt
  app/src/main/java/com/nextcloud/utils/autoRename/AutoRename.kt
  app/src/main/java/com/owncloud/android/ui/dialog/CreateFolderDialogFragment.kt
Labels: 3. to review, backport-request

#14646 showDirectoryWhenDeletionCompleted set to false?
  app/src/main/java/com/owncloud/android/ui/dialog/RemoveFilesDialogFragment.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
Labels: 3. to review, backport-request

#14640 BugFix - E2EE Rename NameCollision
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to review, backport-request

#14670 BugFix - Use Previous eTag for Shared Folder If Exists
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt
Labels: 3. to review

#14671 BugFix - E2EE Image Preview
  app/src/main/java/com/owncloud/android/ui/preview/FileDownloadFragment.java
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImageActivity.kt
  app/src/main/java/com/owncloud/android/ui/preview/PreviewImagePagerAdapter.kt
Labels: 3. to review

#14674 Use sentence style capitalization
  app/screenshots/gplay/debug/com.nextcloud.client.etm.EtmActivityTest_overview.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.dialog.DialogFragmentIT_testFileActionsBottomSheet.png
  app/screenshots/gplay/debug/com.owncloud.android.ui.fragment.OCFileListFragmentStaticServerIT_showFolderTypes.png
  app/src/main/res/layout/list_header.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, backport-request

#14611 Feature - Media Multi Select
  app/src/main/java/com/nextcloud/utils/extensions/FragmentExtensions.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java
  app/src/main/java/com/owncloud/android/ui/adapter/CommonOCFileListAdapterInterface.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryAdapter.kt
  app/src/main/java/com/owncloud/android/ui/adapter/GalleryRowHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: enhancement, 3. to review
