Repository nextcloud/android, pull requests merged in 2025-09, with the labels that each got.

#15501 fix: add account name to fetch recommended files
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/92.json
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/dao/RecommendedFileDao.kt
  app/src/main/java/com/nextcloud/client/database/entity/RecommendedFileEntity.kt
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  app/src/main/java/com/owncloud/android/ui/fragment/filesRepository/FilesRepository.kt
  app/src/main/java/com/owncloud/android/ui/fragment/filesRepository/RemoteFilesRepository.kt
Labels: 3. to review

#15495 feat: add recommended item view holder
  app/src/main/java/com/nextcloud/client/database/entity/RecommendedFileEntity.kt
  app/src/main/java/com/nextcloud/ui/fileactions/FileAction.kt
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListAdapter.java
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListDelegate.kt
  app/src/main/java/com/owncloud/android/ui/adapter/OCFileListRecommendedItemViewHolder.kt
  app/src/main/java/com/owncloud/android/ui/adapter/RecommendedFilesAdapter.kt
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/drawable/ic_dots_horizontal.xml
  app/src/main/res/layout/recommended_file_item.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
Labels: 3. to review, ux-enhancement

#15440 feat: metadata worker 🚀
  app/src/androidTest/java/com/nextcloud/extensions/StringExtensionTests.kt
  app/src/main/java/com/nextcloud/client/database/dao/FileDao.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobFactory.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManager.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/metadata/MetadataWorker.kt
  app/src/main/java/com/nextcloud/utils/extensions/FileDataStorageManagerExtensions.kt
  app/src/main/java/com/nextcloud/utils/extensions/StringExtensions.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/datamodel/OCFile.java
  app/src/main/java/com/owncloud/android/operations/RefreshFolderOperation.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java
Labels: 3. to review, performance 🚀

#15459 Drop NC18/19
  app/src/androidTest/java/com/nextcloud/client/account/RegisteredUserTest.kt
  app/src/androidTest/java/com/nextcloud/client/files/DeepLinkHandlerTest.kt
  app/src/androidTest/java/com/owncloud/android/utils/theme/CapabilityUtilsIT.kt
  app/src/main/java/com/owncloud/android/MainApp.java
  app/src/main/java/com/owncloud/android/ui/activity/FileActivity.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailSharingFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/FileDetailsSharingProcessFragment.kt
  app/src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#15475 fix: empty list state handling
  app/src/androidTest/java/com/nextcloud/client/FileDisplayActivityScreenshotIT.kt
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListSearchAsyncTask.kt
  app/src/main/java/com/owncloud/android/ui/fragment/SearchType.kt
Labels: 3. to review, ux-enhancement

#15536 fix: manage space activity screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/owncloud/android/ui/activity/ManageSpaceActivity.kt
  app/src/main/res/layout/activity_manage_space.xml
Labels: 3. to review, backport-request, performance 🚀, ux-enhancement

#15441 split up set status dialog
  app/schemas/com.nextcloud.client.database.NextcloudDatabase/93.json
  app/src/androidTest/java/com/nextcloud/ui/SetOnlineStatusBottomSheetIT.kt
  app/src/androidTest/java/com/nextcloud/ui/SetStatusMessageBottomSheetIT.kt
  app/src/androidTest/java/com/owncloud/android/ui/dialog/DialogFragmentIT.kt
  app/src/main/java/com/nextcloud/client/database/NextcloudDatabase.kt
  app/src/main/java/com/nextcloud/client/database/entity/CapabilityEntity.kt
  app/src/main/java/com/nextcloud/client/di/ComponentsModule.java
  app/src/main/java/com/nextcloud/ui/ChooseAccountDialogFragment.kt
  app/src/main/java/com/nextcloud/ui/SetOnlineStatusBottomSheet.kt
  app/src/main/java/com/nextcloud/ui/SetStatusMessageBottomSheet.kt
  app/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java
  app/src/main/java/com/owncloud/android/db/ProviderMeta.java
  app/src/main/java/com/owncloud/android/ui/StatusDrawable.java
  app/src/main/java/com/owncloud/android/utils/theme/FilesSpecificViewThemeUtils.kt
  app/src/main/res/drawable/chat_bubble.xml
  app/src/main/res/drawable/ic_user_status_away.xml
  app/src/main/res/drawable/ic_user_status_busy.xml
  app/src/main/res/drawable/ic_user_status_dnd.xml
  app/src/main/res/drawable/ic_user_status_invisible.xml
  app/src/main/res/drawable/online_status.xml
  app/src/main/res/layout/dialog_choose_account.xml
  app/src/main/res/layout/dialog_set_status.xml
  app/src/main/res/layout/predefined_status.xml
  app/src/main/res/layout/set_online_status_bottom_sheet.xml
  app/src/main/res/layout/set_status_message_bottom_sheet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dims.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/verification-metadata.xml
Labels: 3. to review

#15449 fix: correct query to fetch uploads by IDs and account name
  app/src/main/java/com/nextcloud/client/database/dao/UploadDao.kt
  app/src/main/java/com/nextcloud/client/database/entity/UploadEntity.kt
  app/src/main/java/com/nextcloud/client/jobs/BackgroundJobManagerImpl.kt
  app/src/main/java/com/nextcloud/client/jobs/upload/FileUploadWorker.kt
  app/src/main/java/com/owncloud/android/datamodel/UploadsStorageManager.java
Labels: backport-request, don't merge

#15543 Style(status): 50/50 button sizing
  app/src/main/res/layout/dialog_choose_account.xml
Labels: bug, design, 3. to review

#15571 Status: no background for emojis
  app/src/main/java/com/owncloud/android/ui/StatusDrawable.java
  app/src/main/res/drawable/ic_user_status_online.xml
  app/src/main/res/layout/account_item.xml
Labels: 3. to review

#15576 fix: accessing result data
  app/src/main/java/com/owncloud/android/operations/CreateFolderOperation.java
  app/src/main/java/com/owncloud/android/operations/SynchronizeFolderOperation.java
Labels: 2. developing, don't merge

#15529 feat: do not show loading spinner
  app/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.kt
  app/src/main/java/com/owncloud/android/ui/activity/FolderPickerActivity.kt
  app/src/main/java/com/owncloud/android/ui/fragment/ExtendedListFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/GalleryFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/GroupfolderListFragment.kt
  app/src/main/java/com/owncloud/android/ui/fragment/LocalFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListSearchAsyncTask.kt
  app/src/main/java/com/owncloud/android/ui/fragment/SharedListFragment.kt
Labels: 3. to review

#15602 chore: bump version to v3.33.0
  app/build.gradle
  fastlane/metadata/android/en-US/changelogs/30330090.txt
  fastlane/metadata/android/en-US/changelogs/30330090.txt.license
Labels: 3. to review

#15589 SpotBugs: Fix Method ignores exceptional return value - PushUtils
  app/src/gplay/java/com/owncloud/android/utils/PushUtils.java
Labels: 3. to review, technical debt, feedback-requested

#15590 SpotBugs: Fix Method ignores exceptional return value - DownloadFileOperation
  app/src/main/java/com/owncloud/android/operations/DownloadFileOperation.java
Labels: 3. to review, technical debt, feedback-requested

#15592 SpotBugs: Fix Method ignores exceptional return value - UploadFileOperation
  app/src/main/java/com/owncloud/android/operations/UploadFileOperation.java
Labels: 3. to review, technical debt, feedback-requested

#15596 SpotBugs: Fix Method ignores exceptional return value - OCFileListFragment
  app/src/main/java/com/owncloud/android/ui/fragment/OCFileListFragment.java
Labels: 3. to review, technical debt, feedback-requested

#15594 SpotBugs: Fix Method ignores exceptional return value - StorageMigration
  app/src/main/java/com/owncloud/android/ui/activity/StorageMigration.java
Labels: 3. to review, technical debt, feedback-requested
